libspatialindex API Reference: SpatialIndex::RTree::Leaf Class Reference
SpatialIndex::RTree::Leaf Class Reference
#include <Leaf.h>
Public Member Functions
virtual ~Leaf ()
Public Member Functions inherited from SpatialIndex::RTree::Node
virtual ~Node ()
virtual Tools::IObject * clone ()
virtual uint32_t getByteArraySize ()
virtual void loadFromByteArray (const byte *data)
virtual void storeToByteArray (byte **data, uint32_t &len)
virtual id_type getIdentifier () const
virtual void getShape (IShape **out) const
virtual uint32_t getChildrenCount () const
virtual id_type getChildIdentifier (uint32_t index) const
virtual void getChildShape (uint32_t index, IShape **out) const
virtual void getChildData (uint32_t index, uint32_t &length, byte **data) const
virtual uint32_t getLevel () const
virtual bool isIndex () const
virtual bool isLeaf () const
Public Member Functions inherited from SpatialIndex::INode
virtual ~INode ()
Public Member Functions inherited from SpatialIndex::IEntry
virtual ~IEntry ()
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()
Protected Member Functions
Leaf (RTree *pTree, id_type id)
virtual NodePtr chooseSubtree (const Region &mbr, uint32_t level, std::stack< id_type > &pathBuffer)
virtual NodePtr findLeaf (const Region &mbr, id_type id, std::stack< id_type > &pathBuffer)
virtual void split (uint32_t dataLength, byte *pData, Region &mbr, id_type id, NodePtr &left, NodePtr &right)
virtual void deleteData (id_type id, std::stack< id_type > &pathBuffer)
Friends
class RTree
class BulkLoader
Detailed Description
Definition at line 34 of file rtree/Leaf.h.
Constructor & Destructor Documentation
Leaf::~Leaf () virtual
Definition at line 40 of file rtree/Leaf.cc.
Leaf::Leaf (RTree * pTree, id_type id) protected
Definition at line 44 of file rtree/Leaf.cc.
Referenced by split().
Member Function Documentation
NodePtr Leaf::chooseSubtree (const Region & mbr, uint32_t level, std::stack< id_type > & pathBuffer) protected virtual
Implements SpatialIndex::RTree::Node.
Definition at line 48 of file rtree/Leaf.cc.
void Leaf::deleteData (id_type id, std::stack< id_type > & pathBuffer) protected virtual
Definition at line 112 of file rtree/Leaf.cc.
References Tools::PoolPointer< X >::get(), and Tools::PoolPointer< X >::relinquish().
NodePtr Leaf::findLeaf (const Region & mbr, id_type id, std::stack< id_type > & pathBuffer) protected virtual
Implements SpatialIndex::RTree::Node.
Definition at line 55 of file rtree/Leaf.cc.
void Leaf::split (uint32_t dataLength, byte * pData, Region & mbr, id_type id, NodePtr & left, NodePtr & right) protected virtual
Implements SpatialIndex::RTree::Node.
Definition at line 67 of file rtree/Leaf.cc.
References Tools::PoolPointer< X >::get(), Leaf(), SpatialIndex::RTree::RV_LINEAR, SpatialIndex::RTree::RV_QUADRATIC, and SpatialIndex::RTree::RV_RSTAR.
Friends And Related Function Documentation
friend class BulkLoader friend
Definition at line 50 of file rtree/Leaf.h.
friend class RTree friend
Definition at line 49 of file rtree/Leaf.h.
The documentation for this class was generated from the following files:
rtree/Leaf.h
rtree/Leaf.cc