libspatialindex API Reference: SpatialIndex::RTree::ExternalSorter Class Reference
SpatialIndex::RTree::ExternalSorter Class Reference
#include <BulkLoader.h>
Classes
class Record
Public Member Functions
ExternalSorter (uint32_t u32PageSize, uint32_t u32BufferPages)
virtual ~ExternalSorter ()
void insert (Record *r)
void sort ()
Record * getNextRecord ()
uint64_t getTotalEntries () const
Detailed Description
Definition at line 34 of file BulkLoader.h.
Constructor & Destructor Documentation
ExternalSorter::ExternalSorter (uint32_t u32PageSize, uint32_t u32BufferPages)
Definition at line 120 of file BulkLoader.cc.
ExternalSorter::~ExternalSorter () virtual
Definition at line 126 of file BulkLoader.cc.
Member Function Documentation
ExternalSorter::Record * ExternalSorter::getNextRecord ()
Definition at line 287 of file BulkLoader.cc.
References Tools::SmartPointer< X >::get(), and SpatialIndex::RTree::ExternalSorter::Record::loadFromFile().
Referenced by SpatialIndex::RTree::BulkLoader::createLevel().
uint64_t ExternalSorter::getTotalEntries () const inline
Definition at line 314 of file BulkLoader.cc.
Referenced by SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), and SpatialIndex::RTree::BulkLoader::createLevel().
void ExternalSorter::insert (Record * r)
Definition at line 131 of file BulkLoader.cc.
Referenced by SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), and SpatialIndex::RTree::BulkLoader::createLevel().
void ExternalSorter::sort ()
Definition at line 156 of file BulkLoader.cc.
References SpatialIndex::RTree::ExternalSorter::Record::loadFromFile(), SpatialIndex::RTree::ExternalSorter::Record::m_r, and Tools::TemporaryFile::rewindForReading().
Referenced by SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), and SpatialIndex::RTree::BulkLoader::createLevel().
The documentation for this class was generated from the following files:
BulkLoader.h
BulkLoader.cc