libspatialindex API Reference: SpatialIndex::TPRTree::Statistics Class Reference
SpatialIndex::TPRTree::Statistics Class Reference
#include <Statistics.h>
Public Member Functions
Statistics ()
Statistics (const Statistics &)
~Statistics () override
Statistics & operator= (const Statistics &)
uint64_t getReads () const override
uint64_t getWrites () const override
uint32_t getNumberOfNodes () const override
uint64_t getNumberOfData () const override
virtual uint64_t getSplits () const
virtual uint64_t getHits () const
virtual uint64_t getMisses () const
virtual uint64_t getAdjustments () const
virtual uint64_t getQueryResults () const
virtual uint32_t getTreeHeight () const
virtual uint32_t getNumberOfNodesInLevel (uint32_t l) const
Public Member Functions inherited from SpatialIndex::IStatistics
virtual ~IStatistics ()=default
Friends
class TPRTree
class Node
class Index
class Leaf
class BulkLoader
std::ostream & operator<< (std::ostream &os, const Statistics &s)
Detailed Description
Definition at line 39 of file tprtree/Statistics.h.
Constructor & Destructor Documentation
Statistics() [1/2]
Statistics::Statistics ()
Definition at line 34 of file tprtree/Statistics.cc.
Statistics() [2/2]
Statistics::Statistics (const Statistics & s)
Definition at line 39 of file tprtree/Statistics.cc.
References ~Statistics().
~Statistics()
Statistics::~Statistics () override default
Referenced by Statistics().
Member Function Documentation
getAdjustments()
uint64_t Statistics::getAdjustments () const virtual
Definition at line 112 of file tprtree/Statistics.cc.
getHits()
uint64_t Statistics::getHits () const virtual
Definition at line 102 of file tprtree/Statistics.cc.
getMisses()
uint64_t Statistics::getMisses () const virtual
Definition at line 107 of file tprtree/Statistics.cc.
getNumberOfData()
uint64_t Statistics::getNumberOfData () const override virtual
Implements SpatialIndex::IStatistics.
Definition at line 92 of file tprtree/Statistics.cc.
Referenced by SpatialIndex::TPRTree::operator<<().
getNumberOfNodes()
uint32_t Statistics::getNumberOfNodes () const override virtual
Implements SpatialIndex::IStatistics.
Definition at line 87 of file tprtree/Statistics.cc.
getNumberOfNodesInLevel()
uint32_t Statistics::getNumberOfNodesInLevel (uint32_t l) const virtual
Definition at line 127 of file tprtree/Statistics.cc.
Referenced by SpatialIndex::TPRTree::operator<<().
getQueryResults()
uint64_t Statistics::getQueryResults () const virtual
Definition at line 117 of file tprtree/Statistics.cc.
getReads()
uint64_t Statistics::getReads () const override virtual
Implements SpatialIndex::IStatistics.
Definition at line 77 of file tprtree/Statistics.cc.
getSplits()
uint64_t Statistics::getSplits () const virtual
Definition at line 97 of file tprtree/Statistics.cc.
getTreeHeight()
uint32_t Statistics::getTreeHeight () const virtual
Definition at line 122 of file tprtree/Statistics.cc.
getWrites()
uint64_t Statistics::getWrites () const override virtual
Implements SpatialIndex::IStatistics.
Definition at line 82 of file tprtree/Statistics.cc.
operator=()
Statistics & Statistics::operator= (const Statistics & s)
Definition at line 57 of file tprtree/Statistics.cc.
Friends And Related Function Documentation
BulkLoader
friend class BulkLoader friend
Definition at line 92 of file tprtree/Statistics.h.
Index
friend class Index friend
Definition at line 90 of file tprtree/Statistics.h.
Leaf
friend class Leaf friend
Definition at line 91 of file tprtree/Statistics.h.
Node
friend class Node friend
Definition at line 89 of file tprtree/Statistics.h.
operator<<
std::ostream& operator<< (std::ostream & os, const Statistics & s) friend
TPRTree
friend class TPRTree friend
Definition at line 88 of file tprtree/Statistics.h.
The documentation for this class was generated from the following files:
tprtree/Statistics.h
tprtree/Statistics.cc