libspatialindex API Reference: ObjVisitor Class Reference
ObjVisitor Class Reference
#include <ObjVisitor.h>
Public Member Functions
ObjVisitor ()
~ObjVisitor ()
uint64_t GetResultCount () const
std::vector< SpatialIndex::IData * > & GetResults ()
void visitNode (const SpatialIndex::INode &n)
void visitData (const SpatialIndex::IData &d)
void visitData (std::vector< const SpatialIndex::IData *> &v)
Public Member Functions inherited from SpatialIndex::IVisitor
virtual ~IVisitor ()=default
Detailed Description
Definition at line 33 of file ObjVisitor.h.
Constructor & Destructor Documentation
ObjVisitor()
ObjVisitor::ObjVisitor ()
Definition at line 31 of file ObjVisitor.cc.
~ObjVisitor()
ObjVisitor::~ObjVisitor ()
Definition at line 35 of file ObjVisitor.cc.
Member Function Documentation
GetResultCount()
uint64_t ObjVisitor::GetResultCount () const inline
Definition at line 44 of file ObjVisitor.h.
Referenced by Page_ResultSet_Obj().
GetResults()
std::vector<SpatialIndex::IData*>& ObjVisitor::GetResults () inline
Definition at line 45 of file ObjVisitor.h.
References SpatialIndex::IVisitor::visitData(), and SpatialIndex::IVisitor::visitNode().
Referenced by Page_ResultSet_Obj().
visitData() [1/2]
void ObjVisitor::visitData (const SpatialIndex::IData & d) virtual
Implements SpatialIndex::IVisitor.
Definition at line 48 of file ObjVisitor.cc.
visitData() [2/2]
void ObjVisitor::visitData (std::vector< const SpatialIndex::IData *> & v) virtual
Implements SpatialIndex::IVisitor.
Definition at line 58 of file ObjVisitor.cc.
visitNode()
void ObjVisitor::visitNode (const SpatialIndex::INode & n) virtual
Implements SpatialIndex::IVisitor.
Definition at line 44 of file ObjVisitor.cc.
The documentation for this class was generated from the following files:
ObjVisitor.h
ObjVisitor.cc