libspatialindex API Reference: CountVisitor Class Reference
CountVisitor Class Reference
#include <CountVisitor.h>
Public Member Functions
CountVisitor ()
~CountVisitor ()
uint64_t GetResultCount () const
void visitNode (const SpatialIndex::INode &n)
void visitData (const SpatialIndex::IData &d)
void visitData (std::vector< const SpatialIndex::IData *> &v)
Public Member Functions inherited from SpatialIndex::IVisitor
virtual ~IVisitor ()=default
Detailed Description
Definition at line 33 of file CountVisitor.h.
Constructor & Destructor Documentation
CountVisitor()
CountVisitor::CountVisitor ()
Definition at line 31 of file CountVisitor.cc.
~CountVisitor()
CountVisitor::~CountVisitor ()
Definition at line 35 of file CountVisitor.cc.
Member Function Documentation
GetResultCount()
uint64_t CountVisitor::GetResultCount () const inline
Definition at line 43 of file CountVisitor.h.
References SpatialIndex::IVisitor::visitData(), and SpatialIndex::IVisitor::visitNode().
Referenced by Index_Contains_count(), Index_Intersects_count(), Index_MVRIntersects_count(), Index_SegmentIntersects_count(), and Index_TPIntersects_count().
visitData() [1/2]
void CountVisitor::visitData (const SpatialIndex::IData & d) virtual
Implements SpatialIndex::IVisitor.
Definition at line 45 of file CountVisitor.cc.
visitData() [2/2]
void CountVisitor::visitData (std::vector< const SpatialIndex::IData *> & v) virtual
Implements SpatialIndex::IVisitor.
Definition at line 50 of file CountVisitor.cc.
visitNode()
void CountVisitor::visitNode (const SpatialIndex::INode & n) virtual
Implements SpatialIndex::IVisitor.
Definition at line 40 of file CountVisitor.cc.
The documentation for this class was generated from the following files:
CountVisitor.h
CountVisitor.cc