libspatialindex API Reference: SpatialIndex::MovingPoint Class Reference
SpatialIndex::MovingPoint Class Reference
#include <MovingPoint.h>
Public Member Functions
MovingPoint ()
MovingPoint (const double *pCoords, const double *pVCoords, const Tools::IInterval &ti, uint32_t dimension)
MovingPoint (const double *pCoords, const double *pVCoords, double tStart, double tEnd, uint32_t dimension)
MovingPoint (const Point &p, const Point &vp, const Tools::IInterval &ti)
MovingPoint (const Point &p, const Point &vp, double tStart, double tEnd)
MovingPoint (const MovingPoint &p)
~MovingPoint () override
virtual MovingPoint & operator= (const MovingPoint &p)
virtual bool operator== (const MovingPoint &p) const
virtual double getCoord (uint32_t index, double t) const
virtual double getProjectedCoord (uint32_t index, double t) const
virtual double getVCoord (uint32_t index) const
virtual void getPointAtTime (double t, Point &out) const
MovingPoint * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const byte *data) override
void storeToByteArray (byte **data, uint32_t &len) override
void getVMBR (Region &out) const override
void getMBRAtTime (double t, Region &out) const override
void makeInfinite (uint32_t dimension) override
void makeDimension (uint32_t dimension) override
Public Member Functions inherited from SpatialIndex::TimePoint
TimePoint ()
TimePoint (const double *pCoords, const Tools::IInterval &ti, uint32_t dimension)
TimePoint (const double *pCoords, double tStart, double tEnd, uint32_t dimension)
TimePoint (const Point &p, const Tools::IInterval &ti)
TimePoint (const Point &p, double tStart, double tEnd)
TimePoint (const TimePoint &p)
~TimePoint () override
virtual TimePoint & operator= (const TimePoint &p)
virtual bool operator== (const TimePoint &p) const
TimePoint * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const byte *data) override
void storeToByteArray (byte **data, uint32_t &len) override
bool intersectsShapeInTime (const ITimeShape &in) const override
bool intersectsShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
bool containsShapeInTime (const ITimeShape &in) const override
bool containsShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
bool touchesShapeInTime (const ITimeShape &in) const override
bool touchesShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
double getAreaInTime () const override
double getAreaInTime (const Tools::IInterval &ivI) const override
double getIntersectingAreaInTime (const ITimeShape &r) const override
double getIntersectingAreaInTime (const Tools::IInterval &ivI, const ITimeShape &r) const override
virtual Tools::IInterval & operator= (const Tools::IInterval &)
double getLowerBound () const override
double getUpperBound () const override
void setBounds (double, double) override
bool intersectsInterval (const Tools::IInterval &ti) const override
bool intersectsInterval (Tools::IntervalType t, const double start, const double end) const override
bool containsInterval (const Tools::IInterval &ti) const override
Tools::IntervalType getIntervalType () const override
void makeInfinite (uint32_t dimension) override
void makeDimension (uint32_t dimension) override
Public Member Functions inherited from SpatialIndex::Point
Point ()
Point (const double *pCoords, uint32_t dimension)
Point (const Point &p)
~Point () override
virtual Point & operator= (const Point &p)
virtual bool operator== (const Point &p) const
bool intersectsShape (const IShape &in) const override
bool containsShape (const IShape &in) const override
bool touchesShape (const IShape &in) const override
void getCenter (Point &out) const override
uint32_t getDimension () const override
void getMBR (Region &out) const override
double getArea () const override
double getMinimumDistance (const IShape &in) const override
virtual double getMinimumDistance (const Point &p) const
virtual double getCoordinate (uint32_t index) const
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
Public Member Functions inherited from SpatialIndex::IShape
~IShape () override=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Public Member Functions inherited from SpatialIndex::ITimeShape
~ITimeShape () override=default
Public Member Functions inherited from Tools::IInterval
virtual ~IInterval ()=default
Public Member Functions inherited from SpatialIndex::IEvolvingShape
virtual ~IEvolvingShape ()=default
Public Attributes
double * m_pVCoords
Public Attributes inherited from SpatialIndex::TimePoint
double m_startTime
double m_endTime
Public Attributes inherited from SpatialIndex::Point
uint32_t m_dimension {0}
double * m_pCoords {nullptr}
Friends
SIDX_DLL std::ostream & operator<< (std::ostream &os, const MovingPoint &pt)
Detailed Description
Definition at line 32 of file MovingPoint.h.
Constructor & Destructor Documentation
MovingPoint() [1/6]
MovingPoint::MovingPoint () default
Referenced by clone(), and MovingPoint().
MovingPoint() [2/6]
SpatialIndex::MovingPoint::MovingPoint (const double * pCoords, const double * pVCoords, const Tools::IInterval & ti, uint32_t dimension)
MovingPoint() [3/6]
MovingPoint::MovingPoint (const double * pCoords, const double * pVCoords, double tStart, double tEnd, uint32_t dimension)
Definition at line 51 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Point::m_pCoords, and MovingPoint().
MovingPoint() [4/6]
SpatialIndex::MovingPoint::MovingPoint (const Point & p, const Point & vp, const Tools::IInterval & ti)
MovingPoint() [5/6]
MovingPoint::MovingPoint (const Point & p, const Point & vp, double tStart, double tEnd)
Definition at line 74 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, and SpatialIndex::Point::m_pCoords.
MovingPoint() [6/6]
MovingPoint::MovingPoint (const MovingPoint & p)
Definition at line 86 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
~MovingPoint()
MovingPoint::~MovingPoint () override
Definition at line 109 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
Member Function Documentation
clone()
MovingPoint * MovingPoint::clone () override virtual
Implements Tools::IObject.
Definition at line 214 of file MovingPoint.cc.
References MovingPoint().
getByteArraySize()
uint32_t MovingPoint::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 222 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension.
Referenced by storeToByteArray().
getCoord()
double MovingPoint::getCoord (uint32_t index, double t) const virtual
Definition at line 179 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
Referenced by getMBRAtTime(), and getPointAtTime().
getMBRAtTime()
void MovingPoint::getMBRAtTime (double t, Region & out) const override virtual
Implements SpatialIndex::IEvolvingShape.
Definition at line 272 of file MovingPoint.cc.
References getCoord(), SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, and SpatialIndex::Region::makeDimension().
getPointAtTime()
void MovingPoint::getPointAtTime (double t, Point & out) const virtual
Definition at line 202 of file MovingPoint.cc.
References getCoord(), SpatialIndex::Point::m_dimension, SpatialIndex::Point::m_pCoords, and SpatialIndex::Point::makeDimension().
getProjectedCoord()
double MovingPoint::getProjectedCoord (uint32_t index, double t) const virtual
Definition at line 188 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
Referenced by SpatialIndex::MovingRegion::containsPointInTime(), and SpatialIndex::MovingRegion::intersectsPointInTime().
getVCoord()
double MovingPoint::getVCoord (uint32_t index) const virtual
Definition at line 195 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, and m_pVCoords.
Referenced by SpatialIndex::MovingRegion::intersectsPointInTime().
getVMBR()
void MovingPoint::getVMBR (Region & out) const override virtual
Implements SpatialIndex::IEvolvingShape.
Definition at line 265 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVCoords, and SpatialIndex::Region::makeDimension().
loadFromByteArray()
void MovingPoint::loadFromByteArray (const byte * data) override virtual
Implements Tools::ISerializable.
Definition at line 227 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, SpatialIndex::TimePoint::m_startTime, and makeDimension().
makeDimension()
void MovingPoint::makeDimension (uint32_t dimension) override virtual
Reimplemented from SpatialIndex::Point.
Definition at line 295 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Point::m_pCoords, and m_pVCoords.
Referenced by loadFromByteArray(), makeInfinite(), and operator=().
makeInfinite()
void MovingPoint::makeInfinite (uint32_t dimension) override virtual
Reimplemented from SpatialIndex::Point.
Definition at line 282 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, SpatialIndex::TimePoint::m_startTime, and makeDimension().
operator=()
MovingPoint & MovingPoint::operator= (const MovingPoint & p) virtual
Definition at line 142 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, SpatialIndex::TimePoint::m_startTime, and makeDimension().
operator==()
bool MovingPoint::operator== (const MovingPoint & p) const virtual
Definition at line 157 of file MovingPoint.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
storeToByteArray()
void MovingPoint::storeToByteArray (byte ** data, uint32_t & len) override virtual
Implements Tools::ISerializable.
Definition at line 244 of file MovingPoint.cc.
References getByteArraySize(), SpatialIndex::Point::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::Point::m_pCoords, m_pVCoords, and SpatialIndex::TimePoint::m_startTime.
Friends And Related Function Documentation
operator<<
SIDX_DLL std::ostream& operator<< (std::ostream & os, const MovingPoint & pt) friend
Member Data Documentation
m_pVCoords
double* SpatialIndex::MovingPoint::m_pVCoords
Definition at line 78 of file MovingPoint.h.
Referenced by SpatialIndex::MovingRegion::containsPointInTime(), getCoord(), getProjectedCoord(), getVCoord(), getVMBR(), loadFromByteArray(), makeDimension(), makeInfinite(), MovingPoint(), SpatialIndex::MovingRegion::MovingRegion(), SpatialIndex::operator<<(), operator=(), operator==(), storeToByteArray(), and ~MovingPoint().
The documentation for this class was generated from the following files:
MovingPoint.h
MovingPoint.cc