libspatialindex API Reference: Tools::PoolPointer< X > Class Template Reference
Tools::PoolPointer< X > Class Template Reference
#include <PoolPointer.h>
Public Member Functions
PoolPointer (X *p=nullptr)
PoolPointer (X *p, PointerPool< X > *pPool) noexcept
~PoolPointer ()
PoolPointer (const PoolPointer &p) noexcept
PoolPointer & operator= (const PoolPointer &p)
X & operator* () const noexcept
X * operator-> () const noexcept
X * get () const noexcept
bool unique () const noexcept
void relinquish () noexcept
Detailed Description
template<class X>
class Tools::PoolPointer< X >
Definition at line 36 of file PoolPointer.h.
Constructor & Destructor Documentation
PoolPointer() [1/3]
template<class X> Tools::PoolPointer< X >::PoolPointer (X * p = nullptr) inline explicit
Definition at line 39 of file PoolPointer.h.
PoolPointer() [2/3]
template<class X> Tools::PoolPointer< X >::PoolPointer (X * p, PointerPool< X > * pPool) inline explicit noexcept
Definition at line 40 of file PoolPointer.h.
~PoolPointer()
template<class X> Tools::PoolPointer< X >::~PoolPointer () inline
Definition at line 41 of file PoolPointer.h.
PoolPointer() [3/3]
template<class X> Tools::PoolPointer< X >::PoolPointer (const PoolPointer< X > & p) inline noexcept
Definition at line 42 of file PoolPointer.h.
Member Function Documentation
get()
template<class X> X* Tools::PoolPointer< X >::get () const inline noexcept
Definition at line 55 of file PoolPointer.h.
Referenced by SpatialIndex::RTree::Index::adjustTree(), SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), SpatialIndex::RTree::Index::chooseSubtree(), SpatialIndex::RTree::Leaf::deleteData(), SpatialIndex::RTree::Index::findLeaf(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), SpatialIndex::RTree::Leaf::split(), SpatialIndex::RTree::Index::split(), SpatialIndex::TPRTree::Node::~Node(), SpatialIndex::RTree::Node::~Node(), and SpatialIndex::MVRTree::Node::~Node().
operator*()
template<class X> X& Tools::PoolPointer< X >::operator* () const inline noexcept
Definition at line 53 of file PoolPointer.h.
operator->()
template<class X> X* Tools::PoolPointer< X >::operator-> () const inline noexcept
Definition at line 54 of file PoolPointer.h.
operator=()
template<class X> PoolPointer& Tools::PoolPointer< X >::operator= (const PoolPointer< X > & p) inline
Definition at line 43 of file PoolPointer.h.
relinquish()
template<class X> void Tools::PoolPointer< X >::relinquish () inline noexcept
Definition at line 57 of file PoolPointer.h.
Referenced by SpatialIndex::RTree::Index::chooseSubtree(), SpatialIndex::RTree::Leaf::deleteData(), SpatialIndex::RTree::Index::findLeaf(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), and SpatialIndex::MVRTree::MVRTree::flush().
unique()
template<class X> bool Tools::PoolPointer< X >::unique () const inline noexcept
Definition at line 56 of file PoolPointer.h.
Referenced by SpatialIndex::RTree::Index::chooseSubtree(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), and Tools::PoolPointer< MovingRegion >::relinquish().
The documentation for this class was generated from the following file:
PoolPointer.h