libspatialindex API Reference: Tools::BufferedFileWriter Class Reference
Tools::BufferedFileWriter Class Reference
#include <Tools.h>
Public Member Functions
BufferedFileWriter ()
BufferedFileWriter (const std::string &sFileName, FileMode mode=CREATE, uint32_t u32BufferSize=32768)
~BufferedFileWriter () override
virtual void open (const std::string &sFileName, FileMode mode=CREATE)
void rewind () override
void seek (std::fstream::off_type offset) override
virtual void write (uint8_t i)
virtual void write (uint16_t i)
virtual void write (uint32_t i)
virtual void write (uint64_t i)
virtual void write (float i)
virtual void write (double i)
virtual void write (bool b)
virtual void write (const std::string &s)
virtual void write (uint32_t u32Len, uint8_t *pData)
Public Member Functions inherited from Tools::BufferedFile
BufferedFile (uint32_t u32BufferSize=16384)
virtual ~BufferedFile ()
virtual void close ()
virtual bool eof ()
Additional Inherited Members
Protected Attributes inherited from Tools::BufferedFile
std::fstream m_file
char * m_buffer
uint32_t m_u32BufferSize
bool m_bEOF {true}
Detailed Description
Definition at line 446 of file Tools.h.
Constructor & Destructor Documentation
BufferedFileWriter() [1/2]
Tools::BufferedFileWriter::BufferedFileWriter ()
Definition at line 925 of file Tools.cc.
References Tools::BufferedFileReader::open().
BufferedFileWriter() [2/2]
Tools::BufferedFileWriter::BufferedFileWriter (const std::string & sFileName, FileMode mode = CREATE, uint32_t u32BufferSize = 32768)
Definition at line 930 of file Tools.cc.
References open().
~BufferedFileWriter()
Tools::BufferedFileWriter::~BufferedFileWriter () override
Definition at line 936 of file Tools.cc.
References Tools::BufferedFile::m_file.
Member Function Documentation
open()
void Tools::BufferedFileWriter::open (const std::string & sFileName, FileMode mode = CREATE) virtual
Definition at line 941 of file Tools.cc.
References Tools::APPEND, Tools::CREATE, Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by BufferedFileWriter().
rewind()
void Tools::BufferedFileWriter::rewind () override virtual
Implements Tools::BufferedFile.
Definition at line 977 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::rewindForWriting().
seek()
void Tools::BufferedFileWriter::seek (std::fstream::off_type offset) override virtual
Implements Tools::BufferedFile.
Definition at line 986 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
write() [1/9]
void Tools::BufferedFileWriter::write (uint8_t i) virtual
Definition at line 995 of file Tools.cc.
References Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::write().
write() [2/9]
void Tools::BufferedFileWriter::write (uint16_t i) virtual
Definition at line 1001 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [3/9]
void Tools::BufferedFileWriter::write (uint32_t i) virtual
Definition at line 1007 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [4/9]
void Tools::BufferedFileWriter::write (uint64_t i) virtual
Definition at line 1013 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [5/9]
void Tools::BufferedFileWriter::write (float i) virtual
Definition at line 1019 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [6/9]
void Tools::BufferedFileWriter::write (double i) virtual
Definition at line 1025 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [7/9]
void Tools::BufferedFileWriter::write (bool b) virtual
Definition at line 1031 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [8/9]
void Tools::BufferedFileWriter::write (const std::string & s) virtual
Definition at line 1037 of file Tools.cc.
References Tools::BufferedFile::m_file.
write() [9/9]
void Tools::BufferedFileWriter::write (uint32_t u32Len, uint8_t * pData) virtual
Definition at line 1046 of file Tools.cc.
References Tools::BufferedFile::m_file.
The documentation for this class was generated from the following files:
Tools.h
Tools.cc