libspatialindex API Reference: SpatialIndex::INode Class Reference
SpatialIndex::INode Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual uint32_t getChildrenCount () const =0
virtual id_type getChildIdentifier (uint32_t index) const =0
virtual void getChildData (uint32_t index, uint32_t &len, uint8_t **data) const =0
virtual void getChildShape (uint32_t index, IShape **out) const =0
virtual uint32_t getLevel () const =0
virtual bool isIndex () const =0
virtual bool isLeaf () const =0
~INode () override=default
Public Member Functions inherited from SpatialIndex::IEntry
virtual id_type getIdentifier () const =0
virtual void getShape (IShape **out) const =0
~IEntry () override=default
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
virtual IObject * clone ()=0
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
virtual uint32_t getByteArraySize ()=0
virtual void loadFromByteArray (const uint8_t *data)=0
virtual void storeToByteArray (uint8_t **data, uint32_t &length)=0
Detailed Description
Definition at line 113 of file SpatialIndex.h.
Constructor & Destructor Documentation
~INode()
SpatialIndex::INode::~INode () override default
Member Function Documentation
getChildData()
virtual void SpatialIndex::INode::getChildData (uint32_t index, uint32_t & len, uint8_t ** data) const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
getChildIdentifier()
virtual id_type SpatialIndex::INode::getChildIdentifier (uint32_t index) const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
Referenced by get_results(), and LeafQuery::getNextEntry().
getChildrenCount()
virtual uint32_t SpatialIndex::INode::getChildrenCount () const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
Referenced by get_results(), and LeafQuery::getNextEntry().
getChildShape()
virtual void SpatialIndex::INode::getChildShape (uint32_t index, IShape ** out) const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
getLevel()
virtual uint32_t SpatialIndex::INode::getLevel () const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
Referenced by LeafQuery::getNextEntry().
isIndex()
virtual bool SpatialIndex::INode::isIndex () const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
isLeaf()
virtual bool SpatialIndex::INode::isLeaf () const pure virtual
Implemented in SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, and SpatialIndex::TPRTree::Node.
Referenced by LeafQuery::getNextEntry().
The documentation for this class was generated from the following file:
SpatialIndex.h