libspatialindex API Reference: SpatialIndex::StorageManager::Buffer Class Reference
SpatialIndex::StorageManager::Buffer Class Reference abstract
#include <Buffer.h>
Classes
class Entry
Public Member Functions
Buffer (IStorageManager &sm, Tools::PropertySet &ps)
~Buffer () override
void flush () override
void loadByteArray (const id_type page, uint32_t &len, byte **data) override
void storeByteArray (id_type &page, const uint32_t len, const byte *const data) override
void deleteByteArray (const id_type page) override
void clear () override
uint64_t getHits () override
Public Member Functions inherited from SpatialIndex::StorageManager::IBuffer
~IBuffer () override=default
Public Member Functions inherited from SpatialIndex::IStorageManager
virtual ~IStorageManager ()=default
Protected Member Functions
virtual void addEntry (id_type page, Entry *pEntry)=0
virtual void removeEntry ()=0
Protected Attributes
uint32_t m_capacity
bool m_bWriteThrough
IStorageManager * m_pStorageManager
std::map< id_type, Entry * > m_buffer
uint64_t m_u64Hits
Detailed Description
Definition at line 39 of file Buffer.h.
Constructor & Destructor Documentation
Buffer()
Buffer::Buffer (IStorageManager & sm, Tools::PropertySet & ps)
Definition at line 33 of file Buffer.cc.
References Tools::Variant::blVal, Tools::PropertySet::getProperty(), m_bWriteThrough, m_capacity, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_EMPTY, and Tools::VT_ULONG.
~Buffer()
Buffer::~Buffer () override
Definition at line 54 of file Buffer.cc.
References flush().
Member Function Documentation
addEntry()
virtual void SpatialIndex::StorageManager::Buffer::addEntry (id_type page, Entry * pEntry) protected pure virtual
Implemented in SpatialIndex::StorageManager::RandomEvictionsBuffer.
Referenced by loadByteArray(), and storeByteArray().
clear()
void Buffer::clear () override virtual
Implements SpatialIndex::StorageManager::IBuffer.
Definition at line 134 of file Buffer.cc.
References m_buffer, m_pStorageManager, m_u64Hits, and SpatialIndex::IStorageManager::storeByteArray().
deleteByteArray()
void Buffer::deleteByteArray (const id_type page) override virtual
Implements SpatialIndex::IStorageManager.
Definition at line 122 of file Buffer.cc.
References SpatialIndex::IStorageManager::deleteByteArray(), m_buffer, and m_pStorageManager.
flush()
void Buffer::flush () override virtual
Implements SpatialIndex::IStorageManager.
Definition at line 59 of file Buffer.cc.
References m_buffer, m_pStorageManager, and SpatialIndex::IStorageManager::storeByteArray().
Referenced by ~Buffer().
getHits()
uint64_t Buffer::getHits () override virtual
Implements SpatialIndex::StorageManager::IBuffer.
Definition at line 151 of file Buffer.cc.
References m_u64Hits.
loadByteArray()
void Buffer::loadByteArray (const id_type page, uint32_t & len, byte ** data) override virtual
Implements SpatialIndex::IStorageManager.
Definition at line 72 of file Buffer.cc.
References addEntry(), SpatialIndex::IStorageManager::loadByteArray(), m_buffer, m_pStorageManager, and m_u64Hits.
removeEntry()
virtual void SpatialIndex::StorageManager::Buffer::removeEntry () protected pure virtual
Implemented in SpatialIndex::StorageManager::RandomEvictionsBuffer.
storeByteArray()
void Buffer::storeByteArray (id_type & page, const uint32_t len, const byte *const data) override virtual
Implements SpatialIndex::IStorageManager.
Definition at line 90 of file Buffer.cc.
References addEntry(), SpatialIndex::StorageManager::Buffer::Entry::m_bDirty, m_buffer, m_bWriteThrough, m_pStorageManager, m_u64Hits, SpatialIndex::StorageManager::NewPage, and SpatialIndex::IStorageManager::storeByteArray().
Member Data Documentation
m_buffer
std::map<id_type, Entry*> SpatialIndex::StorageManager::Buffer::m_buffer protected
Definition at line 81 of file Buffer.h.
Referenced by SpatialIndex::StorageManager::RandomEvictionsBuffer::addEntry(), clear(), deleteByteArray(), flush(), loadByteArray(), SpatialIndex::StorageManager::RandomEvictionsBuffer::removeEntry(), and storeByteArray().
m_bWriteThrough
bool SpatialIndex::StorageManager::Buffer::m_bWriteThrough protected
Definition at line 79 of file Buffer.h.
Referenced by Buffer(), and storeByteArray().
m_capacity
uint32_t SpatialIndex::StorageManager::Buffer::m_capacity protected
Definition at line 78 of file Buffer.h.
Referenced by SpatialIndex::StorageManager::RandomEvictionsBuffer::addEntry(), and Buffer().
m_pStorageManager
IStorageManager* SpatialIndex::StorageManager::Buffer::m_pStorageManager protected
Definition at line 80 of file Buffer.h.
Referenced by clear(), deleteByteArray(), flush(), loadByteArray(), SpatialIndex::StorageManager::RandomEvictionsBuffer::removeEntry(), and storeByteArray().
m_u64Hits
uint64_t SpatialIndex::StorageManager::Buffer::m_u64Hits protected
Definition at line 82 of file Buffer.h.
Referenced by clear(), getHits(), loadByteArray(), and storeByteArray().
The documentation for this class was generated from the following files:
Buffer.h
Buffer.cc