libspatialindex API Reference: LeafQuery.cc File Reference
LeafQuery.cc File Reference
#include <spatialindex/capi/sidx_impl.h>
Functions
LeafQueryResult get_results (const SpatialIndex::INode *n)
Function Documentation
get_results()
LeafQueryResult get_results (const SpatialIndex::INode * n)
Definition at line 36 of file LeafQuery.cc.
References SpatialIndex::INode::getChildIdentifier(), SpatialIndex::INode::getChildrenCount(), SpatialIndex::IEntry::getIdentifier(), and SpatialIndex::IEntry::getShape().
Referenced by LeafQuery::getNextEntry().