libspatialindex API Reference: SpatialIndex::RTree Namespace Reference
SpatialIndex::RTree Namespace Reference
Classes
class BulkLoader
class Data
class ExternalSorter
class Index
class Leaf
class Node
class RTree
class Statistics
Typedefs
typedef Tools::PoolPointer< Node > NodePtr
Enumerations
enum RTreeVariant { RV_LINEAR = 0x0, RV_QUADRATIC, RV_RSTAR }
enum BulkLoadMethod { BLM_STR = 0x0 }
enum PersistenObjectIdentifier { PersistentIndex = 0x1, PersistentLeaf = 0x2 }
enum RangeQueryType { ContainmentQuery = 0x1, IntersectionQuery = 0x2 }
Functions
SIDX_DLL ISpatialIndex * returnRTree (IStorageManager &ind, Tools::PropertySet &in)
SIDX_DLL ISpatialIndex * createNewRTree (IStorageManager &sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, RTreeVariant rv, id_type &indexIdentifier)
SIDX_DLL ISpatialIndex * createAndBulkLoadNewRTree (BulkLoadMethod m, IDataStream &stream, IStorageManager &sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, RTreeVariant rv, id_type &indexIdentifier)
SIDX_DLL ISpatialIndex * createAndBulkLoadNewRTree (BulkLoadMethod m, IDataStream &stream, IStorageManager &sm, Tools::PropertySet &ps, id_type &indexIdentifier)
SIDX_DLL ISpatialIndex * loadRTree (IStorageManager &in, id_type indexIdentifier)
std::ostream & operator<< (std::ostream &os, const RTree &t)
std::ostream & operator<< (std::ostream &os, const Statistics &s)
Typedef Documentation
NodePtr
typedef Tools::PoolPointer<Node> SpatialIndex::RTree::NodePtr
Definition at line 40 of file rtree/Node.h.
Enumeration Type Documentation
BulkLoadMethod
enum SpatialIndex::RTree::BulkLoadMethod
Enumerator
BLM_STR
Definition at line 41 of file include/spatialindex/RTree.h.
PersistenObjectIdentifier
enum SpatialIndex::RTree::PersistenObjectIdentifier
Enumerator
PersistentIndex
PersistentLeaf
Definition at line 46 of file include/spatialindex/RTree.h.
RangeQueryType
enum SpatialIndex::RTree::RangeQueryType
Enumerator
ContainmentQuery
IntersectionQuery
Definition at line 52 of file include/spatialindex/RTree.h.
RTreeVariant
enum SpatialIndex::RTree::RTreeVariant
Enumerator
RV_LINEAR
RV_QUADRATIC
RV_RSTAR
Definition at line 34 of file include/spatialindex/RTree.h.
Function Documentation
createAndBulkLoadNewRTree() [1/2]
SpatialIndex::ISpatialIndex * SpatialIndex::RTree::createAndBulkLoadNewRTree (BulkLoadMethod m, IDataStream & stream, SpatialIndex::IStorageManager & sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, RTreeVariant rv, id_type & indexIdentifier)
Definition at line 190 of file RTree.cc.
References BLM_STR, SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), and createNewRTree().
Referenced by Index::Index().
createAndBulkLoadNewRTree() [2/2]
SpatialIndex::ISpatialIndex * SpatialIndex::RTree::createAndBulkLoadNewRTree (BulkLoadMethod m, IDataStream & stream, SpatialIndex::IStorageManager & sm, Tools::PropertySet & ps, id_type & indexIdentifier)
Definition at line 221 of file RTree.cc.
References BLM_STR, SpatialIndex::RTree::BulkLoader::bulkLoadUsingSTR(), createNewRTree(), Tools::Variant::dblVal, Tools::PropertySet::getProperty(), Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, RV_LINEAR, RV_QUADRATIC, RV_RSTAR, Tools::Variant::ulVal, Tools::VT_DOUBLE, Tools::VT_EMPTY, Tools::VT_LONG, and Tools::VT_ULONG.
createNewRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::RTree::createNewRTree (SpatialIndex::IStorageManager & sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, RTreeVariant rv, id_type & indexIdentifier)
Definition at line 149 of file RTree.cc.
References Tools::Variant::dblVal, Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnRTree(), Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
Referenced by createAndBulkLoadNewRTree().
loadRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::RTree::loadRTree (IStorageManager & in, id_type indexIdentifier)
Definition at line 346 of file RTree.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnRTree(), Tools::PropertySet::setProperty(), and Tools::VT_LONGLONG.
operator<<() [1/2]
std::ostream & SpatialIndex::RTree::operator<< (std::ostream & os, const Statistics & s)
Definition at line 157 of file rtree/Statistics.cc.
operator<<() [2/2]
std::ostream & SpatialIndex::RTree::operator<< (std::ostream & os, const RTree & t)
Definition at line 1546 of file RTree.cc.
References SpatialIndex::RTree::Statistics::getNumberOfData(), SpatialIndex::RTree::Statistics::getNumberOfNodesInLevel(), Tools::PointerPool< X >::m_hits, Tools::PointerPool< X >::m_misses, and RV_RSTAR.
returnRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::RTree::returnRTree (SpatialIndex::IStorageManager & sm, Tools::PropertySet & in)
Definition at line 143 of file RTree.cc.
Referenced by createNewRTree(), and loadRTree().