libspatialindex API Reference: SpatialIndex::StorageManager Namespace Reference
SpatialIndex::StorageManager Namespace Reference
Classes
class Buffer
class CustomStorageManager
struct CustomStorageManagerCallbacks
class DiskStorageManager
class IBuffer
class MemoryStorageManager
class RandomEvictionsBuffer
Enumerations
enum StorageManagerConstants { EmptyPage = -0x1, NewPage = -0x1 }
Functions
IStorageManager * returnCustomStorageManager (Tools::PropertySet &in)
SIDX_DLL IStorageManager * returnMemoryStorageManager (Tools::PropertySet &in)
SIDX_DLL IStorageManager * createNewMemoryStorageManager ()
SIDX_DLL IStorageManager * returnDiskStorageManager (Tools::PropertySet &in)
SIDX_DLL IStorageManager * createNewDiskStorageManager (std::string &baseName, uint32_t pageSize)
SIDX_DLL IStorageManager * loadDiskStorageManager (std::string &baseName)
SIDX_DLL IBuffer * returnRandomEvictionsBuffer (IStorageManager &ind, Tools::PropertySet &in)
SIDX_DLL IBuffer * createNewRandomEvictionsBuffer (IStorageManager &in, uint32_t capacity, bool bWriteThrough)
Enumeration Type Documentation
StorageManagerConstants
enum SpatialIndex::StorageManager::StorageManagerConstants
Enumerator
EmptyPage
NewPage
Definition at line 215 of file SpatialIndex.h.
Function Documentation
createNewDiskStorageManager()
SpatialIndex::IStorageManager * SpatialIndex::StorageManager::createNewDiskStorageManager (std::string & baseName, uint32_t pageSize)
Definition at line 90 of file DiskStorageManager.cc.
References Tools::Variant::blVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, returnDiskStorageManager(), Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_PCHAR, and Tools::VT_ULONG.
createNewMemoryStorageManager()
SpatialIndex::IStorageManager * SpatialIndex::StorageManager::createNewMemoryStorageManager ()
Definition at line 43 of file MemoryStorageManager.cc.
References returnMemoryStorageManager().
createNewRandomEvictionsBuffer()
IBuffer * SpatialIndex::StorageManager::createNewRandomEvictionsBuffer (IStorageManager & in, uint32_t capacity, bool bWriteThrough)
Definition at line 47 of file RandomEvictionsBuffer.cc.
References Tools::Variant::blVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnRandomEvictionsBuffer(), Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, and Tools::VT_ULONG.
loadDiskStorageManager()
SpatialIndex::IStorageManager * SpatialIndex::StorageManager::loadDiskStorageManager (std::string & baseName)
Definition at line 115 of file DiskStorageManager.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, returnDiskStorageManager(), Tools::PropertySet::setProperty(), and Tools::VT_PCHAR.
returnCustomStorageManager()
IStorageManager * SpatialIndex::StorageManager::returnCustomStorageManager (Tools::PropertySet & in)
Definition at line 35 of file CustomStorage.cc.
Referenced by Index::Index().
returnDiskStorageManager()
SpatialIndex::IStorageManager * SpatialIndex::StorageManager::returnDiskStorageManager (Tools::PropertySet & in)
Definition at line 84 of file DiskStorageManager.cc.
Referenced by createNewDiskStorageManager(), Index::Index(), and loadDiskStorageManager().
returnMemoryStorageManager()
SpatialIndex::IStorageManager * SpatialIndex::StorageManager::returnMemoryStorageManager (Tools::PropertySet & in)
Definition at line 37 of file MemoryStorageManager.cc.
Referenced by createNewMemoryStorageManager(), and Index::Index().
returnRandomEvictionsBuffer()
IBuffer * SpatialIndex::StorageManager::returnRandomEvictionsBuffer (IStorageManager & ind, Tools::PropertySet & in)
Definition at line 41 of file RandomEvictionsBuffer.cc.
Referenced by createNewRandomEvictionsBuffer(), and Index::Index().