libspatialindex API Reference: SpatialIndex::TPRTree Namespace Reference
SpatialIndex::TPRTree Namespace Reference
Classes
class Data
class Index
class Leaf
class Node
class Statistics
class TPRTree
Typedefs
typedef Tools::PoolPointer< Node > NodePtr
Enumerations
enum TPRTreeVariant { TPRV_RSTAR = 0x2 }
enum PersistenObjectIdentifier { PersistentIndex = 0x1, PersistentLeaf = 0x2 }
enum RangeQueryType { ContainmentQuery = 0x1, IntersectionQuery = 0x2 }
Functions
SIDX_DLL ISpatialIndex * returnTPRTree (IStorageManager &ind, Tools::PropertySet &in)
SIDX_DLL ISpatialIndex * createNewTPRTree (IStorageManager &sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, TPRTreeVariant rv, double horizon, id_type &indexIdentifier)
SIDX_DLL ISpatialIndex * loadTPRTree (IStorageManager &in, id_type indexIdentifier)
std::ostream & operator<< (std::ostream &os, const Statistics &s)
std::ostream & operator<< (std::ostream &os, const TPRTree &t)
Typedef Documentation
NodePtr
typedef Tools::PoolPointer<Node> SpatialIndex::TPRTree::NodePtr
Definition at line 39 of file tprtree/Node.h.
Enumeration Type Documentation
PersistenObjectIdentifier
enum SpatialIndex::TPRTree::PersistenObjectIdentifier
Enumerator
PersistentIndex
PersistentLeaf
Definition at line 40 of file include/spatialindex/TPRTree.h.
RangeQueryType
enum SpatialIndex::TPRTree::RangeQueryType
Enumerator
ContainmentQuery
IntersectionQuery
Definition at line 46 of file include/spatialindex/TPRTree.h.
TPRTreeVariant
enum SpatialIndex::TPRTree::TPRTreeVariant
Enumerator
TPRV_RSTAR
Definition at line 35 of file include/spatialindex/TPRTree.h.
Function Documentation
createNewTPRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::TPRTree::createNewTPRTree (SpatialIndex::IStorageManager & sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, TPRTreeVariant rv, double horizon, id_type & indexIdentifier)
Definition at line 146 of file TPRTree.cc.
References Tools::Variant::dblVal, Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnTPRTree(), Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
loadTPRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::TPRTree::loadTPRTree (IStorageManager & in, id_type indexIdentifier)
Definition at line 192 of file TPRTree.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnTPRTree(), Tools::PropertySet::setProperty(), and Tools::VT_LONGLONG.
operator<<() [1/2]
std::ostream & SpatialIndex::TPRTree::operator<< (std::ostream & os, const Statistics & s)
Definition at line 157 of file tprtree/Statistics.cc.
operator<<() [2/2]
std::ostream & SpatialIndex::TPRTree::operator<< (std::ostream & os, const TPRTree & t)
Definition at line 1247 of file TPRTree.cc.
References SpatialIndex::TPRTree::Statistics::getNumberOfData(), SpatialIndex::TPRTree::Statistics::getNumberOfNodesInLevel(), Tools::PointerPool< X >::m_hits, Tools::PointerPool< X >::m_misses, and TPRV_RSTAR.
returnTPRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::TPRTree::returnTPRTree (SpatialIndex::IStorageManager & sm, Tools::PropertySet & in)
Definition at line 140 of file TPRTree.cc.
Referenced by createNewTPRTree(), and loadTPRTree().