libspatialindex API Reference: sidx_api.cc File Reference
sidx_api.cc File Reference
#include <cmath>
#include <limits>
#include <cassert>
#include <cstring>
#include <spatialindex/capi/sidx_api.h>
#include <spatialindex/capi/sidx_impl.h>
Macros
#define VALIDATE_POINTER0(ptr, func)
#define VALIDATE_POINTER1(ptr, func, rc)
Functions
IDX_C_START SIDX_C_DLL void Error_Reset (void)
SIDX_C_DLL void Error_Pop (void)
SIDX_C_DLL int Error_GetLastErrorNum (void)
SIDX_C_DLL char * Error_GetLastErrorMsg (void)
SIDX_C_DLL char * Error_GetLastErrorMethod (void)
SIDX_C_DLL void Error_PushError (int code, const char *message, const char *method)
SIDX_C_DLL int Error_GetErrorCount (void)
SIDX_C_DLL IndexH Index_Create (IndexPropertyH hProp)
SIDX_C_DLL IndexH Index_CreateWithStream (IndexPropertyH hProp, int(*readNext)(SpatialIndex::id_type *id, double **pMin, double **pMax, uint32_t *nDimension, const uint8_t **pData, size_t *nDataLength))
SIDX_C_DLL void Index_Destroy (IndexH index)
SIDX_C_DLL void Index_Flush (IndexH index)
SIDX_C_DLL RTError Index_DeleteTPData (IndexH index, int64_t id, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension)
SIDX_C_DLL RTError Index_DeleteMVRData (IndexH index, int64_t id, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension)
SIDX_C_DLL RTError Index_DeleteData (IndexH index, int64_t id, double *pdMin, double *pdMax, uint32_t nDimension)
SIDX_C_DLL RTError Index_InsertTPData (IndexH index, int64_t id, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, const uint8_t *pData, size_t nDataLength)
SIDX_C_DLL RTError Index_InsertMVRData (IndexH index, int64_t id, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, const uint8_t *pData, size_t nDataLength)
SIDX_C_DLL RTError Index_InsertData (IndexH index, int64_t id, double *pdMin, double *pdMax, uint32_t nDimension, const uint8_t *pData, size_t nDataLength)
SIDX_C_DLL RTError Index_TPIntersects_obj (IndexH index, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_MVRIntersects_obj (IndexH index, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_Intersects_obj (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_TPIntersects_id (IndexH index, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_MVRIntersects_id (IndexH index, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_Intersects_id (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_TPIntersects_count (IndexH index, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, uint64_t *nResults)
SIDX_C_DLL RTError Index_MVRIntersects_count (IndexH index, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, uint64_t *nResults)
SIDX_C_DLL RTError Index_Intersects_count (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, uint64_t *nResults)
SIDX_C_DLL RTError Index_SegmentIntersects_obj (IndexH index, double *pdStartPoint, double *pdEndPoint, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_SegmentIntersects_id (IndexH index, double *pdStartPoint, double *pdEndPoint, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_SegmentIntersects_count (IndexH index, double *pdStartPoint, double *pdEndPoint, uint32_t nDimension, uint64_t *nResults)
SIDX_C_DLL RTError Index_TPNearestNeighbors_id (IndexH index, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_MVRNearestNeighbors_id (IndexH index, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_NearestNeighbors_id (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, int64_t **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_TPNearestNeighbors_obj (IndexH index, double *pdMin, double *pdMax, double *pdVMin, double *pdVMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_MVRNearestNeighbors_obj (IndexH index, double *pdMin, double *pdMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_NearestNeighbors_obj (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, IndexItemH **items, uint64_t *nResults)
SIDX_C_DLL RTError Index_Intersects_internal (IndexH index, double *pdMin, double *pdMax, uint32_t nDimension, IndexItemH **ids, uint64_t *nResults)
SIDX_C_DLL RTError Index_GetBounds (IndexH index, double **ppdMin, double **ppdMax, uint32_t *nDimension)
SIDX_DLL RTError Index_SetResultSetOffset (IndexH index, int64_t value)
SIDX_DLL int64_t Index_GetResultSetOffset (IndexH index)
SIDX_DLL RTError Index_SetResultSetLimit (IndexH index, int64_t value)
SIDX_DLL int64_t Index_GetResultSetLimit (IndexH index)
SIDX_C_DLL uint32_t Index_IsValid (IndexH index)
SIDX_C_DLL IndexPropertyH Index_GetProperties (IndexH index)
SIDX_C_DLL void Index_ClearBuffer (IndexH index)
SIDX_C_DLL void Index_DestroyObjResults (IndexItemH *results, uint32_t nResults)
SIDX_C_DLL void Index_Free (void *results)
SIDX_C_DLL RTError Index_GetLeaves (IndexH index, uint32_t *nNumLeafNodes, uint32_t **nLeafSizes, int64_t **nLeafIDs, int64_t ***nLeafChildIDs, double ***pppdMin, double ***pppdMax, uint32_t *nDimension)
SIDX_C_DLL void IndexItem_Destroy (IndexItemH item)
SIDX_C_DLL RTError IndexItem_GetData (IndexItemH item, uint8_t **data, uint64_t *length)
SIDX_C_DLL int64_t IndexItem_GetID (IndexItemH item)
SIDX_C_DLL RTError IndexItem_GetBounds (IndexItemH item, double **ppdMin, double **ppdMax, uint32_t *nDimension)
SIDX_C_DLL IndexPropertyH IndexProperty_Create ()
SIDX_C_DLL void IndexProperty_Destroy (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexType (IndexPropertyH hProp, RTIndexType value)
SIDX_C_DLL RTIndexType IndexProperty_GetIndexType (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetDimension (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetDimension (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexVariant (IndexPropertyH hProp, RTIndexVariant value)
SIDX_C_DLL RTIndexVariant IndexProperty_GetIndexVariant (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexStorage (IndexPropertyH hProp, RTStorageType value)
SIDX_C_DLL RTStorageType IndexProperty_GetIndexStorage (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetIndexCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetLeafCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetLeafCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetPagesize (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetPagesize (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetLeafPoolCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetLeafPoolCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexPoolCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetIndexPoolCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetRegionPoolCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetRegionPoolCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetPointPoolCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetPointPoolCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetNearMinimumOverlapFactor (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetNearMinimumOverlapFactor (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetBufferingCapacity (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetBufferingCapacity (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetEnsureTightMBRs (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetEnsureTightMBRs (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetWriteThrough (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetWriteThrough (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetOverwrite (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetOverwrite (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetFillFactor (IndexPropertyH hProp, double value)
SIDX_C_DLL double IndexProperty_GetFillFactor (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetSplitDistributionFactor (IndexPropertyH hProp, double value)
SIDX_C_DLL double IndexProperty_GetSplitDistributionFactor (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetTPRHorizon (IndexPropertyH hProp, double value)
SIDX_C_DLL double IndexProperty_GetTPRHorizon (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetReinsertFactor (IndexPropertyH hProp, double value)
SIDX_C_DLL double IndexProperty_GetReinsertFactor (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetFileName (IndexPropertyH hProp, const char *value)
SIDX_C_DLL char * IndexProperty_GetFileName (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetFileNameExtensionDat (IndexPropertyH hProp, const char *value)
SIDX_C_DLL char * IndexProperty_GetFileNameExtensionDat (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetFileNameExtensionIdx (IndexPropertyH hProp, const char *value)
SIDX_C_DLL char * IndexProperty_GetFileNameExtensionIdx (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetCustomStorageCallbacksSize (IndexPropertyH hProp, uint32_t value)
SIDX_C_DLL uint32_t IndexProperty_GetCustomStorageCallbacksSize (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetCustomStorageCallbacks (IndexPropertyH hProp, const void *value)
SIDX_C_DLL void * IndexProperty_GetCustomStorageCallbacks (IndexPropertyH hProp)
SIDX_C_DLL RTError IndexProperty_SetIndexID (IndexPropertyH hProp, int64_t value)
SIDX_C_DLL int64_t IndexProperty_GetIndexID (IndexPropertyH hProp)
SIDX_C_DLL void * SIDX_NewBuffer (size_t length)
SIDX_DLL RTError IndexProperty_SetResultSetLimit (IndexPropertyH hProp, uint64_t value)
SIDX_DLL uint64_t IndexProperty_GetResultSetLimit (IndexPropertyH hProp)
SIDX_C_DLL void SIDX_DeleteBuffer (void *buffer)
SIDX_C_DLL char * SIDX_Version ()
Variables
static std::stack< Error > errors
Macro Definition Documentation
VALIDATE_POINTER0
#define VALIDATE_POINTER0 (ptr, func)
Value:
do { if(NULL == ptr) { \
        RTError const ret = RT_Failure; \
        std::ostringstream msg; \
        msg << "Pointer \'" << #ptr << "\' is NULL in \'" << (func) <<"\'."; \
        std::string message(msg.str()); \
        Error_PushError( ret, message.c_str(), (func)); \
        return; \
   }} while(0)
Definition at line 60 of file sidx_api.cc.
Referenced by Index_ClearBuffer(), Index_Destroy(), Index_DestroyObjResults(), Index_Flush(), Index_Free(), IndexItem_Destroy(), and IndexProperty_Destroy().
VALIDATE_POINTER1
#define VALIDATE_POINTER1 (ptr, func, rc)
Value:
do { if(NULL == ptr) { \
        RTError const ret = RT_Failure; \
        std::ostringstream msg; \
        msg << "Pointer \'" << #ptr << "\' is NULL in \'" << (func) <<"\'."; \
        std::string message(msg.str()); \
        Error_PushError( ret, message.c_str(), (func)); \
        return (rc); \
   }} while(0)
Definition at line 70 of file sidx_api.cc.
Referenced by Index_Create(), Index_CreateWithStream(), Index_DeleteData(), Index_DeleteMVRData(), Index_DeleteTPData(), Index_GetBounds(), Index_GetLeaves(), Index_GetProperties(), Index_GetResultSetLimit(), Index_GetResultSetOffset(), Index_InsertData(), Index_InsertMVRData(), Index_InsertTPData(), Index_Intersects_count(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_IsValid(), Index_MVRIntersects_count(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_count(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_SetResultSetLimit(), Index_SetResultSetOffset(), Index_TPIntersects_count(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), Index_TPNearestNeighbors_obj(), IndexItem_GetBounds(), IndexItem_GetData(), IndexItem_GetID(), IndexProperty_GetBufferingCapacity(), IndexProperty_GetCustomStorageCallbacks(), IndexProperty_GetCustomStorageCallbacksSize(), IndexProperty_GetDimension(), IndexProperty_GetEnsureTightMBRs(), IndexProperty_GetFileName(), IndexProperty_GetFileNameExtensionDat(), IndexProperty_GetFileNameExtensionIdx(), IndexProperty_GetFillFactor(), IndexProperty_GetIndexCapacity(), IndexProperty_GetIndexID(), IndexProperty_GetIndexPoolCapacity(), IndexProperty_GetIndexStorage(), IndexProperty_GetIndexType(), IndexProperty_GetIndexVariant(), IndexProperty_GetLeafCapacity(), IndexProperty_GetLeafPoolCapacity(), IndexProperty_GetNearMinimumOverlapFactor(), IndexProperty_GetOverwrite(), IndexProperty_GetPagesize(), IndexProperty_GetPointPoolCapacity(), IndexProperty_GetRegionPoolCapacity(), IndexProperty_GetReinsertFactor(), IndexProperty_GetResultSetLimit(), IndexProperty_GetSplitDistributionFactor(), IndexProperty_GetTPRHorizon(), IndexProperty_GetWriteThrough(), IndexProperty_SetBufferingCapacity(), IndexProperty_SetCustomStorageCallbacks(), IndexProperty_SetCustomStorageCallbacksSize(), IndexProperty_SetDimension(), IndexProperty_SetEnsureTightMBRs(), IndexProperty_SetFileName(), IndexProperty_SetFileNameExtensionDat(), IndexProperty_SetFileNameExtensionIdx(), IndexProperty_SetFillFactor(), IndexProperty_SetIndexCapacity(), IndexProperty_SetIndexID(), IndexProperty_SetIndexPoolCapacity(), IndexProperty_SetIndexStorage(), IndexProperty_SetIndexType(), IndexProperty_SetIndexVariant(), IndexProperty_SetLeafCapacity(), IndexProperty_SetLeafPoolCapacity(), IndexProperty_SetNearMinimumOverlapFactor(), IndexProperty_SetOverwrite(), IndexProperty_SetPagesize(), IndexProperty_SetPointPoolCapacity(), IndexProperty_SetRegionPoolCapacity(), IndexProperty_SetReinsertFactor(), IndexProperty_SetResultSetLimit(), IndexProperty_SetSplitDistributionFactor(), IndexProperty_SetTPRHorizon(), and IndexProperty_SetWriteThrough().
Function Documentation
Error_GetErrorCount()
SIDX_C_DLL int Error_GetErrorCount (void)
Definition at line 161 of file sidx_api.cc.
References errors.
Error_GetLastErrorMethod()
SIDX_C_DLL char* Error_GetLastErrorMethod (void)
Definition at line 130 of file sidx_api.cc.
References errors, Error::GetMethod(), and STRDUP.
Error_GetLastErrorMsg()
SIDX_C_DLL char* Error_GetLastErrorMsg (void)
Definition at line 113 of file sidx_api.cc.
References errors, Error::GetMessage(), and STRDUP.
Error_GetLastErrorNum()
SIDX_C_DLL int Error_GetLastErrorNum (void)
Definition at line 100 of file sidx_api.cc.
References errors, and Error::GetCode().
Error_Pop()
SIDX_C_DLL void Error_Pop (void)
Definition at line 91 of file sidx_api.cc.
References errors.
Error_PushError()
SIDX_C_DLL void Error_PushError (int code, const char * message, const char * method)
Definition at line 147 of file sidx_api.cc.
References errors.
Referenced by Index_Create(), Index_CreateWithStream(), Index_DeleteData(), Index_DeleteMVRData(), Index_DeleteTPData(), Index_GetBounds(), Index_GetLeaves(), Index_InsertData(), Index_InsertMVRData(), Index_InsertTPData(), Index_Intersects_count(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_MVRIntersects_count(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_count(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_SetResultSetLimit(), Index_SetResultSetOffset(), Index_TPIntersects_count(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), Index_TPNearestNeighbors_obj(), IndexItem_GetBounds(), IndexProperty_GetBufferingCapacity(), IndexProperty_GetCustomStorageCallbacks(), IndexProperty_GetCustomStorageCallbacksSize(), IndexProperty_GetDimension(), IndexProperty_GetEnsureTightMBRs(), IndexProperty_GetFileName(), IndexProperty_GetFileNameExtensionDat(), IndexProperty_GetFileNameExtensionIdx(), IndexProperty_GetFillFactor(), IndexProperty_GetIndexCapacity(), IndexProperty_GetIndexID(), IndexProperty_GetIndexPoolCapacity(), IndexProperty_GetIndexStorage(), IndexProperty_GetIndexType(), IndexProperty_GetIndexVariant(), IndexProperty_GetLeafCapacity(), IndexProperty_GetLeafPoolCapacity(), IndexProperty_GetNearMinimumOverlapFactor(), IndexProperty_GetOverwrite(), IndexProperty_GetPagesize(), IndexProperty_GetPointPoolCapacity(), IndexProperty_GetRegionPoolCapacity(), IndexProperty_GetReinsertFactor(), IndexProperty_GetResultSetLimit(), IndexProperty_GetSplitDistributionFactor(), IndexProperty_GetTPRHorizon(), IndexProperty_GetWriteThrough(), IndexProperty_SetBufferingCapacity(), IndexProperty_SetCustomStorageCallbacks(), IndexProperty_SetCustomStorageCallbacksSize(), IndexProperty_SetDimension(), IndexProperty_SetEnsureTightMBRs(), IndexProperty_SetFileName(), IndexProperty_SetFileNameExtensionDat(), IndexProperty_SetFileNameExtensionIdx(), IndexProperty_SetFillFactor(), IndexProperty_SetIndexCapacity(), IndexProperty_SetIndexID(), IndexProperty_SetIndexPoolCapacity(), IndexProperty_SetIndexStorage(), IndexProperty_SetIndexType(), IndexProperty_SetIndexVariant(), IndexProperty_SetLeafCapacity(), IndexProperty_SetLeafPoolCapacity(), IndexProperty_SetNearMinimumOverlapFactor(), IndexProperty_SetOverwrite(), IndexProperty_SetPagesize(), IndexProperty_SetPointPoolCapacity(), IndexProperty_SetRegionPoolCapacity(), IndexProperty_SetReinsertFactor(), IndexProperty_SetResultSetLimit(), IndexProperty_SetSplitDistributionFactor(), IndexProperty_SetTPRHorizon(), and IndexProperty_SetWriteThrough().
Error_Reset()
IDX_C_START SIDX_C_DLL void Error_Reset (void)
Definition at line 82 of file sidx_api.cc.
References errors.
Index_ClearBuffer()
SIDX_C_DLL void Index_ClearBuffer (IndexH index)
Definition at line 1714 of file sidx_api.cc.
References Index::buffer(), SpatialIndex::StorageManager::IBuffer::clear(), and VALIDATE_POINTER0.
Index_Create()
SIDX_C_DLL IndexH Index_Create (IndexPropertyH hProp)
Definition at line 169 of file sidx_api.cc.
References Error_PushError(), RT_Failure, VALIDATE_POINTER1, and Tools::Exception::what().
Index_CreateWithStream()
SIDX_C_DLL IndexH Index_CreateWithStream (IndexPropertyH hProp, int(*)(SpatialIndex::id_type *id, double **pMin, double **pMax, uint32_t *nDimension, const uint8_t **pData, size_t *nDataLength) readNext)
Definition at line 197 of file sidx_api.cc.
References Error_PushError(), RT_Failure, VALIDATE_POINTER1, and Tools::Exception::what().
Index_DeleteData()
SIDX_C_DLL RTError Index_DeleteData (IndexH index, int64_t id, double * pdMin, double * pdMax, uint32_t nDimension)
Definition at line 318 of file sidx_api.cc.
References SpatialIndex::ISpatialIndex::deleteData(), Error_PushError(), Index::index(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_DeleteMVRData()
SIDX_C_DLL RTError Index_DeleteMVRData (IndexH index, int64_t id, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension)
Definition at line 282 of file sidx_api.cc.
References SpatialIndex::ISpatialIndex::deleteData(), Error_PushError(), Index::index(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_DeleteTPData()
SIDX_C_DLL RTError Index_DeleteTPData (IndexH index, int64_t id, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension)
Definition at line 244 of file sidx_api.cc.
References SpatialIndex::ISpatialIndex::deleteData(), Error_PushError(), Index::index(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_Destroy()
SIDX_C_DLL void Index_Destroy (IndexH index)
Definition at line 227 of file sidx_api.cc.
References VALIDATE_POINTER0.
Index_DestroyObjResults()
SIDX_C_DLL void Index_DestroyObjResults (IndexItemH * results, uint32_t nResults)
Definition at line 1721 of file sidx_api.cc.
References VALIDATE_POINTER0.
Index_Flush()
SIDX_C_DLL void Index_Flush (IndexH index)
Definition at line 234 of file sidx_api.cc.
References Index::flush(), and VALIDATE_POINTER0.
Index_Free()
SIDX_C_DLL void Index_Free (void * results)
Definition at line 1737 of file sidx_api.cc.
References VALIDATE_POINTER0.
Index_GetBounds()
SIDX_C_DLL RTError Index_GetBounds (IndexH index, double ** ppdMin, double ** ppdMax, uint32_t * nDimension)
Definition at line 1590 of file sidx_api.cc.
References Error_PushError(), BoundsQuery::GetBounds(), SpatialIndex::Region::getDimension(), SpatialIndex::Region::getHigh(), SpatialIndex::Region::getLow(), Index::index(), SpatialIndex::ISpatialIndex::queryStrategy(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_GetLeaves()
SIDX_C_DLL RTError Index_GetLeaves (IndexH index, uint32_t * nNumLeafNodes, uint32_t ** nLeafSizes, int64_t ** nLeafIDs, int64_t *** nLeafChildIDs, double *** pppdMin, double *** pppdMax, uint32_t * nDimension)
Definition at line 1744 of file sidx_api.cc.
References Error_PushError(), SpatialIndex::Region::getHigh(), SpatialIndex::ISpatialIndex::getIndexProperties(), SpatialIndex::Region::getLow(), Tools::PropertySet::getProperty(), LeafQuery::GetResults(), Index::index(), Tools::Variant::m_val, Tools::Variant::m_varType, SpatialIndex::ISpatialIndex::queryStrategy(), RT_Failure, RT_None, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, Tools::VT_ULONG, and Tools::Exception::what().
Index_GetProperties()
SIDX_C_DLL IndexPropertyH Index_GetProperties (IndexH index)
Definition at line 1701 of file sidx_api.cc.
References SpatialIndex::ISpatialIndex::getIndexProperties(), Index::GetProperties(), Tools::PropertySet::getProperty(), Index::index(), Tools::PropertySet, Tools::PropertySet::setProperty(), and VALIDATE_POINTER1.
Index_GetResultSetLimit()
SIDX_DLL int64_t Index_GetResultSetLimit (IndexH index)
Definition at line 1687 of file sidx_api.cc.
References Index::GetResultSetLimit(), and VALIDATE_POINTER1.
Index_GetResultSetOffset()
SIDX_DLL int64_t Index_GetResultSetOffset (IndexH index)
Definition at line 1663 of file sidx_api.cc.
References Index::GetResultSetOffset(), and VALIDATE_POINTER1.
Index_InsertData()
SIDX_C_DLL RTError Index_InsertData (IndexH index, int64_t id, double * pdMin, double * pdMax, uint32_t nDimension, const uint8_t * pData, size_t nDataLength)
Definition at line 496 of file sidx_api.cc.
References Error_PushError(), Index::index(), SpatialIndex::ISpatialIndex::insertData(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_InsertMVRData()
SIDX_C_DLL RTError Index_InsertMVRData (IndexH index, int64_t id, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, const uint8_t * pData, size_t nDataLength)
Definition at line 426 of file sidx_api.cc.
References Error_PushError(), Index::index(), SpatialIndex::ISpatialIndex::insertData(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_InsertTPData()
SIDX_C_DLL RTError Index_InsertTPData (IndexH index, int64_t id, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, const uint8_t * pData, size_t nDataLength)
Definition at line 351 of file sidx_api.cc.
References Error_PushError(), Index::index(), SpatialIndex::ISpatialIndex::insertData(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_Intersects_count()
SIDX_C_DLL RTError Index_Intersects_count (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, uint64_t * nResults)
Definition at line 992 of file sidx_api.cc.
References Error_PushError(), CountVisitor::GetResultCount(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_Intersects_id()
SIDX_C_DLL RTError Index_Intersects_id (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 837 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_Intersects_internal()
SIDX_C_DLL RTError Index_Intersects_internal (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, IndexItemH ** ids, uint64_t * nResults)
Definition at line 1540 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::internalNodesQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_Intersects_obj()
SIDX_C_DLL RTError Index_Intersects_obj (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 674 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_IsValid()
SIDX_C_DLL uint32_t Index_IsValid (IndexH index)
Definition at line 1694 of file sidx_api.cc.
References Index::index(), SpatialIndex::ISpatialIndex::isIndexValid(), and VALIDATE_POINTER1.
Index_MVRIntersects_count()
SIDX_C_DLL RTError Index_MVRIntersects_count (IndexH index, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, uint64_t * nResults)
Definition at line 942 of file sidx_api.cc.
References Error_PushError(), CountVisitor::GetResultCount(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_MVRIntersects_id()
SIDX_C_DLL RTError Index_MVRIntersects_id (IndexH index, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 782 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_MVRIntersects_obj()
SIDX_C_DLL RTError Index_MVRIntersects_obj (IndexH index, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 619 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_MVRNearestNeighbors_id()
SIDX_C_DLL RTError Index_MVRNearestNeighbors_id (IndexH index, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 1254 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_MVRNearestNeighbors_obj()
SIDX_C_DLL RTError Index_MVRNearestNeighbors_obj (IndexH index, double * pdMin, double * pdMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 1426 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_NearestNeighbors_id()
SIDX_C_DLL RTError Index_NearestNeighbors_id (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 1311 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_NearestNeighbors_obj()
SIDX_C_DLL RTError Index_NearestNeighbors_obj (IndexH index, double * pdMin, double * pdMax, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 1484 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_SegmentIntersects_count()
SIDX_C_DLL RTError Index_SegmentIntersects_count (IndexH index, double * pdStartPoint, double * pdEndPoint, uint32_t nDimension, uint64_t * nResults)
Definition at line 1147 of file sidx_api.cc.
References Error_PushError(), CountVisitor::GetResultCount(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_SegmentIntersects_id()
SIDX_C_DLL RTError Index_SegmentIntersects_id (IndexH index, double * pdStartPoint, double * pdEndPoint, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 1094 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_SegmentIntersects_obj()
SIDX_C_DLL RTError Index_SegmentIntersects_obj (IndexH index, double * pdStartPoint, double * pdEndPoint, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 1040 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_SetResultSetLimit()
SIDX_DLL RTError Index_SetResultSetLimit (IndexH index, int64_t value)
Definition at line 1670 of file sidx_api.cc.
References Error_PushError(), RT_Failure, RT_None, Index::SetResultSetLimit(), and VALIDATE_POINTER1.
Index_SetResultSetOffset()
SIDX_DLL RTError Index_SetResultSetOffset (IndexH index, int64_t value)
Definition at line 1646 of file sidx_api.cc.
References Error_PushError(), RT_Failure, RT_None, Index::SetResultSetOffset(), and VALIDATE_POINTER1.
Index_TPIntersects_count()
SIDX_C_DLL RTError Index_TPIntersects_count (IndexH index, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, uint64_t * nResults)
Definition at line 891 of file sidx_api.cc.
References Error_PushError(), CountVisitor::GetResultCount(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_TPIntersects_id()
SIDX_C_DLL RTError Index_TPIntersects_id (IndexH index, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 725 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_TPIntersects_obj()
SIDX_C_DLL RTError Index_TPIntersects_obj (IndexH index, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 562 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::intersectsWithQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_TPNearestNeighbors_id()
SIDX_C_DLL RTError Index_TPNearestNeighbors_id (IndexH index, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, int64_t ** ids, uint64_t * nResults)
Definition at line 1195 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Ids(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
Index_TPNearestNeighbors_obj()
SIDX_C_DLL RTError Index_TPNearestNeighbors_obj (IndexH index, double * pdMin, double * pdMax, double * pdVMin, double * pdVMax, double tStart, double tEnd, uint32_t nDimension, IndexItemH ** items, uint64_t * nResults)
Definition at line 1367 of file sidx_api.cc.
References Error_PushError(), Index::GetResultSetLimit(), Index::GetResultSetOffset(), Index::index(), SpatialIndex::ISpatialIndex::nearestNeighborQuery(), Page_ResultSet_Obj(), RT_Failure, RT_None, VALIDATE_POINTER1, and Tools::Exception::what().
IndexItem_Destroy()
SIDX_C_DLL void IndexItem_Destroy (IndexItemH item)
Definition at line 1844 of file sidx_api.cc.
References VALIDATE_POINTER0.
IndexItem_GetBounds()
SIDX_C_DLL RTError IndexItem_GetBounds (IndexItemH item, double ** ppdMin, double ** ppdMax, uint32_t * nDimension)
Definition at line 1879 of file sidx_api.cc.
References Error_PushError(), SpatialIndex::Region::getDimension(), SpatialIndex::Region::getHigh(), SpatialIndex::Region::getLow(), SpatialIndex::IShape::getMBR(), SpatialIndex::IEntry::getShape(), RT_Failure, RT_None, and VALIDATE_POINTER1.
IndexItem_GetData()
SIDX_C_DLL RTError IndexItem_GetData (IndexItemH item, uint8_t ** data, uint64_t * length)
Definition at line 1851 of file sidx_api.cc.
References SpatialIndex::IData::getData(), RT_Failure, RT_None, and VALIDATE_POINTER1.
IndexItem_GetID()
SIDX_C_DLL int64_t IndexItem_GetID (IndexItemH item)
Definition at line 1871 of file sidx_api.cc.
References SpatialIndex::IEntry::getIdentifier(), and VALIDATE_POINTER1.
IndexProperty_Create()
SIDX_C_DLL IndexPropertyH IndexProperty_Create ()
Definition at line 1921 of file sidx_api.cc.
References GetDefaults().
IndexProperty_Destroy()
SIDX_C_DLL void IndexProperty_Destroy (IndexPropertyH hProp)
Definition at line 1928 of file sidx_api.cc.
References VALIDATE_POINTER0.
IndexProperty_GetBufferingCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetBufferingCapacity (IndexPropertyH hProp)
Definition at line 2730 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetCustomStorageCallbacks()
SIDX_C_DLL void* IndexProperty_GetCustomStorageCallbacks (IndexPropertyH hProp)
Definition at line 3506 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pvVal, RT_Failure, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_PVOID.
IndexProperty_GetCustomStorageCallbacksSize()
SIDX_C_DLL uint32_t IndexProperty_GetCustomStorageCallbacksSize (IndexPropertyH hProp)
Definition at line 3424 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetDimension()
SIDX_C_DLL uint32_t IndexProperty_GetDimension (IndexPropertyH hProp)
Definition at line 2031 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetEnsureTightMBRs()
SIDX_C_DLL uint32_t IndexProperty_GetEnsureTightMBRs (IndexPropertyH hProp)
Definition at line 2796 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::VT_EMPTY.
IndexProperty_GetFileName()
SIDX_C_DLL char* IndexProperty_GetFileName (IndexPropertyH hProp)
Definition at line 3237 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, STRDUP, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_PCHAR.
IndexProperty_GetFileNameExtensionDat()
SIDX_C_DLL char* IndexProperty_GetFileNameExtensionDat (IndexPropertyH hProp)
Definition at line 3301 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, STRDUP, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_PCHAR.
IndexProperty_GetFileNameExtensionIdx()
SIDX_C_DLL char* IndexProperty_GetFileNameExtensionIdx (IndexPropertyH hProp)
Definition at line 3364 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, STRDUP, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_PCHAR.
IndexProperty_GetFillFactor()
SIDX_C_DLL double IndexProperty_GetFillFactor (IndexPropertyH hProp)
Definition at line 2989 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::VT_EMPTY.
IndexProperty_GetIndexCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetIndexCapacity (IndexPropertyH hProp)
Definition at line 2247 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetIndexID()
SIDX_C_DLL int64_t IndexProperty_GetIndexID (IndexPropertyH hProp)
Definition at line 3566 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_LONGLONG.
IndexProperty_GetIndexPoolCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetIndexPoolCapacity (IndexPropertyH hProp)
Definition at line 2487 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetIndexStorage()
SIDX_C_DLL RTStorageType IndexProperty_GetIndexStorage (IndexPropertyH hProp)
Definition at line 2183 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_InvalidStorageType, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetIndexType()
SIDX_C_DLL RTIndexType IndexProperty_GetIndexType (IndexPropertyH hProp)
Definition at line 1973 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_InvalidIndexType, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
Referenced by IndexProperty_SetIndexVariant().
IndexProperty_GetIndexVariant()
SIDX_C_DLL RTIndexVariant IndexProperty_GetIndexVariant (IndexPropertyH hProp)
Definition at line 2115 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_InvalidIndexVariant, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_LONG.
IndexProperty_GetLeafCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetLeafCapacity (IndexPropertyH hProp)
Definition at line 2307 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetLeafPoolCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetLeafPoolCapacity (IndexPropertyH hProp)
Definition at line 2427 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetNearMinimumOverlapFactor()
SIDX_C_DLL uint32_t IndexProperty_GetNearMinimumOverlapFactor (IndexPropertyH hProp)
Definition at line 2669 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetOverwrite()
SIDX_C_DLL uint32_t IndexProperty_GetOverwrite (IndexPropertyH hProp)
Definition at line 2928 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::VT_EMPTY.
IndexProperty_GetPagesize()
SIDX_C_DLL uint32_t IndexProperty_GetPagesize (IndexPropertyH hProp)
Definition at line 2367 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetPointPoolCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetPointPoolCapacity (IndexPropertyH hProp)
Definition at line 2607 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetRegionPoolCapacity()
SIDX_C_DLL uint32_t IndexProperty_GetRegionPoolCapacity (IndexPropertyH hProp)
Definition at line 2547 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_ULONG.
IndexProperty_GetReinsertFactor()
SIDX_C_DLL double IndexProperty_GetReinsertFactor (IndexPropertyH hProp)
Definition at line 3175 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::VT_EMPTY.
IndexProperty_GetResultSetLimit()
SIDX_DLL uint64_t IndexProperty_GetResultSetLimit (IndexPropertyH hProp)
Definition at line 3631 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_EMPTY, and Tools::VT_LONGLONG.
IndexProperty_GetSplitDistributionFactor()
SIDX_C_DLL double IndexProperty_GetSplitDistributionFactor (IndexPropertyH hProp)
Definition at line 3051 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::VT_EMPTY.
IndexProperty_GetTPRHorizon()
SIDX_C_DLL double IndexProperty_GetTPRHorizon (IndexPropertyH hProp)
Definition at line 3113 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::VT_EMPTY.
IndexProperty_GetWriteThrough()
SIDX_C_DLL uint32_t IndexProperty_GetWriteThrough (IndexPropertyH hProp)
Definition at line 2862 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::VT_EMPTY.
IndexProperty_SetBufferingCapacity()
SIDX_C_DLL RTError IndexProperty_SetBufferingCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2697 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetCustomStorageCallbacks()
SIDX_C_DLL RTError IndexProperty_SetCustomStorageCallbacks (IndexPropertyH hProp, const void * value)
Definition at line 3451 of file sidx_api.cc.
References Error_PushError(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pvVal, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_PVOID, and Tools::Exception::what().
IndexProperty_SetCustomStorageCallbacksSize()
SIDX_C_DLL RTError IndexProperty_SetCustomStorageCallbacksSize (IndexPropertyH hProp, uint32_t value)
Definition at line 3391 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetDimension()
SIDX_C_DLL RTError IndexProperty_SetDimension (IndexPropertyH hProp, uint32_t value)
Definition at line 1999 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetEnsureTightMBRs()
SIDX_C_DLL RTError IndexProperty_SetEnsureTightMBRs (IndexPropertyH hProp, uint32_t value)
Definition at line 2757 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::Exception::what().
IndexProperty_SetFileName()
SIDX_C_DLL RTError IndexProperty_SetFileName (IndexPropertyH hProp, const char * value)
Definition at line 3202 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, RT_None, Tools::PropertySet::setProperty(), STRDUP, VALIDATE_POINTER1, Tools::VT_PCHAR, and Tools::Exception::what().
IndexProperty_SetFileNameExtensionDat()
SIDX_C_DLL RTError IndexProperty_SetFileNameExtensionDat (IndexPropertyH hProp, const char * value)
Definition at line 3265 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, RT_None, Tools::PropertySet::setProperty(), STRDUP, VALIDATE_POINTER1, Tools::VT_PCHAR, and Tools::Exception::what().
IndexProperty_SetFileNameExtensionIdx()
SIDX_C_DLL RTError IndexProperty_SetFileNameExtensionIdx (IndexPropertyH hProp, const char * value)
Definition at line 3328 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, RT_Failure, RT_None, Tools::PropertySet::setProperty(), STRDUP, VALIDATE_POINTER1, Tools::VT_PCHAR, and Tools::Exception::what().
IndexProperty_SetFillFactor()
SIDX_C_DLL RTError IndexProperty_SetFillFactor (IndexPropertyH hProp, double value)
Definition at line 2956 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::Exception::what().
IndexProperty_SetIndexCapacity()
SIDX_C_DLL RTError IndexProperty_SetIndexCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2214 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetIndexID()
SIDX_C_DLL RTError IndexProperty_SetIndexID (IndexPropertyH hProp, int64_t value)
Definition at line 3533 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_LONGLONG, and Tools::Exception::what().
IndexProperty_SetIndexPoolCapacity()
SIDX_C_DLL RTError IndexProperty_SetIndexPoolCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2454 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetIndexStorage()
SIDX_C_DLL RTError IndexProperty_SetIndexStorage (IndexPropertyH hProp, RTStorageType value)
Definition at line 2147 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Custom, RT_Disk, RT_Failure, RT_Memory, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetIndexType()
SIDX_C_DLL RTError IndexProperty_SetIndexType (IndexPropertyH hProp, RTIndexType value)
Definition at line 1935 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_MVRTree, RT_None, RT_RTree, RT_TPRTree, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetIndexVariant()
SIDX_C_DLL RTError IndexProperty_SetIndexVariant (IndexPropertyH hProp, RTIndexVariant value)
Definition at line 2058 of file sidx_api.cc.
References Error_PushError(), IndexProperty_GetIndexType(), Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_InvalidIndexType, RT_Linear, RT_MVRTree, RT_None, RT_Quadratic, RT_RTree, RT_Star, RT_TPRTree, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_LONG, and Tools::Exception::what().
IndexProperty_SetLeafCapacity()
SIDX_C_DLL RTError IndexProperty_SetLeafCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2274 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetLeafPoolCapacity()
SIDX_C_DLL RTError IndexProperty_SetLeafPoolCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2394 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetNearMinimumOverlapFactor()
SIDX_C_DLL RTError IndexProperty_SetNearMinimumOverlapFactor (IndexPropertyH hProp, uint32_t value)
Definition at line 2634 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetOverwrite()
SIDX_C_DLL RTError IndexProperty_SetOverwrite (IndexPropertyH hProp, uint32_t value)
Definition at line 2889 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::Exception::what().
IndexProperty_SetPagesize()
SIDX_C_DLL RTError IndexProperty_SetPagesize (IndexPropertyH hProp, uint32_t value)
Definition at line 2334 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetPointPoolCapacity()
SIDX_C_DLL RTError IndexProperty_SetPointPoolCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2574 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetRegionPoolCapacity()
SIDX_C_DLL RTError IndexProperty_SetRegionPoolCapacity (IndexPropertyH hProp, uint32_t value)
Definition at line 2514 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, VALIDATE_POINTER1, Tools::VT_ULONG, and Tools::Exception::what().
IndexProperty_SetReinsertFactor()
SIDX_C_DLL RTError IndexProperty_SetReinsertFactor (IndexPropertyH hProp, double value)
Definition at line 3140 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::Exception::what().
IndexProperty_SetResultSetLimit()
SIDX_DLL RTError IndexProperty_SetResultSetLimit (IndexPropertyH hProp, uint64_t value)
Definition at line 3598 of file sidx_api.cc.
References Error_PushError(), Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_LONGLONG, and Tools::Exception::what().
IndexProperty_SetSplitDistributionFactor()
SIDX_C_DLL RTError IndexProperty_SetSplitDistributionFactor (IndexPropertyH hProp, double value)
Definition at line 3016 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::Exception::what().
IndexProperty_SetTPRHorizon()
SIDX_C_DLL RTError IndexProperty_SetTPRHorizon (IndexPropertyH hProp, double value)
Definition at line 3078 of file sidx_api.cc.
References Tools::Variant::dblVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_DOUBLE, and Tools::Exception::what().
IndexProperty_SetWriteThrough()
SIDX_C_DLL RTError IndexProperty_SetWriteThrough (IndexPropertyH hProp, uint32_t value)
Definition at line 2823 of file sidx_api.cc.
References Tools::Variant::blVal, Error_PushError(), Tools::Variant::m_val, Tools::Variant::m_varType, RT_Failure, RT_None, Tools::PropertySet::setProperty(), VALIDATE_POINTER1, Tools::VT_BOOL, and Tools::Exception::what().
SIDX_DeleteBuffer()
SIDX_C_DLL void SIDX_DeleteBuffer (void * buffer)
Definition at line 3659 of file sidx_api.cc.
SIDX_NewBuffer()
SIDX_C_DLL void* SIDX_NewBuffer (size_t length)
Definition at line 3593 of file sidx_api.cc.
SIDX_Version()
SIDX_C_DLL char* SIDX_Version ()
Definition at line 3665 of file sidx_api.cc.
References IDX_C_END, SIDX_RELEASE_NAME, and STRDUP.
Variable Documentation
errors
std::stack<Error> errors static
Definition at line 52 of file sidx_api.cc.
Referenced by Error_GetErrorCount(), Error_GetLastErrorMethod(), Error_GetLastErrorMsg(), Error_GetLastErrorNum(), Error_Pop(), Error_PushError(), and Error_Reset().