libspatialindex API Reference: SpatialIndex::StorageManager::CustomStorageManagerCallbacks Struct Reference
SpatialIndex::StorageManager::CustomStorageManagerCallbacks Struct Reference
#include <CustomStorage.h>
Public Member Functions
CustomStorageManagerCallbacks ()
Public Attributes
void * context
void(* createCallback)(const void *context, int *errorCode)
void(* destroyCallback)(const void *context, int *errorCode)
void(* flushCallback)(const void *context, int *errorCode)
void(* loadByteArrayCallback)(const void *context, const id_type page, uint32_t *len, byte **data, int *errorCode)
void(* storeByteArrayCallback)(const void *context, id_type *page, const uint32_t len, const byte *const data, int *errorCode)
void(* deleteByteArrayCallback)(const void *context, const id_type page, int *errorCode)
Detailed Description
Definition at line 37 of file CustomStorage.h.
Constructor & Destructor Documentation
CustomStorageManagerCallbacks()
SpatialIndex::StorageManager::CustomStorageManagerCallbacks::CustomStorageManagerCallbacks () inline
Definition at line 39 of file CustomStorage.h.
Member Data Documentation
context
void* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::context
Definition at line 48 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::CustomStorageManager(), SpatialIndex::StorageManager::CustomStorageManager::deleteByteArray(), SpatialIndex::StorageManager::CustomStorageManager::flush(), SpatialIndex::StorageManager::CustomStorageManager::loadByteArray(), SpatialIndex::StorageManager::CustomStorageManager::storeByteArray(), and SpatialIndex::StorageManager::CustomStorageManager::~CustomStorageManager().
createCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::createCallback) (const void *context, int *errorCode)
Definition at line 49 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::CustomStorageManager().
deleteByteArrayCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::deleteByteArrayCallback) (const void *context, const id_type page, int *errorCode)
Definition at line 54 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::deleteByteArray().
destroyCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::destroyCallback) (const void *context, int *errorCode)
Definition at line 50 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::~CustomStorageManager().
flushCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::flushCallback) (const void *context, int *errorCode)
Definition at line 51 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::flush().
loadByteArrayCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::loadByteArrayCallback) (const void *context, const id_type page, uint32_t *len, byte **data, int *errorCode)
Definition at line 52 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::loadByteArray().
storeByteArrayCallback
void(* SpatialIndex::StorageManager::CustomStorageManagerCallbacks::storeByteArrayCallback) (const void *context, id_type *page, const uint32_t len, const byte *const data, int *errorCode)
Definition at line 53 of file CustomStorage.h.
Referenced by SpatialIndex::StorageManager::CustomStorageManager::storeByteArray().
The documentation for this struct was generated from the following file:
CustomStorage.h