libspatialindex API Reference: Utility.cc File Reference
Utility.cc File Reference
#include <spatialindex/capi/sidx_impl.h>
Functions
Tools::PropertySet * GetDefaults ()
void Page_ResultSet_Ids (IdVisitor &visitor, int64_t **ids, int64_t nStart, int64_t nResultLimit, uint64_t *nResults)
void Page_ResultSet_Obj (ObjVisitor &visitor, IndexItemH **items, int64_t nStart, int64_t nResultLimit, uint64_t *nResults)
Function Documentation
GetDefaults()
Tools::PropertySet* GetDefaults ()
Definition at line 31 of file Utility.cc.
References Tools::Variant::bVal, Tools::Variant::dblVal, Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, Tools::PropertySet, RT_Disk, RT_RTree, SpatialIndex::RTree::RV_RSTAR, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, Tools::VT_PCHAR, Tools::VT_PVOID, and Tools::VT_ULONG.
Referenced by IndexProperty_Create().
Page_ResultSet_Ids()
void Page_ResultSet_Ids (IdVisitor & visitor, int64_t ** ids, int64_t nStart, int64_t nResultLimit, uint64_t * nResults)
Definition at line 157 of file Utility.cc.
References IdVisitor::GetResultCount(), and IdVisitor::GetResults().
Referenced by Index_Intersects_id(), Index_MVRIntersects_id(), Index_MVRNearestNeighbors_id(), Index_NearestNeighbors_id(), Index_SegmentIntersects_id(), Index_TPIntersects_id(), and Index_TPNearestNeighbors_id().
Page_ResultSet_Obj()
void Page_ResultSet_Obj (ObjVisitor & visitor, IndexItemH ** items, int64_t nStart, int64_t nResultLimit, uint64_t * nResults)
Definition at line 195 of file Utility.cc.
References Tools::IObject::clone(), ObjVisitor::GetResultCount(), and ObjVisitor::GetResults().
Referenced by Index_Intersects_internal(), Index_Intersects_obj(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_obj(), Index_TPIntersects_obj(), and Index_TPNearestNeighbors_obj().