libspatialindex API Reference: SpatialIndex::IVisitor Class Reference
SpatialIndex::IVisitor Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual void visitNode (const INode &in)=0
virtual void visitData (const IData &in)=0
virtual void visitData (std::vector< const IData *> &v)=0
virtual ~IVisitor ()=default
Detailed Description
Definition at line 165 of file SpatialIndex.h.
Constructor & Destructor Documentation
~IVisitor()
virtual SpatialIndex::IVisitor::~IVisitor () virtual default
Member Function Documentation
visitData() [1/2]
virtual void SpatialIndex::IVisitor::visitData (const IData & in) pure virtual
Implemented in IdVisitor, ObjVisitor, and CountVisitor.
Referenced by SpatialIndex::RTree::RTree::containsWhatQuery(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), CountVisitor::GetResultCount(), ObjVisitor::GetResults(), IdVisitor::GetResults(), SpatialIndex::RTree::RTree::internalNodesQuery(), and SpatialIndex::RTree::RTree::nearestNeighborQuery().
visitData() [2/2]
virtual void SpatialIndex::IVisitor::visitData (std::vector< const IData *> & v) pure virtual
Implemented in IdVisitor, ObjVisitor, and CountVisitor.
visitNode()
virtual void SpatialIndex::IVisitor::visitNode (const INode & in) pure virtual
Implemented in IdVisitor, ObjVisitor, and CountVisitor.
Referenced by SpatialIndex::RTree::RTree::containsWhatQuery(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), CountVisitor::GetResultCount(), ObjVisitor::GetResults(), IdVisitor::GetResults(), and SpatialIndex::RTree::RTree::nearestNeighborQuery().
The documentation for this class was generated from the following file:
SpatialIndex.h