libspatialindex API Reference: IdVisitor Class Reference
IdVisitor Class Reference
#include <IdVisitor.h>
Public Member Functions
IdVisitor ()
~IdVisitor ()
uint64_t GetResultCount () const
std::vector< uint64_t > & GetResults ()
void visitNode (const SpatialIndex::INode &n)
void visitData (const SpatialIndex::IData &d)
void visitData (std::vector< const SpatialIndex::IData *> &v)
Public Member Functions inherited from SpatialIndex::IVisitor
virtual ~IVisitor ()=default
Detailed Description
Definition at line 33 of file IdVisitor.h.
Constructor & Destructor Documentation
IdVisitor()
IdVisitor::IdVisitor ()
Definition at line 31 of file IdVisitor.cc.
~IdVisitor()
IdVisitor::~IdVisitor ()
Definition at line 35 of file IdVisitor.cc.
Member Function Documentation
GetResultCount()
uint64_t IdVisitor::GetResultCount () const inline
Definition at line 44 of file IdVisitor.h.
Referenced by SpatialIndex::RTree::RTree::internalNodesQuery(), and Page_ResultSet_Ids().
GetResults()
std::vector<uint64_t>& IdVisitor::GetResults () inline
Definition at line 45 of file IdVisitor.h.
References SpatialIndex::IVisitor::visitData(), and SpatialIndex::IVisitor::visitNode().
Referenced by SpatialIndex::RTree::RTree::internalNodesQuery(), and Page_ResultSet_Ids().
visitData() [1/2]
void IdVisitor::visitData (const SpatialIndex::IData & d) virtual
Implements SpatialIndex::IVisitor.
Definition at line 45 of file IdVisitor.cc.
References SpatialIndex::IEntry::getIdentifier().
visitData() [2/2]
void IdVisitor::visitData (std::vector< const SpatialIndex::IData *> & v) virtual
Implements SpatialIndex::IVisitor.
Definition at line 52 of file IdVisitor.cc.
visitNode()
void IdVisitor::visitNode (const SpatialIndex::INode & n) virtual
Implements SpatialIndex::IVisitor.
Definition at line 40 of file IdVisitor.cc.
The documentation for this class was generated from the following files:
IdVisitor.h
IdVisitor.cc