libspatialindex API Reference: Index Class Reference
Index Class Reference
#include <Index.h>
Public Member Functions
Index (const Tools::PropertySet &poProperties)
Index (const Tools::PropertySet &poProperties, int(*readNext)(SpatialIndex::id_type *id, double **pMin, double **pMax, uint32_t *nDimension, const uint8_t **pData, size_t *nDataLength))
~Index ()
const Tools::PropertySet GetProperties ()
bool insertFeature (uint64_t id, double *min, double *max)
RTIndexType GetIndexType ()
void SetIndexType (RTIndexType v)
RTStorageType GetIndexStorage ()
void SetIndexStorage (RTStorageType v)
RTIndexVariant GetIndexVariant ()
void SetIndexVariant (RTStorageType v)
int64_t GetResultSetOffset ()
void SetResultSetOffset (int64_t v)
int64_t GetResultSetLimit ()
void SetResultSetLimit (int64_t v)
void flush ()
SpatialIndex::ISpatialIndex & index ()
SpatialIndex::StorageManager::IBuffer & buffer ()
Detailed Description
Definition at line 33 of file include/spatialindex/capi/Index.h.
Constructor & Destructor Documentation
Index() [1/2]
Index::Index (const Tools::PropertySet & poProperties)
Definition at line 76 of file capi/Index.cc.
References Index().
Referenced by Index().
Index() [2/2]
Index::Index (const Tools::PropertySet & poProperties, int(*)(SpatialIndex::id_type *id, double **pMin, double **pMax, uint32_t *nDimension, const uint8_t **pData, size_t *nDataLength) readNext)
Definition at line 91 of file capi/Index.cc.
References SpatialIndex::RTree::BLM_STR, buffer(), SpatialIndex::RTree::createAndBulkLoadNewRTree(), Tools::Variant::dblVal, GetIndexStorage(), Index(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, SpatialIndex::StorageManager::returnCustomStorageManager(), SpatialIndex::StorageManager::returnDiskStorageManager(), SpatialIndex::StorageManager::returnMemoryStorageManager(), SpatialIndex::StorageManager::returnRandomEvictionsBuffer(), RT_Custom, RT_Disk, RT_Memory, SpatialIndex::RTree::RV_RSTAR, Tools::Variant::ulVal, Tools::VT_DOUBLE, Tools::VT_EMPTY, Tools::VT_LONG, Tools::VT_LONGLONG, Tools::VT_PCHAR, Tools::VT_ULONG, and Tools::Exception::what().
~Index()
Index::~Index ()
Definition at line 84 of file capi/Index.cc.
Member Function Documentation
buffer()
SpatialIndex::StorageManager::IBuffer& Index::buffer () inline
Definition at line 63 of file include/spatialindex/capi/Index.h.
Referenced by Index(), and Index_ClearBuffer().
flush()
void Index::flush ()
Definition at line 428 of file capi/Index.cc.
Referenced by Index_Flush().
GetIndexStorage()
RTStorageType Index::GetIndexStorage ()
Definition at line 314 of file capi/Index.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, RT_InvalidStorageType, Tools::Variant::ulVal, Tools::VT_EMPTY, and Tools::VT_ULONG.
Referenced by Index().
GetIndexType()
RTIndexType Index::GetIndexType ()
Definition at line 288 of file capi/Index.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, RT_InvalidIndexType, Tools::Variant::ulVal, Tools::VT_EMPTY, and Tools::VT_ULONG.
Referenced by SetIndexVariant().
GetIndexVariant()
RTIndexVariant Index::GetIndexVariant ()
Definition at line 341 of file capi/Index.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, RT_InvalidIndexVariant, Tools::Variant::ulVal, Tools::VT_EMPTY, and Tools::VT_ULONG.
GetProperties()
const Tools::PropertySet Index::GetProperties () inline
Definition at line 41 of file include/spatialindex/capi/Index.h.
Referenced by Index_GetProperties().
GetResultSetLimit()
int64_t Index::GetResultSetLimit ()
Definition at line 403 of file capi/Index.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::VT_EMPTY, and Tools::VT_LONGLONG.
Referenced by Index_Contains_id(), Index_Contains_obj(), Index_GetResultSetLimit(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), and Index_TPNearestNeighbors_obj().
GetResultSetOffset()
int64_t Index::GetResultSetOffset ()
Definition at line 377 of file capi/Index.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::VT_EMPTY, and Tools::VT_LONGLONG.
Referenced by Index_Contains_id(), Index_Contains_obj(), Index_GetResultSetOffset(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), and Index_TPNearestNeighbors_obj().
index()
SpatialIndex::ISpatialIndex& Index::index () inline
Definition at line 62 of file include/spatialindex/capi/Index.h.
Referenced by SpatialIndex::TPRTree::Node::getChildData(), SpatialIndex::MVRTree::Node::getChildData(), SpatialIndex::RTree::Node::getChildData(), SpatialIndex::TPRTree::Node::getChildIdentifier(), SpatialIndex::RTree::Node::getChildIdentifier(), SpatialIndex::MVRTree::Node::getChildIdentifier(), Index_Contains_count(), Index_Contains_id(), Index_Contains_obj(), Index_DeleteData(), Index_DeleteMVRData(), Index_DeleteTPData(), Index_GetBounds(), Index_GetLeaves(), Index_GetProperties(), Index_InsertData(), Index_InsertMVRData(), Index_InsertTPData(), Index_Intersects_count(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_IsValid(), Index_MVRIntersects_count(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_count(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_TPIntersects_count(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), Index_TPNearestNeighbors_obj(), SpatialIndex::TPRTree::Node::~Node(), SpatialIndex::RTree::Node::~Node(), and SpatialIndex::MVRTree::Node::~Node().
insertFeature()
bool Index::insertFeature (uint64_t id, double * min, double * max)
SetIndexStorage()
void Index::SetIndexStorage (RTStorageType v)
Definition at line 333 of file capi/Index.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::ulVal, and Tools::VT_ULONG.
SetIndexType()
void Index::SetIndexType (RTIndexType v)
Definition at line 306 of file capi/Index.cc.
References Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::ulVal, and Tools::VT_ULONG.
SetIndexVariant()
void Index::SetIndexVariant (RTStorageType v)
Definition at line 360 of file capi/Index.cc.
References GetIndexType(), Tools::Variant::m_val, RT_MVRTree, RT_RTree, RT_TPRTree, and Tools::Variant::ulVal.
SetResultSetLimit()
void Index::SetResultSetLimit (int64_t v)
Definition at line 420 of file capi/Index.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, and Tools::VT_LONGLONG.
Referenced by Index_SetResultSetLimit().
SetResultSetOffset()
void Index::SetResultSetOffset (int64_t v)
Definition at line 394 of file capi/Index.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, and Tools::VT_LONGLONG.
Referenced by Index_SetResultSetOffset().
The documentation for this class was generated from the following files:
include/spatialindex/capi/Index.h
capi/Index.cc