libspatialindex API Reference: SpatialIndex::TPRTree::Node Class Reference
SpatialIndex::TPRTree::Node Class Reference abstract
#include <Node.h>
Public Member Functions
~Node () override
Tools::IObject * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const uint8_t *data) override
void storeToByteArray (uint8_t **data, uint32_t &len) override
id_type getIdentifier () const override
void getShape (IShape **out) const override
uint32_t getChildrenCount () const override
id_type getChildIdentifier (uint32_t index) const override
void getChildShape (uint32_t index, IShape **out) const override
void getChildData (uint32_t index, uint32_t &length, uint8_t **data) const override
uint32_t getLevel () const override
bool isIndex () const override
bool isLeaf () const override
Public Member Functions inherited from SpatialIndex::INode
~INode () override=default
Public Member Functions inherited from SpatialIndex::IEntry
~IEntry () override=default
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Friends
class TPRTree
class Leaf
class Index
class Tools::PointerPool< Node >
Detailed Description
Definition at line 43 of file tprtree/Node.h.
Constructor & Destructor Documentation
~Node()
Node::~Node () override
Definition at line 297 of file tprtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::MovingRegion::combineRegionAfterTime(), SpatialIndex::MovingRegion::containsRegionAfterTime(), Tools::PoolPointer< X >::get(), SpatialIndex::MovingRegion::getAreaInTime(), SpatialIndex::MovingRegion::getCenterDistanceInTime(), SpatialIndex::MovingRegion::getExtrapolatedHigh(), SpatialIndex::MovingRegion::getExtrapolatedLow(), SpatialIndex::MovingRegion::getIntersectingAreaInTime(), SpatialIndex::MovingRegion::getProjectedSurfaceAreaInTime(), Index::index(), Index, SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::TPRTree::TPRV_RSTAR.
Member Function Documentation
clone()
Tools::IObject * Node::clone () override virtual
Implements Tools::IObject.
Definition at line 44 of file tprtree/Node.cc.
getByteArraySize()
uint32_t Node::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 52 of file tprtree/Node.cc.
Referenced by storeToByteArray().
getChildData()
void Node::getChildData (uint32_t index, uint32_t & length, uint8_t ** data) const override virtual
Implements SpatialIndex::INode.
Definition at line 229 of file tprtree/Node.cc.
References Index::index().
getChildIdentifier()
SpatialIndex::id_type Node::getChildIdentifier (uint32_t index) const override virtual
Implements SpatialIndex::INode.
Definition at line 215 of file tprtree/Node.cc.
References Index::index().
getChildrenCount()
uint32_t Node::getChildrenCount () const override virtual
Implements SpatialIndex::INode.
Definition at line 210 of file tprtree/Node.cc.
getChildShape()
void Node::getChildShape (uint32_t index, IShape ** out) const override virtual
Implements SpatialIndex::INode.
Definition at line 222 of file tprtree/Node.cc.
getIdentifier()
SpatialIndex::id_type Node::getIdentifier () const override virtual
Implements SpatialIndex::IEntry.
Definition at line 197 of file tprtree/Node.cc.
getLevel()
uint32_t Node::getLevel () const override virtual
Implements SpatialIndex::INode.
Definition at line 244 of file tprtree/Node.cc.
getShape()
void Node::getShape (IShape ** out) const override virtual
Implements SpatialIndex::IEntry.
Definition at line 202 of file tprtree/Node.cc.
isIndex()
bool Node::isIndex () const override virtual
Implements SpatialIndex::INode.
Definition at line 254 of file tprtree/Node.cc.
References SpatialIndex::MovingRegion::makeInfinite().
isLeaf()
bool Node::isLeaf () const override virtual
Implements SpatialIndex::INode.
Definition at line 249 of file tprtree/Node.cc.
loadFromByteArray()
void Node::loadFromByteArray (const uint8_t * data) override virtual
Implements Tools::ISerializable.
Definition at line 64 of file tprtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::MovingRegion::makeDimension().
Referenced by SpatialIndex::TPRTree::TPRTree::flush().
storeToByteArray()
void Node::storeToByteArray (uint8_t ** data, uint32_t & len) override virtual
Implements Tools::ISerializable.
Definition at line 131 of file tprtree/Node.cc.
References getByteArraySize(), SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, SpatialIndex::TimeRegion::m_startTime, SpatialIndex::TPRTree::PersistentIndex, and SpatialIndex::TPRTree::PersistentLeaf.
Referenced by SpatialIndex::TPRTree::TPRTree::flush().
Friends And Related Function Documentation
Index
friend class Index friend
Definition at line 204 of file tprtree/Node.h.
Referenced by ~Node().
Leaf
friend class Leaf friend
Definition at line 203 of file tprtree/Node.h.
Tools::PointerPool< Node >
friend class Tools::PointerPool< Node > friend
Definition at line 205 of file tprtree/Node.h.
TPRTree
friend class TPRTree friend
Definition at line 202 of file tprtree/Node.h.
The documentation for this class was generated from the following files:
tprtree/Node.h
tprtree/Node.cc