libspatialindex API Reference: SpatialIndex::MovingRegion Class Reference
SpatialIndex::MovingRegion Class Reference
#include <MovingRegion.h>
Classes
class CrossPoint
Public Member Functions
MovingRegion ()
MovingRegion (const double *pLow, const double *pHigh, const double *pVLow, const double *pVHigh, const Tools::IInterval &ti, uint32_t dimension)
MovingRegion (const double *pLow, const double *pHigh, const double *pVLow, const double *pVHigh, double tStart, double tEnd, uint32_t dimension)
MovingRegion (const Point &low, const Point &high, const Point &vlow, const Point &vhigh, const Tools::IInterval &ti)
MovingRegion (const Point &low, const Point &high, const Point &vlow, const Point &vhigh, double tStart, double tEnd)
MovingRegion (const Region &mbr, const Region &vbr, const Tools::IInterval &ivI)
MovingRegion (const Region &mbr, const Region &vbr, double tStart, double tEnd)
MovingRegion (const MovingPoint &low, const MovingPoint &high)
MovingRegion (const MovingRegion &in)
~MovingRegion () override
virtual MovingRegion & operator= (const MovingRegion &r)
virtual bool operator== (const MovingRegion &) const
bool isShrinking () const
virtual double getLow (uint32_t index, double t) const
virtual double getHigh (uint32_t index, double t) const
virtual double getExtrapolatedLow (uint32_t index, double t) const
virtual double getExtrapolatedHigh (uint32_t index, double t) const
virtual double getVLow (uint32_t index) const
virtual double getVHigh (uint32_t index) const
virtual bool intersectsRegionInTime (const MovingRegion &r) const
virtual bool intersectsRegionInTime (const MovingRegion &r, Tools::IInterval &out) const
virtual bool intersectsRegionInTime (const Tools::IInterval &ivI, const MovingRegion &r, Tools::IInterval &ret) const
virtual bool containsRegionInTime (const MovingRegion &r) const
virtual bool containsRegionInTime (const Tools::IInterval &ivI, const MovingRegion &r) const
virtual bool containsRegionAfterTime (double t, const MovingRegion &r) const
virtual double getProjectedSurfaceAreaInTime () const
virtual double getProjectedSurfaceAreaInTime (const Tools::IInterval &ivI) const
virtual double getCenterDistanceInTime (const MovingRegion &r) const
virtual double getCenterDistanceInTime (const Tools::IInterval &ivI, const MovingRegion &r) const
virtual bool intersectsRegionAtTime (double t, const MovingRegion &r) const
virtual bool containsRegionAtTime (double t, const MovingRegion &r) const
virtual bool intersectsPointInTime (const MovingPoint &p) const
virtual bool intersectsPointInTime (const MovingPoint &p, Tools::IInterval &out) const
virtual bool intersectsPointInTime (const Tools::IInterval &ivI, const MovingPoint &p, Tools::IInterval &out) const
virtual bool containsPointInTime (const MovingPoint &p) const
virtual bool containsPointInTime (const Tools::IInterval &ivI, const MovingPoint &p) const
virtual void combineRegionInTime (const MovingRegion &r)
virtual void combineRegionAfterTime (double t, const MovingRegion &r)
virtual void getCombinedRegionInTime (MovingRegion &out, const MovingRegion &in) const
virtual void getCombinedRegionAfterTime (double t, MovingRegion &out, const MovingRegion &in) const
virtual double getIntersectingAreaInTime (const MovingRegion &r) const
virtual double getIntersectingAreaInTime (const Tools::IInterval &ivI, const MovingRegion &r) const
MovingRegion * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const byte *data) override
void storeToByteArray (byte **data, uint32_t &len) override
void getVMBR (Region &out) const override
void getMBRAtTime (double t, Region &out) const override
double getAreaInTime () const override
double getAreaInTime (const Tools::IInterval &ivI) const override
double getIntersectingAreaInTime (const ITimeShape &r) const override
double getIntersectingAreaInTime (const Tools::IInterval &ivI, const ITimeShape &r) const override
void makeInfinite (uint32_t dimension) override
void makeDimension (uint32_t dimension) override
Public Member Functions inherited from SpatialIndex::TimeRegion
TimeRegion ()
TimeRegion (const double *pLow, const double *pHigh, const Tools::IInterval &ti, uint32_t dimension)
TimeRegion (const double *pLow, const double *pHigh, double tStart, double tEnd, uint32_t dimension)
TimeRegion (const Point &low, const Point &high, const Tools::IInterval &ti)
TimeRegion (const Point &low, const Point &high, double tStart, double tEnd)
TimeRegion (const Region &in, const Tools::IInterval &ti)
TimeRegion (const Region &in, double tStart, double tEnd)
TimeRegion (const TimePoint &low, const TimePoint &high)
TimeRegion (const TimeRegion &in)
~TimeRegion () override
virtual TimeRegion & operator= (const TimeRegion &r)
virtual bool operator== (const TimeRegion &) const
virtual bool intersectsRegionInTime (const TimeRegion &in) const
virtual bool containsRegionInTime (const TimeRegion &in) const
virtual bool touchesRegionInTime (const TimeRegion &in) const
virtual bool containsPointInTime (const TimePoint &in) const
virtual bool touchesPointInTime (const TimePoint &in) const
virtual void combineRegionInTime (const TimeRegion &in)
virtual void getCombinedRegionInTime (TimeRegion &out, const TimeRegion &in) const
TimeRegion * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const byte *data) override
void storeToByteArray (byte **data, uint32_t &len) override
bool intersectsShapeInTime (const ITimeShape &in) const override
bool intersectsShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
bool containsShapeInTime (const ITimeShape &in) const override
bool containsShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
bool touchesShapeInTime (const ITimeShape &in) const override
bool touchesShapeInTime (const Tools::IInterval &ivI, const ITimeShape &in) const override
double getAreaInTime () const override
double getAreaInTime (const Tools::IInterval &ivI) const override
double getIntersectingAreaInTime (const ITimeShape &r) const override
double getIntersectingAreaInTime (const Tools::IInterval &ivI, const ITimeShape &r) const override
virtual Tools::IInterval & operator= (const Tools::IInterval &)
double getLowerBound () const override
double getUpperBound () const override
void setBounds (double, double) override
bool intersectsInterval (const Tools::IInterval &ti) const override
bool intersectsInterval (Tools::IntervalType t, const double start, const double end) const override
bool containsInterval (const Tools::IInterval &ti) const override
Tools::IntervalType getIntervalType () const override
void makeInfinite (uint32_t dimension) override
void makeDimension (uint32_t dimension) override
Public Member Functions inherited from SpatialIndex::Region
Region ()
Region (const double *pLow, const double *pHigh, uint32_t dimension)
Region (const Point &low, const Point &high)
Region (const Region &in)
~Region () override
virtual Region & operator= (const Region &r)
virtual bool operator== (const Region &) const
bool intersectsShape (const IShape &in) const override
bool containsShape (const IShape &in) const override
bool touchesShape (const IShape &in) const override
void getCenter (Point &out) const override
uint32_t getDimension () const override
void getMBR (Region &out) const override
double getArea () const override
double getMinimumDistance (const IShape &in) const override
virtual bool intersectsRegion (const Region &in) const
virtual bool containsRegion (const Region &in) const
virtual bool touchesRegion (const Region &in) const
virtual double getMinimumDistance (const Region &in) const
virtual bool intersectsLineSegment (const LineSegment &in) const
virtual bool containsPoint (const Point &in) const
virtual bool touchesPoint (const Point &in) const
virtual double getMinimumDistance (const Point &in) const
virtual Region getIntersectingRegion (const Region &r) const
virtual double getIntersectingArea (const Region &in) const
virtual double getMargin () const
virtual void combineRegion (const Region &in)
virtual void combinePoint (const Point &in)
virtual void getCombinedRegion (Region &out, const Region &in) const
virtual double getLow (uint32_t index) const
virtual double getHigh (uint32_t index) const
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
Public Member Functions inherited from SpatialIndex::IShape
~IShape () override=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Public Member Functions inherited from SpatialIndex::ITimeShape
~ITimeShape () override=default
Public Member Functions inherited from Tools::IInterval
virtual ~IInterval ()=default
Public Member Functions inherited from SpatialIndex::IEvolvingShape
virtual ~IEvolvingShape ()=default
Public Attributes
double * m_pVLow {nullptr}
double * m_pVHigh {nullptr}
Public Attributes inherited from SpatialIndex::TimeRegion
double m_startTime
double m_endTime
Public Attributes inherited from SpatialIndex::Region
uint32_t m_dimension {0}
double * m_pLow {nullptr}
double * m_pHigh {nullptr}
Friends
SIDX_DLL std::ostream & operator<< (std::ostream &os, const MovingRegion &r)
Detailed Description
Definition at line 32 of file MovingRegion.h.
Constructor & Destructor Documentation
MovingRegion() [1/9]
MovingRegion::MovingRegion ()
Definition at line 41 of file MovingRegion.cc.
Referenced by clone(), and MovingRegion().
MovingRegion() [2/9]
SpatialIndex::MovingRegion::MovingRegion (const double * pLow, const double * pHigh, const double * pVLow, const double * pVHigh, const Tools::IInterval & ti, uint32_t dimension)
MovingRegion() [3/9]
MovingRegion::MovingRegion (const double * pLow, const double * pHigh, const double * pVLow, const double * pVHigh, double tStart, double tEnd, uint32_t dimension)
Definition at line 54 of file MovingRegion.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Point::m_pCoords, and MovingRegion().
MovingRegion() [4/9]
SpatialIndex::MovingRegion::MovingRegion (const Point & low, const Point & high, const Point & vlow, const Point & vhigh, const Tools::IInterval & ti)
MovingRegion() [5/9]
MovingRegion::MovingRegion (const Point & low, const Point & high, const Point & vlow, const Point & vhigh, double tStart, double tEnd)
Definition at line 75 of file MovingRegion.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_dimension, SpatialIndex::Point::m_pCoords, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, and MovingRegion().
MovingRegion() [6/9]
SpatialIndex::MovingRegion::MovingRegion (const Region & mbr, const Region & vbr, const Tools::IInterval & ivI)
MovingRegion() [7/9]
MovingRegion::MovingRegion (const Region & mbr, const Region & vbr, double tStart, double tEnd)
Definition at line 97 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, and SpatialIndex::Region::m_pLow.
MovingRegion() [8/9]
MovingRegion::MovingRegion (const MovingPoint & low, const MovingPoint & high)
Definition at line 106 of file MovingRegion.cc.
References SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Point::m_pCoords, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingPoint::m_pVCoords, m_pVHigh, m_pVLow, SpatialIndex::TimePoint::m_startTime, and SpatialIndex::TimeRegion::m_startTime.
MovingRegion() [9/9]
MovingRegion::MovingRegion (const MovingRegion & in)
Definition at line 141 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
~MovingRegion()
MovingRegion::~MovingRegion () override
Definition at line 215 of file MovingRegion.cc.
References m_pVHigh, and m_pVLow.
Member Function Documentation
clone()
MovingRegion * MovingRegion::clone () override virtual
Implements Tools::IObject.
Definition at line 1021 of file MovingRegion.cc.
References MovingRegion().
combineRegionAfterTime()
void MovingRegion::combineRegionAfterTime (double t, const MovingRegion & r) virtual
Definition at line 834 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by getCombinedRegionAfterTime(), and SpatialIndex::TPRTree::Node::~Node().
combineRegionInTime()
void MovingRegion::combineRegionInTime (const MovingRegion & r) virtual
Definition at line 808 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by getCombinedRegionInTime().
containsPointInTime() [1/2]
bool MovingRegion::containsPointInTime (const MovingPoint & p) const virtual
Definition at line 753 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::MovingPoint::getProjectedCoord(), isShrinking(), SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::MovingPoint::m_pVCoords, m_pVHigh, m_pVLow, SpatialIndex::TimePoint::m_startTime, and SpatialIndex::TimeRegion::m_startTime.
Referenced by intersectsPointInTime().
containsPointInTime() [2/2]
virtual bool SpatialIndex::MovingRegion::containsPointInTime (const Tools::IInterval & ivI, const MovingPoint & p) const virtual
containsRegionAfterTime()
bool MovingRegion::containsRegionAfterTime (double t, const MovingRegion & r) const virtual
Definition at line 493 of file MovingRegion.cc.
References containsRegionInTime(), and SpatialIndex::TimeRegion::m_endTime.
Referenced by SpatialIndex::TPRTree::Node::~Node().
containsRegionAtTime()
bool MovingRegion::containsRegionAtTime (double t, const MovingRegion & r) const virtual
Definition at line 646 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
containsRegionInTime() [1/2]
bool MovingRegion::containsRegionInTime (const MovingRegion & r) const virtual
Definition at line 434 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), isShrinking(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by containsRegionAfterTime(), SpatialIndex::TPRTree::TPRTree::flush(), getIntersectingAreaInTime(), and intersectsRegionInTime().
containsRegionInTime() [2/2]
virtual bool SpatialIndex::MovingRegion::containsRegionInTime (const Tools::IInterval & ivI, const MovingRegion & r) const virtual
getAreaInTime() [1/2]
double MovingRegion::getAreaInTime () const override virtual
Implements SpatialIndex::ITimeShape.
Definition at line 1102 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), getVHigh(), getVLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
Referenced by getIntersectingAreaInTime(), and SpatialIndex::TPRTree::Node::~Node().
getAreaInTime() [2/2]
double SpatialIndex::MovingRegion::getAreaInTime (const Tools::IInterval & ivI) const override virtual
Implements SpatialIndex::ITimeShape.
getByteArraySize()
uint32_t MovingRegion::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 1029 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension.
Referenced by SpatialIndex::TPRTree::Data::getByteArraySize(), and storeToByteArray().
getCenterDistanceInTime() [1/2]
double MovingRegion::getCenterDistanceInTime (const MovingRegion & r) const virtual
Definition at line 558 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), getVHigh(), getVLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
Referenced by SpatialIndex::TPRTree::Node::~Node().
getCenterDistanceInTime() [2/2]
virtual double SpatialIndex::MovingRegion::getCenterDistanceInTime (const Tools::IInterval & ivI, const MovingRegion & r) const virtual
getCombinedRegionAfterTime()
void MovingRegion::getCombinedRegionAfterTime (double t, MovingRegion & out, const MovingRegion & in) const virtual
Definition at line 853 of file MovingRegion.cc.
References combineRegionAfterTime(), and SpatialIndex::Region::m_dimension.
getCombinedRegionInTime()
void MovingRegion::getCombinedRegionInTime (MovingRegion & out, const MovingRegion & in) const virtual
Definition at line 826 of file MovingRegion.cc.
References combineRegionInTime(), and SpatialIndex::Region::m_dimension.
getExtrapolatedHigh()
double MovingRegion::getExtrapolatedHigh (uint32_t index, double t) const virtual
Definition at line 302 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, m_pVHigh, and SpatialIndex::TimeRegion::m_startTime.
Referenced by combineRegionAfterTime(), combineRegionInTime(), containsPointInTime(), containsRegionAtTime(), containsRegionInTime(), getAreaInTime(), getCenterDistanceInTime(), getIntersectingAreaInTime(), getProjectedSurfaceAreaInTime(), intersectsPointInTime(), intersectsRegionAtTime(), intersectsRegionInTime(), and SpatialIndex::TPRTree::Node::~Node().
getExtrapolatedLow()
double MovingRegion::getExtrapolatedLow (uint32_t index, double t) const virtual
Definition at line 294 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pLow, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by combineRegionAfterTime(), combineRegionInTime(), containsPointInTime(), containsRegionAtTime(), containsRegionInTime(), getAreaInTime(), getCenterDistanceInTime(), getIntersectingAreaInTime(), getProjectedSurfaceAreaInTime(), intersectsPointInTime(), intersectsRegionAtTime(), intersectsRegionInTime(), and SpatialIndex::TPRTree::Node::~Node().
getHigh()
double MovingRegion::getHigh (uint32_t index, double t) const virtual
Definition at line 284 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, m_pVHigh, and SpatialIndex::TimeRegion::m_startTime.
Referenced by getIntersectingAreaInTime(), and getMBRAtTime().
getIntersectingAreaInTime() [1/4]
double MovingRegion::getIntersectingAreaInTime (const MovingRegion & r) const virtual
Definition at line 861 of file MovingRegion.cc.
References containsRegionInTime(), getAreaInTime(), getExtrapolatedHigh(), getExtrapolatedLow(), getHigh(), getLow(), Tools::Interval::getLowerBound(), Tools::Interval::getUpperBound(), getVHigh(), getVLow(), intersectsRegionInTime(), isShrinking(), SpatialIndex::MovingRegion::CrossPoint::m_boundary, SpatialIndex::Region::m_dimension, SpatialIndex::MovingRegion::CrossPoint::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, SpatialIndex::TimeRegion::m_startTime, SpatialIndex::MovingRegion::CrossPoint::m_t, and SpatialIndex::MovingRegion::CrossPoint::m_to.
Referenced by getIntersectingAreaInTime(), and SpatialIndex::TPRTree::Node::~Node().
getIntersectingAreaInTime() [2/4]
virtual double SpatialIndex::MovingRegion::getIntersectingAreaInTime (const Tools::IInterval & ivI, const MovingRegion & r) const virtual
getIntersectingAreaInTime() [3/4]
double MovingRegion::getIntersectingAreaInTime (const ITimeShape & r) const override virtual
Implements SpatialIndex::ITimeShape.
Definition at line 1157 of file MovingRegion.cc.
References getIntersectingAreaInTime().
getIntersectingAreaInTime() [4/4]
double SpatialIndex::MovingRegion::getIntersectingAreaInTime (const Tools::IInterval & ivI, const ITimeShape & r) const override virtual
Implements SpatialIndex::ITimeShape.
getLow()
double MovingRegion::getLow (uint32_t index, double t) const virtual
Definition at line 274 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pLow, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by getIntersectingAreaInTime(), and getMBRAtTime().
getMBRAtTime()
void MovingRegion::getMBRAtTime (double t, Region & out) const override virtual
Implements SpatialIndex::IEvolvingShape.
Definition at line 1089 of file MovingRegion.cc.
References getHigh(), getLow(), SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, and SpatialIndex::Region::makeDimension().
getProjectedSurfaceAreaInTime() [1/2]
double MovingRegion::getProjectedSurfaceAreaInTime () const virtual
Definition at line 503 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), getVHigh(), getVLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
Referenced by SpatialIndex::TPRTree::Node::~Node().
getProjectedSurfaceAreaInTime() [2/2]
virtual double SpatialIndex::MovingRegion::getProjectedSurfaceAreaInTime (const Tools::IInterval & ivI) const virtual
getVHigh()
double MovingRegion::getVHigh (uint32_t index) const virtual
Definition at line 316 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, and m_pVHigh.
Referenced by getAreaInTime(), getCenterDistanceInTime(), getIntersectingAreaInTime(), getProjectedSurfaceAreaInTime(), intersectsPointInTime(), and intersectsRegionInTime().
getVLow()
double MovingRegion::getVLow (uint32_t index) const virtual
Definition at line 309 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, and m_pVLow.
Referenced by getAreaInTime(), getCenterDistanceInTime(), getIntersectingAreaInTime(), getProjectedSurfaceAreaInTime(), intersectsPointInTime(), and intersectsRegionInTime().
getVMBR()
void MovingRegion::getVMBR (Region & out) const override virtual
Implements SpatialIndex::IEvolvingShape.
Definition at line 1082 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::Region::makeDimension().
intersectsPointInTime() [1/3]
bool MovingRegion::intersectsPointInTime (const MovingPoint & p) const virtual
Definition at line 660 of file MovingRegion.cc.
References containsPointInTime(), getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::MovingPoint::getProjectedCoord(), SpatialIndex::MovingPoint::getVCoord(), getVHigh(), getVLow(), isShrinking(), SpatialIndex::Point::m_dimension, SpatialIndex::Region::m_dimension, SpatialIndex::TimePoint::m_endTime, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::TimePoint::m_startTime, and SpatialIndex::TimeRegion::m_startTime.
intersectsPointInTime() [2/3]
virtual bool SpatialIndex::MovingRegion::intersectsPointInTime (const MovingPoint & p, Tools::IInterval & out) const virtual
intersectsPointInTime() [3/3]
virtual bool SpatialIndex::MovingRegion::intersectsPointInTime (const Tools::IInterval & ivI, const MovingPoint & p, Tools::IInterval & out) const virtual
intersectsRegionAtTime()
bool MovingRegion::intersectsRegionAtTime (double t, const MovingRegion & r) const virtual
Definition at line 630 of file MovingRegion.cc.
References getExtrapolatedHigh(), getExtrapolatedLow(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
intersectsRegionInTime() [1/3]
bool MovingRegion::intersectsRegionInTime (const MovingRegion & r) const virtual
Definition at line 323 of file MovingRegion.cc.
References containsRegionInTime(), getExtrapolatedHigh(), getExtrapolatedLow(), getVHigh(), getVLow(), isShrinking(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, and SpatialIndex::TimeRegion::m_startTime.
Referenced by SpatialIndex::TPRTree::TPRTree::flush(), and getIntersectingAreaInTime().
intersectsRegionInTime() [2/3]
virtual bool SpatialIndex::MovingRegion::intersectsRegionInTime (const MovingRegion & r, Tools::IInterval & out) const virtual
intersectsRegionInTime() [3/3]
virtual bool SpatialIndex::MovingRegion::intersectsRegionInTime (const Tools::IInterval & ivI, const MovingRegion & r, Tools::IInterval & ret) const virtual
isShrinking()
bool MovingRegion::isShrinking () const
Definition at line 264 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, m_pVHigh, and m_pVLow.
Referenced by containsPointInTime(), containsRegionInTime(), getIntersectingAreaInTime(), intersectsPointInTime(), and intersectsRegionInTime().
loadFromByteArray()
void MovingRegion::loadFromByteArray (const byte * data) override virtual
Implements Tools::ISerializable.
Definition at line 1034 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, SpatialIndex::TimeRegion::m_startTime, and makeDimension().
Referenced by SpatialIndex::TPRTree::Data::loadFromByteArray().
makeDimension()
void MovingRegion::makeDimension (uint32_t dimension) override virtual
Reimplemented from SpatialIndex::Region.
Definition at line 1185 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, and m_pVLow.
Referenced by SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::TPRTree::Node::loadFromByteArray(), loadFromByteArray(), makeInfinite(), and operator=().
makeInfinite()
void MovingRegion::makeInfinite (uint32_t dimension) override virtual
Reimplemented from SpatialIndex::Region.
Definition at line 1170 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, SpatialIndex::TimeRegion::m_startTime, and makeDimension().
Referenced by SpatialIndex::TPRTree::TPRTree::flush(), and SpatialIndex::TPRTree::Node::isIndex().
operator=()
MovingRegion & MovingRegion::operator= (const MovingRegion & r) virtual
Definition at line 221 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, SpatialIndex::TimeRegion::m_startTime, and makeDimension().
operator==()
bool MovingRegion::operator== (const MovingRegion & r) const virtual
Definition at line 240 of file MovingRegion.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
storeToByteArray()
void MovingRegion::storeToByteArray (byte ** data, uint32_t & len) override virtual
Implements Tools::ISerializable.
Definition at line 1056 of file MovingRegion.cc.
References getByteArraySize(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_pVHigh, m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by SpatialIndex::TPRTree::Data::storeToByteArray().
Friends And Related Function Documentation
operator<<
SIDX_DLL std::ostream& operator<< (std::ostream & os, const MovingRegion & r) friend
Member Data Documentation
m_pVHigh
double* SpatialIndex::MovingRegion::m_pVHigh {nullptr}
Definition at line 163 of file MovingRegion.h.
Referenced by combineRegionAfterTime(), combineRegionInTime(), containsPointInTime(), containsRegionInTime(), SpatialIndex::TPRTree::TPRTree::deleteData(), getExtrapolatedHigh(), getHigh(), getIntersectingAreaInTime(), getVHigh(), getVMBR(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::TPRTree::TPRTree::isIndexValid(), isShrinking(), SpatialIndex::TPRTree::Node::loadFromByteArray(), loadFromByteArray(), makeDimension(), makeInfinite(), MovingRegion(), SpatialIndex::operator<<(), operator=(), operator==(), SpatialIndex::TPRTree::Node::storeToByteArray(), storeToByteArray(), ~MovingRegion(), and SpatialIndex::TPRTree::Node::~Node().
m_pVLow
double* SpatialIndex::MovingRegion::m_pVLow {nullptr}
Definition at line 162 of file MovingRegion.h.
Referenced by combineRegionAfterTime(), combineRegionInTime(), containsPointInTime(), containsRegionInTime(), SpatialIndex::TPRTree::TPRTree::deleteData(), getExtrapolatedLow(), getIntersectingAreaInTime(), getLow(), getVLow(), getVMBR(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::TPRTree::TPRTree::isIndexValid(), isShrinking(), SpatialIndex::TPRTree::Node::loadFromByteArray(), loadFromByteArray(), makeDimension(), makeInfinite(), MovingRegion(), SpatialIndex::operator<<(), operator=(), operator==(), SpatialIndex::TPRTree::Node::storeToByteArray(), storeToByteArray(), ~MovingRegion(), and SpatialIndex::TPRTree::Node::~Node().
The documentation for this class was generated from the following files:
MovingRegion.h
MovingRegion.cc