libspatialindex API Reference: SpatialIndex::RTree::ExternalSorter::Record Class Reference
SpatialIndex::RTree::ExternalSorter::Record Class Reference
#include <BulkLoader.h>
Classes
struct SortAscending
Public Member Functions
Record ()
Record (const Region &r, id_type id, uint32_t len, byte *pData, uint32_t s)
~Record ()
bool operator< (const Record &r) const
void storeToFile (Tools::TemporaryFile &f)
void loadFromFile (Tools::TemporaryFile &f)
Public Attributes
Region m_r
id_type m_id
uint32_t m_len
byte * m_pData
uint32_t m_s
Detailed Description
Definition at line 31 of file BulkLoader.h.
Constructor & Destructor Documentation
ExternalSorter::Record::Record ()
Definition at line 42 of file BulkLoader.cc.
ExternalSorter::Record::Record (const Region & r, id_type id, uint32_t len, byte * pData, uint32_t s)
Definition at line 47 of file BulkLoader.cc.
ExternalSorter::Record::~Record ()
Definition at line 52 of file BulkLoader.cc.
Member Function Documentation
void ExternalSorter::Record::loadFromFile (Tools::TemporaryFile & f)
Definition at line 84 of file BulkLoader.cc.
References Tools::TemporaryFile::readBytes(), Tools::TemporaryFile::readDouble(), Tools::TemporaryFile::readUInt32(), and Tools::TemporaryFile::readUInt64().
Referenced by SpatialIndex::RTree::ExternalSorter::getNextRecord(), and SpatialIndex::RTree::ExternalSorter::sort().
bool ExternalSorter::Record::operator< (const Record & r) const
Definition at line 57 of file BulkLoader.cc.
References SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, m_r, and m_s.
void ExternalSorter::Record::storeToFile (Tools::TemporaryFile & f)
Definition at line 68 of file BulkLoader.cc.
References Tools::TemporaryFile::write().
Member Data Documentation
id_type SpatialIndex::RTree::ExternalSorter::Record::m_id
Definition at line 54 of file BulkLoader.h.
uint32_t SpatialIndex::RTree::ExternalSorter::Record::m_len
Definition at line 55 of file BulkLoader.h.
byte* SpatialIndex::RTree::ExternalSorter::Record::m_pData
Definition at line 56 of file BulkLoader.h.
Region SpatialIndex::RTree::ExternalSorter::Record::m_r
Definition at line 53 of file BulkLoader.h.
Referenced by operator<(), and SpatialIndex::RTree::ExternalSorter::sort().
uint32_t SpatialIndex::RTree::ExternalSorter::Record::m_s
Definition at line 57 of file BulkLoader.h.
Referenced by SpatialIndex::RTree::BulkLoader::createLevel(), and operator<().
The documentation for this class was generated from the following files:
BulkLoader.h
BulkLoader.cc