libspatialindex API Reference: Tools::Interval Class Reference
Tools::Interval Class Reference
#include <Tools.h>
Public Member Functions
Interval ()
Interval (IntervalType, double, double)
Interval (double, double)
Interval (const Interval &)
~Interval () override=default
virtual IInterval & operator= (const IInterval &)
virtual bool operator== (const Interval &) const
virtual bool operator!= (const Interval &) const
double getLowerBound () const override
double getUpperBound () const override
void setBounds (double, double) override
bool intersectsInterval (const IInterval &) const override
bool intersectsInterval (IntervalType type, const double start, const double end) const override
bool containsInterval (const IInterval &) const override
IntervalType getIntervalType () const override
Public Member Functions inherited from Tools::IInterval
virtual ~IInterval ()=default
Public Attributes
IntervalType m_type {IT_RIGHTOPEN}
double m_low {0.0}
double m_high {0.0}
Detailed Description
Definition at line 327 of file Tools.h.
Constructor & Destructor Documentation
Interval() [1/4]
Tools::Interval::Interval () default
Referenced by Tools::PropertySet::removeProperty().
Interval() [2/4]
Tools::Interval::Interval (IntervalType t, double l, double h)
Definition at line 375 of file Tools.cc.
Interval() [3/4]
Tools::Interval::Interval (double l, double h)
Definition at line 380 of file Tools.cc.
Interval() [4/4]
Tools::Interval::Interval (const Interval & iv)
Definition at line 385 of file Tools.cc.
References m_high, m_low, and m_type.
~Interval()
Tools::Interval::~Interval () override default
Member Function Documentation
containsInterval()
bool Tools::Interval::containsInterval (const IInterval & i) const override virtual
Implements Tools::IInterval.
Definition at line 499 of file Tools.cc.
References Tools::IInterval::getIntervalType(), Tools::IInterval::getLowerBound(), Tools::IInterval::getUpperBound(), Tools::IT_CLOSED, Tools::IT_LEFTOPEN, Tools::IT_OPEN, Tools::IT_RIGHTOPEN, m_high, m_low, and m_type.
getIntervalType()
Tools::IntervalType Tools::Interval::getIntervalType () const override virtual
Implements Tools::IInterval.
Definition at line 536 of file Tools.cc.
References m_type.
getLowerBound()
double Tools::Interval::getLowerBound () const override virtual
Implements Tools::IInterval.
Definition at line 422 of file Tools.cc.
References m_low.
Referenced by SpatialIndex::MovingRegion::getIntersectingAreaInTime().
getUpperBound()
double Tools::Interval::getUpperBound () const override virtual
Implements Tools::IInterval.
Definition at line 427 of file Tools.cc.
References m_high.
Referenced by SpatialIndex::MovingRegion::getIntersectingAreaInTime().
intersectsInterval() [1/2]
bool Tools::Interval::intersectsInterval (const IInterval & i) const override virtual
Implements Tools::IInterval.
Definition at line 440 of file Tools.cc.
References Tools::IInterval::getIntervalType(), Tools::IInterval::getLowerBound(), and Tools::IInterval::getUpperBound().
intersectsInterval() [2/2]
bool Tools::Interval::intersectsInterval (IntervalType type, const double start, const double end) const override virtual
Implements Tools::IInterval.
Definition at line 445 of file Tools.cc.
References Tools::IT_CLOSED, Tools::IT_LEFTOPEN, Tools::IT_OPEN, Tools::IT_RIGHTOPEN, m_high, m_low, and m_type.
operator!=()
bool Tools::Interval::operator!= (const Interval & iv) const virtual
Definition at line 417 of file Tools.cc.
operator=()
Tools::IInterval & Tools::Interval::operator= (const IInterval & iv) virtual
Definition at line 392 of file Tools.cc.
References Tools::IInterval::getIntervalType(), Tools::IInterval::getLowerBound(), Tools::IInterval::getUpperBound(), m_high, m_low, and m_type.
operator==()
bool Tools::Interval::operator== (const Interval & iv) const virtual
Definition at line 404 of file Tools.cc.
References m_high, m_low, and m_type.
setBounds()
void Tools::Interval::setBounds (double l, double h) override virtual
Implements Tools::IInterval.
Definition at line 432 of file Tools.cc.
References m_high, and m_low.
Member Data Documentation
m_high
double Tools::Interval::m_high {0.0}
Definition at line 349 of file Tools.h.
Referenced by containsInterval(), getUpperBound(), intersectsInterval(), Interval(), Tools::operator<<(), operator=(), operator==(), and setBounds().
m_low
double Tools::Interval::m_low {0.0}
Definition at line 348 of file Tools.h.
Referenced by containsInterval(), getLowerBound(), intersectsInterval(), Interval(), Tools::operator<<(), operator=(), operator==(), and setBounds().
m_type
IntervalType Tools::Interval::m_type {IT_RIGHTOPEN}
Definition at line 347 of file Tools.h.
Referenced by containsInterval(), getIntervalType(), intersectsInterval(), Interval(), Tools::operator<<(), operator=(), and operator==().
The documentation for this class was generated from the following files:
Tools.h
Tools.cc