libspatialindex API Reference: Tools::BufferedFileReader Class Reference
Tools::BufferedFileReader Class Reference
#include <Tools.h>
Public Member Functions
BufferedFileReader ()
BufferedFileReader (const std::string &sFileName, uint32_t u32BufferSize=32768)
~BufferedFileReader () override
virtual void open (const std::string &sFileName)
void rewind () override
void seek (std::fstream::off_type offset) override
virtual uint8_t readUInt8 ()
virtual uint16_t readUInt16 ()
virtual uint32_t readUInt32 ()
virtual uint64_t readUInt64 ()
virtual float readFloat ()
virtual double readDouble ()
virtual bool readBoolean ()
virtual std::string readString ()
virtual void readBytes (uint32_t u32Len, uint8_t **pData)
Public Member Functions inherited from Tools::BufferedFile
BufferedFile (uint32_t u32BufferSize=16384)
virtual ~BufferedFile ()
virtual void close ()
virtual bool eof ()
Additional Inherited Members
Protected Attributes inherited from Tools::BufferedFile
std::fstream m_file
char * m_buffer
uint32_t m_u32BufferSize
bool m_bEOF {true}
Detailed Description
Definition at line 424 of file Tools.h.
Constructor & Destructor Documentation
BufferedFileReader() [1/2]
Tools::BufferedFileReader::BufferedFileReader () default
Referenced by Tools::BufferedFile::eof().
BufferedFileReader() [2/2]
Tools::BufferedFileReader::BufferedFileReader (const std::string & sFileName, uint32_t u32BufferSize = 32768)
Definition at line 742 of file Tools.cc.
References open().
~BufferedFileReader()
Tools::BufferedFileReader::~BufferedFileReader () override default
Referenced by open().
Member Function Documentation
open()
void Tools::BufferedFileReader::open (const std::string & sFileName) virtual
Definition at line 748 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, Tools::BufferedFile::m_buffer, Tools::BufferedFile::m_file, Tools::BufferedFile::m_u32BufferSize, and ~BufferedFileReader().
Referenced by BufferedFileReader(), and Tools::BufferedFileWriter::BufferedFileWriter().
readBoolean()
bool Tools::BufferedFileReader::readBoolean () virtual
Definition at line 867 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
readBytes()
void Tools::BufferedFileReader::readBytes (uint32_t u32Len, uint8_t ** pData) virtual
Definition at line 908 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readBytes().
readDouble()
double Tools::BufferedFileReader::readDouble () virtual
Definition at line 853 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readDouble().
readFloat()
float Tools::BufferedFileReader::readFloat () virtual
Definition at line 839 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readFloat().
readString()
std::string Tools::BufferedFileReader::readString () virtual
Definition at line 881 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readString().
readUInt16()
uint16_t Tools::BufferedFileReader::readUInt16 () virtual
Definition at line 797 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readUInt16().
readUInt32()
uint32_t Tools::BufferedFileReader::readUInt32 () virtual
Definition at line 811 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readUInt32().
readUInt64()
uint64_t Tools::BufferedFileReader::readUInt64 () virtual
Definition at line 825 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readUInt64().
readUInt8()
uint8_t Tools::BufferedFileReader::readUInt8 () virtual
Definition at line 783 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::readUInt8().
rewind()
void Tools::BufferedFileReader::rewind () override virtual
Implements Tools::BufferedFile.
Definition at line 764 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
Referenced by Tools::TemporaryFile::rewindForReading().
seek()
void Tools::BufferedFileReader::seek (std::fstream::off_type offset) override virtual
Implements Tools::BufferedFile.
Definition at line 774 of file Tools.cc.
References Tools::BufferedFile::m_bEOF, and Tools::BufferedFile::m_file.
The documentation for this class was generated from the following files:
Tools.h
Tools.cc