libspatialindex API Reference: SpatialIndex::IEntry Class Reference
SpatialIndex::IEntry Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual id_type getIdentifier () const =0
virtual void getShape (IShape **out) const =0
~IEntry () override=default
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
virtual IObject * clone ()=0
Detailed Description
Definition at line 105 of file SpatialIndex.h.
Constructor & Destructor Documentation
~IEntry()
SpatialIndex::IEntry::~IEntry () override default
Member Function Documentation
getIdentifier()
virtual id_type SpatialIndex::IEntry::getIdentifier () const pure virtual
Implemented in SpatialIndex::RTree::Data, SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, SpatialIndex::TPRTree::Node, SpatialIndex::MVRTree::Data, and SpatialIndex::TPRTree::Data.
Referenced by get_results(), IndexItem_GetID(), and IdVisitor::visitData().
getShape()
virtual void SpatialIndex::IEntry::getShape (IShape ** out) const pure virtual
Implemented in SpatialIndex::RTree::Data, SpatialIndex::MVRTree::Node, SpatialIndex::RTree::Node, SpatialIndex::TPRTree::Node, SpatialIndex::MVRTree::Data, and SpatialIndex::TPRTree::Data.
Referenced by get_results(), BoundsQuery::getNextEntry(), and IndexItem_GetBounds().
The documentation for this class was generated from the following file:
SpatialIndex.h