libspatialindex API Reference: Error Class Reference
Error Class Reference
#include <Error.h>
Public Member Functions
Error (int code, std::string const &message, std::string const &method)
Error (Error const &other)
Copy constructor.
Error & operator= (Error const &rhs)
Assignment operator.
int GetCode () const
const char * GetMessage () const
const char * GetMethod () const
Detailed Description
Definition at line 33 of file Error.h.
Constructor & Destructor Documentation
Error() [1/2]
Error::Error (int code, std::string const & message, std::string const & method)
Definition at line 31 of file Error.cc.
Error() [2/2]
Error::Error (Error const & other)
Copy constructor.
Definition at line 38 of file Error.cc.
Member Function Documentation
GetCode()
int Error::GetCode () const inline
Definition at line 45 of file Error.h.
Referenced by Error_GetLastErrorNum().
GetMessage()
const char* Error::GetMessage () const inline
Definition at line 46 of file Error.h.
Referenced by Error_GetLastErrorMsg().
GetMethod()
const char* Error::GetMethod () const inline
Definition at line 47 of file Error.h.
Referenced by Error_GetLastErrorMethod().
operator=()
Error & Error::operator= (Error const & rhs)
Assignment operator.
Definition at line 45 of file Error.cc.
The documentation for this class was generated from the following files:
Error.h
Error.cc