libspatialindex API Reference: SpatialIndex::RTree::Node Class Reference
SpatialIndex::RTree::Node Class Reference abstract
#include <Node.h>
Public Member Functions
~Node () override
Tools::IObject * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const uint8_t *data) override
void storeToByteArray (uint8_t **data, uint32_t &len) override
id_type getIdentifier () const override
void getShape (IShape **out) const override
uint32_t getChildrenCount () const override
id_type getChildIdentifier (uint32_t index) const override
void getChildShape (uint32_t index, IShape **out) const override
void getChildData (uint32_t index, uint32_t &length, uint8_t **data) const override
uint32_t getLevel () const override
bool isIndex () const override
bool isLeaf () const override
Public Member Functions inherited from SpatialIndex::INode
~INode () override=default
Public Member Functions inherited from SpatialIndex::IEntry
~IEntry () override=default
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Friends
class RTree
class Leaf
class Index
class Tools::PointerPool< Node >
class BulkLoader
Detailed Description
Definition at line 44 of file rtree/Node.h.
Constructor & Destructor Documentation
~Node()
Node::~Node () override
Definition at line 264 of file rtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::RTree::Index::adjustTree(), SpatialIndex::Region::combineRegion(), SpatialIndex::Region::containsRegion(), Tools::PoolPointer< X >::get(), SpatialIndex::Region::getArea(), SpatialIndex::Region::getCenter(), SpatialIndex::Region::getCombinedRegion(), SpatialIndex::Region::getIntersectingArea(), SpatialIndex::Region::getMargin(), Index::index(), Index, SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::RTree::RV_LINEAR, SpatialIndex::RTree::RV_QUADRATIC, SpatialIndex::RTree::RV_RSTAR, and SpatialIndex::Region::touchesRegion().
Member Function Documentation
clone()
Tools::IObject * Node::clone () override virtual
Implements Tools::IObject.
Definition at line 44 of file rtree/Node.cc.
getByteArraySize()
uint32_t Node::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 52 of file rtree/Node.cc.
Referenced by storeToByteArray().
getChildData()
void Node::getChildData (uint32_t index, uint32_t & length, uint8_t ** data) const override virtual
Implements SpatialIndex::INode.
Definition at line 196 of file rtree/Node.cc.
References Index::index().
getChildIdentifier()
SpatialIndex::id_type Node::getChildIdentifier (uint32_t index) const override virtual
Implements SpatialIndex::INode.
Definition at line 182 of file rtree/Node.cc.
References Index::index().
getChildrenCount()
uint32_t Node::getChildrenCount () const override virtual
Implements SpatialIndex::INode.
Definition at line 177 of file rtree/Node.cc.
getChildShape()
void Node::getChildShape (uint32_t index, IShape ** out) const override virtual
Implements SpatialIndex::INode.
Definition at line 189 of file rtree/Node.cc.
getIdentifier()
SpatialIndex::id_type Node::getIdentifier () const override virtual
Implements SpatialIndex::IEntry.
Definition at line 164 of file rtree/Node.cc.
Referenced by SpatialIndex::RTree::RTree::internalNodesQuery().
getLevel()
uint32_t Node::getLevel () const override virtual
Implements SpatialIndex::INode.
Definition at line 211 of file rtree/Node.cc.
getShape()
void Node::getShape (IShape ** out) const override virtual
Implements SpatialIndex::IEntry.
Definition at line 169 of file rtree/Node.cc.
isIndex()
bool Node::isIndex () const override virtual
Implements SpatialIndex::INode.
Definition at line 221 of file rtree/Node.cc.
References SpatialIndex::Region::makeInfinite().
isLeaf()
bool Node::isLeaf () const override virtual
Implements SpatialIndex::INode.
Definition at line 216 of file rtree/Node.cc.
loadFromByteArray()
void Node::loadFromByteArray (const uint8_t * data) override virtual
Implements Tools::ISerializable.
Definition at line 63 of file rtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::Region::m_pHigh, and SpatialIndex::Region::m_pLow.
Referenced by SpatialIndex::RTree::RTree::flush().
storeToByteArray()
void Node::storeToByteArray (uint8_t ** data, uint32_t & len) override virtual
Implements Tools::ISerializable.
Definition at line 112 of file rtree/Node.cc.
References getByteArraySize(), SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::RTree::PersistentIndex, and SpatialIndex::RTree::PersistentLeaf.
Referenced by SpatialIndex::RTree::RTree::flush().
Friends And Related Function Documentation
BulkLoader
friend class BulkLoader friend
Definition at line 194 of file rtree/Node.h.
Index
friend class Index friend
Definition at line 192 of file rtree/Node.h.
Referenced by ~Node().
Leaf
friend class Leaf friend
Definition at line 191 of file rtree/Node.h.
RTree
friend class RTree friend
Definition at line 190 of file rtree/Node.h.
Tools::PointerPool< Node >
friend class Tools::PointerPool< Node > friend
Definition at line 193 of file rtree/Node.h.
The documentation for this class was generated from the following files:
rtree/Node.h
rtree/Node.cc