libspatialindex API Reference: SpatialIndex::InvalidPageException Class Reference
SpatialIndex::InvalidPageException Class Reference
#include <SpatialIndex.h>
Public Member Functions
InvalidPageException (id_type id)
~InvalidPageException () override=default
std::string what () override
Public Member Functions inherited from Tools::Exception
virtual ~Exception ()=default
Detailed Description
Definition at line 52 of file SpatialIndex.h.
Constructor & Destructor Documentation
InvalidPageException()
SpatialIndex::InvalidPageException::InvalidPageException (id_type id)
Definition at line 33 of file SpatialIndexImpl.cc.
~InvalidPageException()
SpatialIndex::InvalidPageException::~InvalidPageException () override default
Member Function Documentation
what()
std::string SpatialIndex::InvalidPageException::what () override virtual
Implements Tools::Exception.
Definition at line 40 of file SpatialIndexImpl.cc.
Referenced by SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), and SpatialIndex::MVRTree::MVRTree::flush().
The documentation for this class was generated from the following files:
SpatialIndex.h
SpatialIndexImpl.cc