libspatialindex API Reference: Tools::NotSupportedException Class Reference
Tools::NotSupportedException Class Reference
#include <Tools.h>
Public Member Functions
NotSupportedException (std::string s)
~NotSupportedException () override=default
std::string what () override
Public Member Functions inherited from Tools::Exception
virtual ~Exception ()=default
Detailed Description
Definition at line 180 of file Tools.h.
Constructor & Destructor Documentation
NotSupportedException()
Tools::NotSupportedException::NotSupportedException (std::string s)
Definition at line 97 of file Tools.cc.
Referenced by Tools::PropertySet::getByteArraySize(), and Tools::PropertySet::storeToByteArray().
~NotSupportedException()
Tools::NotSupportedException::~NotSupportedException () override default
Member Function Documentation
what()
std::string Tools::NotSupportedException::what () override virtual
Implements Tools::Exception.
Definition at line 101 of file Tools.cc.
References Tools::Variant::Variant().
The documentation for this class was generated from the following files:
Tools.h
Tools.cc