libspatialindex API Reference: SpatialIndex::StorageManager::DiskStorageManager Class Reference
SpatialIndex::StorageManager::DiskStorageManager Class Reference
#include <DiskStorageManager.h>
Public Member Functions
DiskStorageManager (Tools::PropertySet &)
virtual ~DiskStorageManager ()
virtual void flush ()
virtual void loadByteArray (const id_type page, uint32_t &len, byte **data)
virtual void storeByteArray (id_type &page, const uint32_t len, const byte *const data)
virtual void deleteByteArray (const id_type page)
Public Member Functions inherited from SpatialIndex::IStorageManager
virtual ~IStorageManager ()
Detailed Description
Definition at line 34 of file DiskStorageManager.h.
Constructor & Destructor Documentation
DiskStorageManager::DiskStorageManager (Tools::PropertySet & ps)
Definition at line 124 of file DiskStorageManager.cc.
References Tools::Variant::blVal, CheckFilesExists(), Tools::PropertySet::getProperty(), Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::pcVal, Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_EMPTY, Tools::VT_PCHAR, and Tools::VT_ULONG.
DiskStorageManager::~DiskStorageManager () virtual
Definition at line 270 of file DiskStorageManager.cc.
References flush().
Member Function Documentation
void DiskStorageManager::deleteByteArray (const id_type page) virtual
Implements SpatialIndex::IStorageManager.
Definition at line 487 of file DiskStorageManager.cc.
void DiskStorageManager::flush () virtual
Definition at line 281 of file DiskStorageManager.cc.
Referenced by ~DiskStorageManager().
void DiskStorageManager::loadByteArray (const id_type page, uint32_t & len, byte ** data) virtual
Implements SpatialIndex::IStorageManager.
Definition at line 339 of file DiskStorageManager.cc.
void DiskStorageManager::storeByteArray (id_type & page, const uint32_t len, const byte *const data) virtual
Implements SpatialIndex::IStorageManager.
Definition at line 377 of file DiskStorageManager.cc.
References SpatialIndex::StorageManager::NewPage.
The documentation for this class was generated from the following files:
DiskStorageManager.h
DiskStorageManager.cc