libspatialindex API Reference: SpatialIndex::IStorageManager Class Reference
SpatialIndex::IStorageManager Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual void loadByteArray (const id_type id, uint32_t &len, uint8_t **data)=0
virtual void storeByteArray (id_type &id, const uint32_t len, const uint8_t *const data)=0
virtual void deleteByteArray (const id_type id)=0
virtual void flush ()=0
virtual ~IStorageManager ()=default
Detailed Description
Definition at line 155 of file SpatialIndex.h.
Constructor & Destructor Documentation
~IStorageManager()
virtual SpatialIndex::IStorageManager::~IStorageManager () virtual default
Member Function Documentation
deleteByteArray()
virtual void SpatialIndex::IStorageManager::deleteByteArray (const id_type id) pure virtual
Implemented in SpatialIndex::StorageManager::CustomStorageManager, SpatialIndex::StorageManager::Buffer, SpatialIndex::StorageManager::MemoryStorageManager, and SpatialIndex::StorageManager::DiskStorageManager.
Referenced by SpatialIndex::StorageManager::Buffer::deleteByteArray(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), and SpatialIndex::MVRTree::MVRTree::flush().
flush()
virtual void SpatialIndex::IStorageManager::flush () pure virtual
Implemented in SpatialIndex::StorageManager::CustomStorageManager, SpatialIndex::StorageManager::Buffer, SpatialIndex::StorageManager::MemoryStorageManager, and SpatialIndex::StorageManager::DiskStorageManager.
loadByteArray()
virtual void SpatialIndex::IStorageManager::loadByteArray (const id_type id, uint32_t & len, uint8_t ** data) pure virtual
Implemented in SpatialIndex::StorageManager::CustomStorageManager, SpatialIndex::StorageManager::Buffer, SpatialIndex::StorageManager::MemoryStorageManager, and SpatialIndex::StorageManager::DiskStorageManager.
Referenced by SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), and SpatialIndex::StorageManager::Buffer::loadByteArray().
storeByteArray()
virtual void SpatialIndex::IStorageManager::storeByteArray (id_type & id, const uint32_t len, const uint8_t *const data) pure virtual
Implemented in SpatialIndex::StorageManager::CustomStorageManager, SpatialIndex::StorageManager::Buffer, SpatialIndex::StorageManager::MemoryStorageManager, and SpatialIndex::StorageManager::DiskStorageManager.
Referenced by SpatialIndex::StorageManager::Buffer::clear(), SpatialIndex::StorageManager::Buffer::flush(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), SpatialIndex::StorageManager::RandomEvictionsBuffer::removeEntry(), and SpatialIndex::StorageManager::Buffer::storeByteArray().
The documentation for this class was generated from the following file:
SpatialIndex.h