libspatialindex API Reference: Tools::PointerPool< X > Class Template Reference
Tools::PointerPool< X > Class Template Reference
#include <PointerPool.h>
Public Member Functions
PointerPool (uint32_t capacity)
~PointerPool ()
PoolPointer< X > acquire ()
void release (X *p)
uint32_t getCapacity () const
void setCapacity (uint32_t c)
Public Attributes
uint64_t m_hits
uint64_t m_misses
uint64_t m_pointerCount
Detailed Description
template<class X>
class Tools::PointerPool< X >
Definition at line 34 of file PointerPool.h.
Constructor & Destructor Documentation
PointerPool()
template<class X> Tools::PointerPool< X >::PointerPool (uint32_t capacity) inline explicit
Definition at line 37 of file PointerPool.h.
~PointerPool()
template<class X> Tools::PointerPool< X >::~PointerPool () inline
Definition at line 46 of file PointerPool.h.
Member Function Documentation
acquire()
template<class X> PoolPointer<X> Tools::PointerPool< X >::acquire () inline
Definition at line 64 of file PointerPool.h.
Referenced by SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::RTree::RTree::deleteData(), SpatialIndex::MVRTree::MVRTree::deleteData(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::RTree::RTree::insertData(), SpatialIndex::MVRTree::MVRTree::insertData(), SpatialIndex::TPRTree::Node::loadFromByteArray(), SpatialIndex::MVRTree::Node::loadFromByteArray(), SpatialIndex::RTree::Node::loadFromByteArray(), SpatialIndex::RTree::RTree::selfJoinQuery(), SpatialIndex::TPRTree::Node::~Node(), SpatialIndex::RTree::Node::~Node(), and SpatialIndex::MVRTree::Node::~Node().
getCapacity()
template<class X> uint32_t Tools::PointerPool< X >::getCapacity () const inline
Definition at line 104 of file PointerPool.h.
Referenced by SpatialIndex::TPRTree::TPRTree::getIndexProperties(), SpatialIndex::RTree::RTree::getIndexProperties(), and SpatialIndex::MVRTree::MVRTree::getIndexProperties().
release()
template<class X> void Tools::PointerPool< X >::release (X * p) inline
Definition at line 87 of file PointerPool.h.
Referenced by Tools::PoolPointer< MovingRegion >::relinquish().
setCapacity()
template<class X> void Tools::PointerPool< X >::setCapacity (uint32_t c) inline
Definition at line 105 of file PointerPool.h.
Referenced by SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), and SpatialIndex::MVRTree::MVRTree::flush().
Member Data Documentation
m_hits
template<class X> uint64_t Tools::PointerPool< X >::m_hits
Definition at line 117 of file PointerPool.h.
Referenced by Tools::PointerPool< SpatialIndex::MovingRegion >::acquire(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::acquire(), SpatialIndex::TPRTree::operator<<(), SpatialIndex::RTree::operator<<(), SpatialIndex::MVRTree::operator<<(), Tools::PointerPool< SpatialIndex::MovingRegion >::PointerPool(), and Tools::PointerPool< SpatialIndex::MVRTree::Node >::PointerPool().
m_misses
template<class X> uint64_t Tools::PointerPool< X >::m_misses
Definition at line 118 of file PointerPool.h.
Referenced by Tools::PointerPool< SpatialIndex::MovingRegion >::acquire(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::acquire(), SpatialIndex::TPRTree::operator<<(), SpatialIndex::RTree::operator<<(), SpatialIndex::MVRTree::operator<<(), Tools::PointerPool< SpatialIndex::MovingRegion >::PointerPool(), and Tools::PointerPool< SpatialIndex::MVRTree::Node >::PointerPool().
m_pointerCount
template<class X> uint64_t Tools::PointerPool< X >::m_pointerCount
Definition at line 119 of file PointerPool.h.
Referenced by Tools::PointerPool< SpatialIndex::MovingRegion >::acquire(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::acquire(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::PointerPool(), Tools::PointerPool< SpatialIndex::MovingRegion >::PointerPool(), Tools::PointerPool< SpatialIndex::MovingRegion >::release(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::release(), Tools::PointerPool< SpatialIndex::MVRTree::Node >::~PointerPool(), and Tools::PointerPool< SpatialIndex::MovingRegion >::~PointerPool().
The documentation for this class was generated from the following file:
PointerPool.h