libspatialindex API Reference: Tools::Random Class Reference
Tools::Random Class Reference
#include <Tools.h>
Public Member Functions
Random ()
Random (uint32_t seed, uint16_t xsubi0)
virtual ~Random ()
int32_t nextUniformLong ()
uint32_t nextUniformUnsignedLong ()
int32_t nextUniformLong (int32_t low, int32_t high)
uint32_t nextUniformUnsignedLong (uint32_t low, uint32_t high)
int64_t nextUniformLongLong ()
uint64_t nextUniformUnsignedLongLong ()
int64_t nextUniformLongLong (int64_t low, int64_t high)
uint64_t nextUniformUnsignedLongLong (uint64_t low, uint64_t high)
int16_t nextUniformShort ()
uint16_t nextUniformUnsignedShort ()
double nextUniformDouble ()
double nextUniformDouble (double low, double high)
bool flipCoin ()
Detailed Description
Definition at line 354 of file Tools.h.
Constructor & Destructor Documentation
Random() [1/2]
Tools::Random::Random ()
Definition at line 541 of file Tools.cc.
Random() [2/2]
Tools::Random::Random (uint32_t seed, uint16_t xsubi0)
Definition at line 547 of file Tools.cc.
~Random()
Tools::Random::~Random () virtual
Definition at line 553 of file Tools.cc.
References srand48().
Member Function Documentation
flipCoin()
bool Tools::Random::flipCoin ()
Definition at line 641 of file Tools.cc.
nextUniformDouble() [1/2]
double Tools::Random::nextUniformDouble ()
Definition at line 630 of file Tools.cc.
References erand48().
nextUniformDouble() [2/2]
double Tools::Random::nextUniformDouble (double low, double high)
Definition at line 636 of file Tools.cc.
nextUniformLong() [1/2]
int32_t Tools::Random::nextUniformLong ()
Definition at line 576 of file Tools.cc.
References jrand48().
nextUniformLong() [2/2]
int32_t Tools::Random::nextUniformLong (int32_t low, int32_t high)
Definition at line 586 of file Tools.cc.
nextUniformLongLong() [1/2]
int64_t Tools::Random::nextUniformLongLong ()
Definition at line 596 of file Tools.cc.
nextUniformLongLong() [2/2]
int64_t Tools::Random::nextUniformLongLong (int64_t low, int64_t high)
Definition at line 609 of file Tools.cc.
nextUniformShort()
int16_t Tools::Random::nextUniformShort ()
Definition at line 619 of file Tools.cc.
nextUniformUnsignedLong() [1/2]
uint32_t Tools::Random::nextUniformUnsignedLong ()
Definition at line 581 of file Tools.cc.
nextUniformUnsignedLong() [2/2]
uint32_t Tools::Random::nextUniformUnsignedLong (uint32_t low, uint32_t high)
Definition at line 591 of file Tools.cc.
nextUniformUnsignedLongLong() [1/2]
uint64_t Tools::Random::nextUniformUnsignedLongLong ()
Definition at line 601 of file Tools.cc.
nextUniformUnsignedLongLong() [2/2]
uint64_t Tools::Random::nextUniformUnsignedLongLong (uint64_t low, uint64_t high)
Definition at line 614 of file Tools.cc.
nextUniformUnsignedShort()
uint16_t Tools::Random::nextUniformUnsignedShort ()
Definition at line 624 of file Tools.cc.
The documentation for this class was generated from the following files:
Tools.h
Tools.cc