libspatialindex API Reference: SpatialIndex::RTree::RTree Class Reference
SpatialIndex::RTree::RTree Class Reference
#include <RTree.h>
Public Member Functions
RTree (IStorageManager &, Tools::PropertySet &)
~RTree ()
virtual void insertData (uint32_t len, const uint8_t *pData, const IShape &shape, id_type shapeIdentifier)
virtual bool deleteData (const IShape &shape, id_type id)
virtual void internalNodesQuery (const IShape &query, IVisitor &v)
virtual void containsWhatQuery (const IShape &query, IVisitor &v)
virtual void intersectsWithQuery (const IShape &query, IVisitor &v)
virtual void pointLocationQuery (const Point &query, IVisitor &v)
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v, INearestNeighborComparator &)
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v)
virtual void selfJoinQuery (const IShape &s, IVisitor &v)
virtual void queryStrategy (IQueryStrategy &qs)
virtual void getIndexProperties (Tools::PropertySet &out) const
virtual void addCommand (ICommand *pCommand, CommandType ct)
virtual bool isIndexValid ()
virtual void getStatistics (IStatistics **out) const
virtual void flush ()
Public Member Functions inherited from SpatialIndex::ISpatialIndex
virtual ~ISpatialIndex ()=default
Friends
class Node
class Leaf
class Index
class BulkLoader
std::ostream & operator<< (std::ostream &os, const RTree &t)
Detailed Description
Definition at line 39 of file src/rtree/RTree.h.
Constructor & Destructor Documentation
RTree()
SpatialIndex::RTree::RTree::RTree (IStorageManager & sm, Tools::PropertySet & ps)
Definition at line 358 of file RTree.cc.
References Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::VT_EMPTY, Tools::VT_LONG, and Tools::VT_LONGLONG.
~RTree()
SpatialIndex::RTree::RTree::~RTree ()
Definition at line 395 of file RTree.cc.
Member Function Documentation
addCommand()
void SpatialIndex::RTree::RTree::addCommand (ICommand * pCommand, CommandType ct) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 733 of file RTree.cc.
References SpatialIndex::CT_NODEDELETE, SpatialIndex::CT_NODEREAD, and SpatialIndex::CT_NODEWRITE.
containsWhatQuery()
void SpatialIndex::RTree::RTree::containsWhatQuery (const IShape & query, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 500 of file RTree.cc.
References SpatialIndex::IShape::containsShape(), SpatialIndex::IShape::getDimension(), SpatialIndex::IShape::intersectsShape(), SpatialIndex::IVisitor::visitData(), and SpatialIndex::IVisitor::visitNode().
deleteData()
bool SpatialIndex::RTree::RTree::deleteData (const IShape & shape, id_type id) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 424 of file RTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), and SpatialIndex::IShape::getMBR().
flush()
void SpatialIndex::RTree::RTree::flush () virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 846 of file RTree.cc.
References Tools::PointerPool< X >::acquire(), Tools::Variant::blVal, SpatialIndex::RTree::ContainmentQuery, SpatialIndex::IShape::containsShape(), Tools::Variant::dblVal, SpatialIndex::IStorageManager::deleteByteArray(), SpatialIndex::RTree::Leaf::deleteData(), Tools::PoolPointer< X >::get(), SpatialIndex::Region::getDimension(), SpatialIndex::Region::getIntersectingRegion(), Tools::PropertySet::getProperty(), Index, SpatialIndex::Region::intersectsRegion(), SpatialIndex::IShape::intersectsShape(), Leaf, SpatialIndex::IStorageManager::loadByteArray(), SpatialIndex::RTree::Node::loadFromByteArray(), Tools::Variant::lVal, SpatialIndex::Region::m_dimension, Tools::Variant::m_val, Tools::Variant::m_varType, SpatialIndex::Region::makeInfinite(), SpatialIndex::StorageManager::NewPage, SpatialIndex::RTree::PersistentIndex, SpatialIndex::RTree::PersistentLeaf, Tools::PoolPointer< X >::relinquish(), SpatialIndex::RTree::RV_LINEAR, SpatialIndex::RTree::RV_QUADRATIC, SpatialIndex::RTree::RV_RSTAR, selfJoinQuery(), Tools::PointerPool< X >::setCapacity(), SpatialIndex::IStorageManager::storeByteArray(), SpatialIndex::RTree::Node::storeToByteArray(), Tools::Variant::ulVal, Tools::PoolPointer< X >::unique(), SpatialIndex::IVisitor::visitData(), SpatialIndex::IVisitor::visitNode(), Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_EMPTY, Tools::VT_LONG, Tools::VT_ULONG, and SpatialIndex::InvalidPageException::what().
getIndexProperties()
void SpatialIndex::RTree::RTree::getIndexProperties (Tools::PropertySet & out) const virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 658 of file RTree.cc.
References Tools::Variant::blVal, Tools::Variant::dblVal, Tools::PointerPool< X >::getCapacity(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
getStatistics()
void SpatialIndex::RTree::RTree::getStatistics (IStatistics ** out) const virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 841 of file RTree.cc.
insertData()
void SpatialIndex::RTree::RTree::insertData (uint32_t len, const uint8_t * pData, const IShape & shape, id_type shapeIdentifier) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 404 of file RTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), and SpatialIndex::IShape::getMBR().
internalNodesQuery()
void SpatialIndex::RTree::RTree::internalNodesQuery (const IShape & query, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 436 of file RTree.cc.
References SpatialIndex::IShape::containsShape(), SpatialIndex::IShape::getDimension(), SpatialIndex::RTree::Node::getIdentifier(), IdVisitor::GetResultCount(), IdVisitor::GetResults(), SpatialIndex::IShape::intersectsShape(), and SpatialIndex::IVisitor::visitData().
intersectsWithQuery()
void SpatialIndex::RTree::RTree::intersectsWithQuery (const IShape & query, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 552 of file RTree.cc.
References SpatialIndex::IShape::getDimension(), and SpatialIndex::RTree::IntersectionQuery.
isIndexValid()
bool SpatialIndex::RTree::RTree::isIndexValid () virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 749 of file RTree.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, and SpatialIndex::Region::m_pLow.
nearestNeighborQuery() [1/2]
void SpatialIndex::RTree::RTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v, INearestNeighborComparator & nnc) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 565 of file RTree.cc.
References SpatialIndex::IShape::getDimension(), SpatialIndex::INearestNeighborComparator::getMinimumDistance(), SpatialIndex::IVisitor::visitData(), and SpatialIndex::IVisitor::visitNode().
Referenced by nearestNeighborQuery().
nearestNeighborQuery() [2/2]
void SpatialIndex::RTree::RTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 628 of file RTree.cc.
References SpatialIndex::IShape::getDimension(), and nearestNeighborQuery().
pointLocationQuery()
void SpatialIndex::RTree::RTree::pointLocationQuery (const Point & query, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 558 of file RTree.cc.
References SpatialIndex::RTree::IntersectionQuery, and SpatialIndex::Point::m_dimension.
queryStrategy()
void SpatialIndex::RTree::RTree::queryStrategy (IQueryStrategy & qs) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 646 of file RTree.cc.
References SpatialIndex::IQueryStrategy::getNextEntry().
selfJoinQuery()
void SpatialIndex::RTree::RTree::selfJoinQuery (const IShape & s, IVisitor & v) virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 636 of file RTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), and SpatialIndex::IShape::getMBR().
Referenced by flush().
Friends And Related Function Documentation
BulkLoader
friend class BulkLoader friend
Definition at line 191 of file src/rtree/RTree.h.
Index
friend class Index friend
Definition at line 190 of file src/rtree/RTree.h.
Referenced by flush().
Leaf
friend class Leaf friend
Definition at line 189 of file src/rtree/RTree.h.
Referenced by flush().
Node
friend class Node friend
Definition at line 188 of file src/rtree/RTree.h.
operator<<
std::ostream& operator<< (std::ostream & os, const RTree & t) friend
The documentation for this class was generated from the following files:
src/rtree/RTree.h
RTree.cc