libspatialindex API Reference: SpatialIndex::MVRTree::Node Class Reference
SpatialIndex::MVRTree::Node Class Reference abstract
#include <Node.h>
Public Member Functions
~Node () override
IObject * clone () override
uint32_t getByteArraySize () override
void loadFromByteArray (const uint8_t *data) override
void storeToByteArray (uint8_t **data, uint32_t &len) override
id_type getIdentifier () const override
void getShape (IShape **out) const override
uint32_t getChildrenCount () const override
id_type getChildIdentifier (uint32_t index) const override
void getChildShape (uint32_t index, IShape **out) const override
void getChildData (uint32_t index, uint32_t &length, uint8_t **data) const override
uint32_t getLevel () const override
bool isIndex () const override
bool isLeaf () const override
Public Member Functions inherited from SpatialIndex::INode
~INode () override=default
Public Member Functions inherited from SpatialIndex::IEntry
~IEntry () override=default
Public Member Functions inherited from Tools::IObject
virtual ~IObject ()=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Friends
class MVRTree
class Leaf
class Index
class Tools::PointerPool< Node >
Detailed Description
Definition at line 44 of file mvrtree/Node.h.
Constructor & Destructor Documentation
~Node()
Node::~Node () override
Definition at line 284 of file mvrtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::Region::combineRegion(), SpatialIndex::TimeRegion::combineRegionInTime(), SpatialIndex::Region::containsShape(), Tools::PoolPointer< X >::get(), SpatialIndex::Region::getArea(), SpatialIndex::Region::getCombinedRegion(), SpatialIndex::Region::getIntersectingArea(), SpatialIndex::Region::getMargin(), Index::index(), Index, SpatialIndex::Region::intersectsShape(), Leaf, SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::TimeRegion::m_startTime, SpatialIndex::MVRTree::RV_LINEAR, SpatialIndex::MVRTree::RV_QUADRATIC, SpatialIndex::MVRTree::RV_RSTAR, and SpatialIndex::Region::touchesShape().
Member Function Documentation
clone()
Tools::IObject * Node::clone () override virtual
Implements Tools::IObject.
Definition at line 45 of file mvrtree/Node.cc.
getByteArraySize()
uint32_t Node::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 53 of file mvrtree/Node.cc.
Referenced by storeToByteArray().
getChildData()
void Node::getChildData (uint32_t index, uint32_t & length, uint8_t ** data) const override virtual
Implements SpatialIndex::INode.
Definition at line 216 of file mvrtree/Node.cc.
References Index::index().
getChildIdentifier()
SpatialIndex::id_type Node::getChildIdentifier (uint32_t index) const override virtual
Implements SpatialIndex::INode.
Definition at line 201 of file mvrtree/Node.cc.
References Index::index().
getChildrenCount()
uint32_t Node::getChildrenCount () const override virtual
Implements SpatialIndex::INode.
Definition at line 196 of file mvrtree/Node.cc.
getChildShape()
void Node::getChildShape (uint32_t index, IShape ** out) const override virtual
Implements SpatialIndex::INode.
Definition at line 208 of file mvrtree/Node.cc.
getIdentifier()
SpatialIndex::id_type Node::getIdentifier () const override virtual
Implements SpatialIndex::IEntry.
Definition at line 183 of file mvrtree/Node.cc.
getLevel()
uint32_t Node::getLevel () const override virtual
Implements SpatialIndex::INode.
Definition at line 231 of file mvrtree/Node.cc.
getShape()
void Node::getShape (IShape ** out) const override virtual
Implements SpatialIndex::IEntry.
Definition at line 188 of file mvrtree/Node.cc.
isIndex()
bool Node::isIndex () const override virtual
Implements SpatialIndex::INode.
Definition at line 241 of file mvrtree/Node.cc.
References SpatialIndex::TimeRegion::makeInfinite().
isLeaf()
bool Node::isLeaf () const override virtual
Implements SpatialIndex::INode.
Definition at line 236 of file mvrtree/Node.cc.
loadFromByteArray()
void Node::loadFromByteArray (const uint8_t * data) override virtual
Implements Tools::ISerializable.
Definition at line 66 of file mvrtree/Node.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, and SpatialIndex::TimeRegion::m_startTime.
Referenced by SpatialIndex::MVRTree::MVRTree::flush().
storeToByteArray()
void Node::storeToByteArray (uint8_t ** data, uint32_t & len) override virtual
Implements Tools::ISerializable.
Definition at line 124 of file mvrtree/Node.cc.
References getByteArraySize(), SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::TimeRegion::m_startTime, SpatialIndex::MVRTree::PersistentIndex, and SpatialIndex::MVRTree::PersistentLeaf.
Referenced by SpatialIndex::MVRTree::MVRTree::flush().
Friends And Related Function Documentation
Index
friend class Index friend
Definition at line 188 of file mvrtree/Node.h.
Referenced by ~Node().
Leaf
friend class Leaf friend
Definition at line 187 of file mvrtree/Node.h.
Referenced by ~Node().
MVRTree
friend class MVRTree friend
Definition at line 186 of file mvrtree/Node.h.
Tools::PointerPool< Node >
friend class Tools::PointerPool< Node > friend
Definition at line 189 of file mvrtree/Node.h.
The documentation for this class was generated from the following files:
mvrtree/Node.h
mvrtree/Node.cc