libspatialindex API Reference: BoundsQuery Class Reference
BoundsQuery Class Reference
#include <BoundsQuery.h>
Public Member Functions
BoundsQuery ()
~BoundsQuery ()
void getNextEntry (const SpatialIndex::IEntry &entry, SpatialIndex::id_type &nextEntry, bool &hasNext)
SpatialIndex::Region * GetBounds () const
Public Member Functions inherited from SpatialIndex::IQueryStrategy
virtual ~IQueryStrategy ()=default
Detailed Description
Definition at line 33 of file BoundsQuery.h.
Constructor & Destructor Documentation
BoundsQuery()
BoundsQuery::BoundsQuery ()
Definition at line 31 of file BoundsQuery.cc.
~BoundsQuery()
BoundsQuery::~BoundsQuery () inline
Definition at line 41 of file BoundsQuery.h.
References SpatialIndex::IQueryStrategy::getNextEntry().
Member Function Documentation
GetBounds()
SpatialIndex::Region* BoundsQuery::GetBounds () const inline
Definition at line 46 of file BoundsQuery.h.
Referenced by Index_GetBounds().
getNextEntry()
void BoundsQuery::getNextEntry (const SpatialIndex::IEntry & entry, SpatialIndex::id_type & nextEntry, bool & hasNext) virtual
Implements SpatialIndex::IQueryStrategy.
Definition at line 36 of file BoundsQuery.cc.
References SpatialIndex::IShape::getMBR(), and SpatialIndex::IEntry::getShape().
The documentation for this class was generated from the following files:
BoundsQuery.h
BoundsQuery.cc