libspatialindex API Reference: Tools::IInterval Class Reference
Tools::IInterval Class Reference abstract
#include <Tools.h>
Public Member Functions
virtual ~IInterval ()=default
virtual double getLowerBound () const =0
virtual double getUpperBound () const =0
virtual void setBounds (double, double)=0
virtual bool intersectsInterval (const IInterval &) const =0
virtual bool intersectsInterval (IntervalType type, const double start, const double end) const =0
virtual bool containsInterval (const IInterval &) const =0
virtual IntervalType getIntervalType () const =0
Detailed Description
Definition at line 194 of file Tools.h.
Constructor & Destructor Documentation
~IInterval()
virtual Tools::IInterval::~IInterval () virtual default
Member Function Documentation
containsInterval()
virtual bool Tools::IInterval::containsInterval (const IInterval &) const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
getIntervalType()
virtual IntervalType Tools::IInterval::getIntervalType () const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
Referenced by Tools::Interval::containsInterval(), Tools::Interval::intersectsInterval(), and Tools::Interval::operator=().
getLowerBound()
virtual double Tools::IInterval::getLowerBound () const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
Referenced by Tools::Interval::containsInterval(), SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::MVRTree::MVRTree::deleteData(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::MVRTree::MVRTree::insertData(), Tools::Interval::intersectsInterval(), SpatialIndex::TimePoint::operator=(), SpatialIndex::TimeRegion::operator=(), and Tools::Interval::operator=().
getUpperBound()
virtual double Tools::IInterval::getUpperBound () const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
Referenced by Tools::Interval::containsInterval(), SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::MVRTree::MVRTree::deleteData(), Tools::Interval::intersectsInterval(), SpatialIndex::TimePoint::operator=(), SpatialIndex::TimeRegion::operator=(), and Tools::Interval::operator=().
intersectsInterval() [1/2]
virtual bool Tools::IInterval::intersectsInterval (const IInterval &) const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
Referenced by SpatialIndex::MVRTree::MVRTree::flush().
intersectsInterval() [2/2]
virtual bool Tools::IInterval::intersectsInterval (IntervalType type, const double start, const double end) const pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
setBounds()
virtual void Tools::IInterval::setBounds (double , double) pure virtual
Implemented in Tools::Interval, SpatialIndex::TimeRegion, and SpatialIndex::TimePoint.
The documentation for this class was generated from the following file:
Tools.h