libspatialindex API Reference: SpatialIndex::IQueryStrategy Class Reference
SpatialIndex::IQueryStrategy Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual void getNextEntry (const IEntry &previouslyFetched, id_type &nextEntryToFetch, bool &bFetchNextEntry)=0
virtual ~IQueryStrategy ()=default
Detailed Description
Definition at line 174 of file SpatialIndex.h.
Constructor & Destructor Documentation
~IQueryStrategy()
virtual SpatialIndex::IQueryStrategy::~IQueryStrategy () virtual default
Member Function Documentation
getNextEntry()
virtual void SpatialIndex::IQueryStrategy::getNextEntry (const IEntry & previouslyFetched, id_type & nextEntryToFetch, bool & bFetchNextEntry) pure virtual
Implemented in LeafQuery, and BoundsQuery.
Referenced by SpatialIndex::TPRTree::TPRTree::queryStrategy(), SpatialIndex::RTree::RTree::queryStrategy(), SpatialIndex::MVRTree::MVRTree::queryStrategy(), BoundsQuery::~BoundsQuery(), and LeafQuery::~LeafQuery().
The documentation for this class was generated from the following file:
SpatialIndex.h