libspatialindex API Reference: SpatialIndex::IShape Class Reference
SpatialIndex::IShape Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual bool intersectsShape (const IShape &in) const =0
virtual bool containsShape (const IShape &in) const =0
virtual bool touchesShape (const IShape &in) const =0
virtual void getCenter (Point &out) const =0
virtual uint32_t getDimension () const =0
virtual void getMBR (Region &out) const =0
virtual double getArea () const =0
virtual double getMinimumDistance (const IShape &in) const =0
~IShape () override=default
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
virtual uint32_t getByteArraySize ()=0
virtual void loadFromByteArray (const uint8_t *data)=0
virtual void storeToByteArray (uint8_t **data, uint32_t &length)=0
Detailed Description
Definition at line 67 of file SpatialIndex.h.
Constructor & Destructor Documentation
~IShape()
SpatialIndex::IShape::~IShape () override default
Member Function Documentation
containsShape()
virtual bool SpatialIndex::IShape::containsShape (const IShape & in) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
Referenced by SpatialIndex::RTree::RTree::containsWhatQuery(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), and SpatialIndex::RTree::RTree::internalNodesQuery().
getArea()
virtual double SpatialIndex::IShape::getArea () const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
getCenter()
virtual void SpatialIndex::IShape::getCenter (Point & out) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
getDimension()
virtual uint32_t SpatialIndex::IShape::getDimension () const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
Referenced by SpatialIndex::TPRTree::TPRTree::containsWhatQuery(), SpatialIndex::RTree::RTree::containsWhatQuery(), SpatialIndex::MVRTree::MVRTree::containsWhatQuery(), SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::RTree::RTree::deleteData(), SpatialIndex::MVRTree::MVRTree::deleteData(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::RTree::RTree::insertData(), SpatialIndex::MVRTree::MVRTree::insertData(), SpatialIndex::RTree::RTree::internalNodesQuery(), SpatialIndex::TPRTree::TPRTree::intersectsWithQuery(), SpatialIndex::RTree::RTree::intersectsWithQuery(), SpatialIndex::MVRTree::MVRTree::intersectsWithQuery(), SpatialIndex::TPRTree::TPRTree::nearestNeighborQuery(), SpatialIndex::RTree::RTree::nearestNeighborQuery(), SpatialIndex::MVRTree::MVRTree::nearestNeighborQuery(), and SpatialIndex::RTree::RTree::selfJoinQuery().
getMBR()
virtual void SpatialIndex::IShape::getMBR (Region & out) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
Referenced by SpatialIndex::TPRTree::TPRTree::deleteData(), SpatialIndex::RTree::RTree::deleteData(), SpatialIndex::MVRTree::MVRTree::deleteData(), BoundsQuery::getNextEntry(), IndexItem_GetBounds(), SpatialIndex::TPRTree::TPRTree::insertData(), SpatialIndex::RTree::RTree::insertData(), SpatialIndex::MVRTree::MVRTree::insertData(), and SpatialIndex::RTree::RTree::selfJoinQuery().
getMinimumDistance()
virtual double SpatialIndex::IShape::getMinimumDistance (const IShape & in) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
intersectsShape()
virtual bool SpatialIndex::IShape::intersectsShape (const IShape & in) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
Referenced by SpatialIndex::RTree::RTree::containsWhatQuery(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), and SpatialIndex::RTree::RTree::internalNodesQuery().
touchesShape()
virtual bool SpatialIndex::IShape::touchesShape (const IShape & in) const pure virtual
Implemented in SpatialIndex::Point, SpatialIndex::LineSegment, and SpatialIndex::Region.
The documentation for this class was generated from the following file:
SpatialIndex.h