libspatialindex API Reference: LeafQuery Class Reference
LeafQuery Class Reference
#include <LeafQuery.h>
Public Member Functions
LeafQuery ()
~LeafQuery ()
void getNextEntry (const SpatialIndex::IEntry &entry, SpatialIndex::id_type &nextEntry, bool &hasNext)
std::vector< LeafQueryResult > const & GetResults () const
Public Member Functions inherited from SpatialIndex::IQueryStrategy
virtual ~IQueryStrategy ()=default
Detailed Description
Definition at line 35 of file LeafQuery.h.
Constructor & Destructor Documentation
LeafQuery()
LeafQuery::LeafQuery ()
Definition at line 31 of file LeafQuery.cc.
~LeafQuery()
LeafQuery::~LeafQuery () inline
Definition at line 43 of file LeafQuery.h.
References SpatialIndex::IQueryStrategy::getNextEntry().
Member Function Documentation
getNextEntry()
void LeafQuery::getNextEntry (const SpatialIndex::IEntry & entry, SpatialIndex::id_type & nextEntry, bool & hasNext) virtual
Implements SpatialIndex::IQueryStrategy.
Definition at line 55 of file LeafQuery.cc.
References get_results(), SpatialIndex::INode::getChildIdentifier(), SpatialIndex::INode::getChildrenCount(), SpatialIndex::INode::getLevel(), and SpatialIndex::INode::isLeaf().
GetResults()
std::vector<LeafQueryResult> const& LeafQuery::GetResults () const inline
Definition at line 47 of file LeafQuery.h.
Referenced by Index_GetLeaves().
The documentation for this class was generated from the following files:
LeafQuery.h
LeafQuery.cc