libspatialindex API Reference: Tools::PropertySet Class Reference
Tools::PropertySet Class Reference
#include <Tools.h>
Public Member Functions
PropertySet ()
PropertySet (const uint8_t *data)
~PropertySet () override
Variant getProperty (std::string property) const
void setProperty (std::string property, Variant const &v)
void removeProperty (std::string property)
uint32_t getByteArraySize () override
void loadFromByteArray (const uint8_t *data) override
void storeToByteArray (uint8_t **data, uint32_t &length) override
Public Member Functions inherited from Tools::ISerializable
virtual ~ISerializable ()=default
Friends
SIDX_DLL std::ostream & Tools::operator<< (std::ostream &os, const Tools::PropertySet &p)
Detailed Description
Definition at line 301 of file Tools.h.
Constructor & Destructor Documentation
PropertySet() [1/2]
Tools::PropertySet::PropertySet () default
Referenced by PropertySet().
PropertySet() [2/2]
Tools::PropertySet::PropertySet (const uint8_t * data)
Definition at line 109 of file Tools.cc.
References PropertySet(), and ~PropertySet().
~PropertySet()
Tools::PropertySet::~PropertySet () override default
Referenced by PropertySet().
Member Function Documentation
getByteArraySize()
uint32_t Tools::PropertySet::getByteArraySize () override virtual
Implements Tools::ISerializable.
Definition at line 214 of file Tools.cc.
References Tools::NotSupportedException::NotSupportedException(), Tools::VT_BOOL, Tools::VT_BYTE, Tools::VT_CHAR, Tools::VT_DOUBLE, Tools::VT_FLOAT, Tools::VT_LONG, Tools::VT_LONGLONG, Tools::VT_SHORT, Tools::VT_ULONG, Tools::VT_ULONGLONG, and Tools::VT_USHORT.
getProperty()
Tools::Variant Tools::PropertySet::getProperty (std::string property) const
Definition at line 346 of file Tools.cc.
Referenced by SpatialIndex::StorageManager::Buffer::Buffer(), CheckFilesExists(), SpatialIndex::RTree::createAndBulkLoadNewRTree(), SpatialIndex::MVRTree::createNewMVRTree(), SpatialIndex::RTree::createNewRTree(), SpatialIndex::TPRTree::createNewTPRTree(), SpatialIndex::StorageManager::CustomStorageManager::CustomStorageManager(), SpatialIndex::StorageManager::DiskStorageManager::DiskStorageManager(), SpatialIndex::TPRTree::TPRTree::flush(), SpatialIndex::RTree::RTree::flush(), SpatialIndex::MVRTree::MVRTree::flush(), Index_GetLeaves(), Index_GetProperties(), IndexProperty_GetBufferingCapacity(), IndexProperty_GetCustomStorageCallbacks(), IndexProperty_GetCustomStorageCallbacksSize(), IndexProperty_GetDimension(), IndexProperty_GetEnsureTightMBRs(), IndexProperty_GetFileName(), IndexProperty_GetFileNameExtensionDat(), IndexProperty_GetFileNameExtensionIdx(), IndexProperty_GetFillFactor(), IndexProperty_GetIndexCapacity(), IndexProperty_GetIndexID(), IndexProperty_GetIndexPoolCapacity(), IndexProperty_GetIndexStorage(), IndexProperty_GetIndexType(), IndexProperty_GetIndexVariant(), IndexProperty_GetLeafCapacity(), IndexProperty_GetLeafPoolCapacity(), IndexProperty_GetNearMinimumOverlapFactor(), IndexProperty_GetOverwrite(), IndexProperty_GetPagesize(), IndexProperty_GetPointPoolCapacity(), IndexProperty_GetRegionPoolCapacity(), IndexProperty_GetReinsertFactor(), IndexProperty_GetResultSetLimit(), IndexProperty_GetSplitDistributionFactor(), IndexProperty_GetTPRHorizon(), IndexProperty_GetWriteThrough(), IndexProperty_SetCustomStorageCallbacks(), SpatialIndex::MVRTree::MVRTree::MVRTree(), SpatialIndex::RTree::RTree::RTree(), and SpatialIndex::TPRTree::TPRTree::TPRTree().
loadFromByteArray()
void Tools::PropertySet::loadFromByteArray (const uint8_t * data) override virtual
Implements Tools::ISerializable.
Definition at line 119 of file Tools.cc.
References Tools::Variant::blVal, Tools::Variant::bVal, Tools::Variant::cVal, Tools::Variant::dblVal, Tools::Variant::fltVal, Tools::Variant::iVal, Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::Variant::uiVal, Tools::Variant::ullVal, Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_BYTE, Tools::VT_CHAR, Tools::VT_DOUBLE, Tools::VT_FLOAT, Tools::VT_LONG, Tools::VT_LONGLONG, Tools::VT_SHORT, Tools::VT_ULONG, Tools::VT_ULONGLONG, and Tools::VT_USHORT.
removeProperty()
void Tools::PropertySet::removeProperty (std::string property)
Definition at line 366 of file Tools.cc.
References Tools::Interval::Interval().
setProperty()
void Tools::PropertySet::setProperty (std::string property, Variant const & v)
Definition at line 354 of file Tools.cc.
Referenced by SpatialIndex::StorageManager::createNewDiskStorageManager(), SpatialIndex::MVRTree::createNewMVRTree(), SpatialIndex::StorageManager::createNewRandomEvictionsBuffer(), SpatialIndex::RTree::createNewRTree(), SpatialIndex::TPRTree::createNewTPRTree(), GetDefaults(), SpatialIndex::TPRTree::TPRTree::getIndexProperties(), SpatialIndex::RTree::RTree::getIndexProperties(), SpatialIndex::MVRTree::MVRTree::getIndexProperties(), Index_GetProperties(), IndexProperty_SetBufferingCapacity(), IndexProperty_SetCustomStorageCallbacks(), IndexProperty_SetCustomStorageCallbacksSize(), IndexProperty_SetDimension(), IndexProperty_SetEnsureTightMBRs(), IndexProperty_SetFileName(), IndexProperty_SetFileNameExtensionDat(), IndexProperty_SetFileNameExtensionIdx(), IndexProperty_SetFillFactor(), IndexProperty_SetIndexCapacity(), IndexProperty_SetIndexID(), IndexProperty_SetIndexPoolCapacity(), IndexProperty_SetIndexStorage(), IndexProperty_SetIndexType(), IndexProperty_SetIndexVariant(), IndexProperty_SetLeafCapacity(), IndexProperty_SetLeafPoolCapacity(), IndexProperty_SetNearMinimumOverlapFactor(), IndexProperty_SetOverwrite(), IndexProperty_SetPagesize(), IndexProperty_SetPointPoolCapacity(), IndexProperty_SetRegionPoolCapacity(), IndexProperty_SetReinsertFactor(), IndexProperty_SetResultSetLimit(), IndexProperty_SetSplitDistributionFactor(), IndexProperty_SetTPRHorizon(), IndexProperty_SetWriteThrough(), SpatialIndex::StorageManager::loadDiskStorageManager(), SpatialIndex::MVRTree::loadMVRTree(), SpatialIndex::RTree::loadRTree(), SpatialIndex::TPRTree::loadTPRTree(), SpatialIndex::MVRTree::MVRTree::MVRTree(), SpatialIndex::RTree::RTree::RTree(), and SpatialIndex::TPRTree::TPRTree::TPRTree().
storeToByteArray()
void Tools::PropertySet::storeToByteArray (uint8_t ** data, uint32_t & length) override virtual
Implements Tools::ISerializable.
Definition at line 266 of file Tools.cc.
References Tools::NotSupportedException::NotSupportedException(), Tools::VT_BOOL, Tools::VT_BYTE, Tools::VT_CHAR, Tools::VT_DOUBLE, Tools::VT_FLOAT, Tools::VT_LONG, Tools::VT_LONGLONG, Tools::VT_SHORT, Tools::VT_ULONG, Tools::VT_ULONGLONG, and Tools::VT_USHORT.
Friends And Related Function Documentation
Tools::operator<<
SIDX_DLL std::ostream& Tools::operator<< (std::ostream & os, const Tools::PropertySet & p) friend
The documentation for this class was generated from the following files:
Tools.h
Tools.cc