libspatialindex API Reference: Tools::TemporaryFile Class Reference
Tools::TemporaryFile Class Reference
#include <Tools.h>
Public Member Functions
TemporaryFile ()
virtual ~TemporaryFile ()
void rewindForReading ()
void rewindForWriting ()
bool eof ()
std::string getFileName () const
uint8_t readUInt8 ()
uint16_t readUInt16 ()
uint32_t readUInt32 ()
uint64_t readUInt64 ()
float readFloat ()
double readDouble ()
std::string readString ()
void readBytes (uint32_t u32Len, uint8_t **pData)
void write (uint8_t i)
void write (uint16_t i)
void write (uint32_t i)
void write (uint64_t i)
void write (float i)
void write (double i)
void write (const std::string &s)
void write (uint32_t u32Len, uint8_t *pData)
Detailed Description
Definition at line 468 of file Tools.h.
Constructor & Destructor Documentation
TemporaryFile()
Tools::TemporaryFile::TemporaryFile ()
Definition at line 1055 of file Tools.cc.
References Tools::CREATE.
~TemporaryFile()
Tools::TemporaryFile::~TemporaryFile () virtual
Definition at line 1091 of file Tools.cc.
Member Function Documentation
eof()
bool Tools::TemporaryFile::eof ()
Definition at line 1126 of file Tools.cc.
getFileName()
std::string Tools::TemporaryFile::getFileName () const
Definition at line 1131 of file Tools.cc.
readBytes()
void Tools::TemporaryFile::readBytes (uint32_t u32Len, uint8_t ** pData)
Definition at line 1199 of file Tools.cc.
References Tools::BufferedFileReader::readBytes().
Referenced by SpatialIndex::RTree::ExternalSorter::Record::loadFromFile().
readDouble()
double Tools::TemporaryFile::readDouble ()
Definition at line 1181 of file Tools.cc.
References Tools::BufferedFileReader::readDouble().
Referenced by SpatialIndex::RTree::ExternalSorter::Record::loadFromFile().
readFloat()
float Tools::TemporaryFile::readFloat ()
Definition at line 1172 of file Tools.cc.
References Tools::BufferedFileReader::readFloat().
readString()
std::string Tools::TemporaryFile::readString ()
Definition at line 1190 of file Tools.cc.
References Tools::BufferedFileReader::readString().
readUInt16()
uint16_t Tools::TemporaryFile::readUInt16 ()
Definition at line 1145 of file Tools.cc.
References Tools::BufferedFileReader::readUInt16().
readUInt32()
uint32_t Tools::TemporaryFile::readUInt32 ()
Definition at line 1154 of file Tools.cc.
References Tools::BufferedFileReader::readUInt32().
Referenced by SpatialIndex::RTree::ExternalSorter::Record::loadFromFile().
readUInt64()
uint64_t Tools::TemporaryFile::readUInt64 ()
Definition at line 1163 of file Tools.cc.
References Tools::BufferedFileReader::readUInt64().
Referenced by SpatialIndex::RTree::ExternalSorter::Record::loadFromFile().
readUInt8()
uint8_t Tools::TemporaryFile::readUInt8 ()
Definition at line 1136 of file Tools.cc.
References Tools::BufferedFileReader::readUInt8().
rewindForReading()
void Tools::TemporaryFile::rewindForReading ()
Definition at line 1102 of file Tools.cc.
References Tools::BufferedFileReader::rewind().
rewindForWriting()
void Tools::TemporaryFile::rewindForWriting ()
Definition at line 1114 of file Tools.cc.
References Tools::BufferedFileWriter::rewind().
write() [1/8]
void Tools::TemporaryFile::write (uint8_t i)
Definition at line 1208 of file Tools.cc.
References Tools::BufferedFileWriter::write().
Referenced by SpatialIndex::RTree::ExternalSorter::Record::storeToFile().
write() [2/8]
void Tools::TemporaryFile::write (uint16_t i)
Definition at line 1217 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [3/8]
void Tools::TemporaryFile::write (uint32_t i)
Definition at line 1226 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [4/8]
void Tools::TemporaryFile::write (uint64_t i)
Definition at line 1235 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [5/8]
void Tools::TemporaryFile::write (float i)
Definition at line 1244 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [6/8]
void Tools::TemporaryFile::write (double i)
Definition at line 1253 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [7/8]
void Tools::TemporaryFile::write (const std::string & s)
Definition at line 1262 of file Tools.cc.
References Tools::BufferedFileWriter::write().
write() [8/8]
void Tools::TemporaryFile::write (uint32_t u32Len, uint8_t * pData)
Definition at line 1271 of file Tools.cc.
References Tools::BufferedFileWriter::write().
The documentation for this class was generated from the following files:
Tools.h
Tools.cc