libspatialindex API Reference: SpatialIndex::ISpatialIndex Class Reference
SpatialIndex::ISpatialIndex Class Reference abstract
#include <SpatialIndex.h>
Public Member Functions
virtual void insertData (uint32_t len, const uint8_t *pData, const IShape &shape, id_type shapeIdentifier)=0
virtual bool deleteData (const IShape &shape, id_type shapeIdentifier)=0
virtual void internalNodesQuery (const IShape &query, IVisitor &v)=0
virtual void containsWhatQuery (const IShape &query, IVisitor &v)=0
virtual void intersectsWithQuery (const IShape &query, IVisitor &v)=0
virtual void pointLocationQuery (const Point &query, IVisitor &v)=0
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v, INearestNeighborComparator &nnc)=0
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v)=0
virtual void selfJoinQuery (const IShape &s, IVisitor &v)=0
virtual void queryStrategy (IQueryStrategy &qs)=0
virtual void getIndexProperties (Tools::PropertySet &out) const =0
virtual void addCommand (ICommand *in, CommandType ct)=0
virtual bool isIndexValid ()=0
virtual void getStatistics (IStatistics **out) const =0
virtual void flush ()=0
virtual ~ISpatialIndex ()=default
Detailed Description
Definition at line 191 of file SpatialIndex.h.
Constructor & Destructor Documentation
~ISpatialIndex()
virtual SpatialIndex::ISpatialIndex::~ISpatialIndex () virtual default
Member Function Documentation
addCommand()
virtual void SpatialIndex::ISpatialIndex::addCommand (ICommand * in, CommandType ct) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
containsWhatQuery()
virtual void SpatialIndex::ISpatialIndex::containsWhatQuery (const IShape & query, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_Contains_count(), Index_Contains_id(), and Index_Contains_obj().
deleteData()
virtual bool SpatialIndex::ISpatialIndex::deleteData (const IShape & shape, id_type shapeIdentifier) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_DeleteData(), Index_DeleteMVRData(), and Index_DeleteTPData().
flush()
virtual void SpatialIndex::ISpatialIndex::flush () pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
getIndexProperties()
virtual void SpatialIndex::ISpatialIndex::getIndexProperties (Tools::PropertySet & out) const pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_GetLeaves(), and Index_GetProperties().
getStatistics()
virtual void SpatialIndex::ISpatialIndex::getStatistics (IStatistics ** out) const pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
insertData()
virtual void SpatialIndex::ISpatialIndex::insertData (uint32_t len, const uint8_t * pData, const IShape & shape, id_type shapeIdentifier) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_InsertData(), Index_InsertMVRData(), and Index_InsertTPData().
internalNodesQuery()
virtual void SpatialIndex::ISpatialIndex::internalNodesQuery (const IShape & query, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_Intersects_internal().
intersectsWithQuery()
virtual void SpatialIndex::ISpatialIndex::intersectsWithQuery (const IShape & query, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_Intersects_count(), Index_Intersects_id(), Index_Intersects_obj(), Index_MVRIntersects_count(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_SegmentIntersects_count(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_TPIntersects_count(), Index_TPIntersects_id(), and Index_TPIntersects_obj().
isIndexValid()
virtual bool SpatialIndex::ISpatialIndex::isIndexValid () pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_IsValid().
nearestNeighborQuery() [1/2]
virtual void SpatialIndex::ISpatialIndex::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v, INearestNeighborComparator & nnc) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_TPNearestNeighbors_id(), and Index_TPNearestNeighbors_obj().
nearestNeighborQuery() [2/2]
virtual void SpatialIndex::ISpatialIndex::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
pointLocationQuery()
virtual void SpatialIndex::ISpatialIndex::pointLocationQuery (const Point & query, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
queryStrategy()
virtual void SpatialIndex::ISpatialIndex::queryStrategy (IQueryStrategy & qs) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
Referenced by Index_GetBounds(), and Index_GetLeaves().
selfJoinQuery()
virtual void SpatialIndex::ISpatialIndex::selfJoinQuery (const IShape & s, IVisitor & v) pure virtual
Implemented in SpatialIndex::MVRTree::MVRTree, SpatialIndex::RTree::RTree, and SpatialIndex::TPRTree::TPRTree.
The documentation for this class was generated from the following file:
SpatialIndex.h