libspatialindex API Reference: SpatialIndex::TPRTree::TPRTree Class Reference
SpatialIndex::TPRTree::TPRTree Class Reference
#include <TPRTree.h>
Public Member Functions
TPRTree (IStorageManager &, Tools::PropertySet &)
~TPRTree () override
virtual void insertData (uint32_t len, const uint8_t *pData, const IShape &shape, id_type shapeIdentifier) override
virtual bool deleteData (const IShape &shape, id_type id) override
virtual void internalNodesQuery (const IShape &query, IVisitor &v) override
virtual void containsWhatQuery (const IShape &query, IVisitor &v) override
virtual void intersectsWithQuery (const IShape &query, IVisitor &v) override
virtual void pointLocationQuery (const Point &query, IVisitor &v) override
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v, INearestNeighborComparator &) override
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v) override
virtual void selfJoinQuery (const IShape &s, IVisitor &v) override
virtual void queryStrategy (IQueryStrategy &qs) override
virtual void getIndexProperties (Tools::PropertySet &out) const override
virtual void addCommand (ICommand *pCommand, CommandType ct) override
virtual bool isIndexValid () override
virtual void getStatistics (IStatistics **out) const override
virtual void flush () override
Public Member Functions inherited from SpatialIndex::ISpatialIndex
virtual ~ISpatialIndex ()=default
Friends
class Node
class Leaf
class Index
std::ostream & operator<< (std::ostream &os, const TPRTree &t)
Detailed Description
Definition at line 39 of file src/tprtree/TPRTree.h.
Constructor & Destructor Documentation
TPRTree()
SpatialIndex::TPRTree::TPRTree::TPRTree (IStorageManager & sm, Tools::PropertySet & ps)
Definition at line 204 of file TPRTree.cc.
References Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::VT_EMPTY, Tools::VT_LONG, and Tools::VT_LONGLONG.
~TPRTree()
SpatialIndex::TPRTree::TPRTree::~TPRTree () override
Definition at line 243 of file TPRTree.cc.
Member Function Documentation
addCommand()
void SpatialIndex::TPRTree::TPRTree::addCommand (ICommand * pCommand, CommandType ct) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 456 of file TPRTree.cc.
References SpatialIndex::CT_NODEDELETE, SpatialIndex::CT_NODEREAD, and SpatialIndex::CT_NODEWRITE.
containsWhatQuery()
void SpatialIndex::TPRTree::TPRTree::containsWhatQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 328 of file TPRTree.cc.
References SpatialIndex::TPRTree::ContainmentQuery, and SpatialIndex::IShape::getDimension().
deleteData()
bool SpatialIndex::TPRTree::TPRTree::deleteData (const IShape & shape, id_type id) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 293 of file TPRTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), Tools::IInterval::getLowerBound(), SpatialIndex::IShape::getMBR(), Tools::IInterval::getUpperBound(), SpatialIndex::IEvolvingShape::getVMBR(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::MovingRegion::makeDimension().
flush()
void SpatialIndex::TPRTree::TPRTree::flush () override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 581 of file TPRTree.cc.
References Tools::PointerPool< X >::acquire(), Tools::Variant::blVal, SpatialIndex::TPRTree::ContainmentQuery, SpatialIndex::MovingRegion::containsRegionInTime(), Tools::Variant::dblVal, SpatialIndex::IStorageManager::deleteByteArray(), Tools::PoolPointer< X >::get(), SpatialIndex::Region::getDimension(), Tools::PropertySet::getProperty(), Index, SpatialIndex::MovingRegion::intersectsRegionInTime(), Leaf, SpatialIndex::IStorageManager::loadByteArray(), SpatialIndex::TPRTree::Node::loadFromByteArray(), Tools::Variant::lVal, SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::TimeRegion::m_startTime, Tools::Variant::m_val, Tools::Variant::m_varType, SpatialIndex::MovingRegion::makeInfinite(), SpatialIndex::StorageManager::NewPage, SpatialIndex::TPRTree::PersistentIndex, SpatialIndex::TPRTree::PersistentLeaf, Tools::PoolPointer< X >::relinquish(), Tools::PointerPool< X >::setCapacity(), SpatialIndex::IStorageManager::storeByteArray(), SpatialIndex::TPRTree::Node::storeToByteArray(), SpatialIndex::TPRTree::TPRV_RSTAR, Tools::Variant::ulVal, Tools::PoolPointer< X >::unique(), SpatialIndex::IVisitor::visitData(), SpatialIndex::IVisitor::visitNode(), Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_EMPTY, Tools::VT_LONG, Tools::VT_ULONG, and SpatialIndex::InvalidPageException::what().
getIndexProperties()
void SpatialIndex::TPRTree::TPRTree::getIndexProperties (Tools::PropertySet & out) const override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 376 of file TPRTree.cc.
References Tools::Variant::blVal, Tools::Variant::dblVal, Tools::PointerPool< X >::getCapacity(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
getStatistics()
void SpatialIndex::TPRTree::TPRTree::getStatistics (IStatistics ** out) const override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 576 of file TPRTree.cc.
insertData()
void SpatialIndex::TPRTree::TPRTree::insertData (uint32_t len, const uint8_t * pData, const IShape & shape, id_type shapeIdentifier) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 252 of file TPRTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), Tools::IInterval::getLowerBound(), SpatialIndex::IShape::getMBR(), SpatialIndex::IEvolvingShape::getVMBR(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::MovingRegion::makeDimension().
internalNodesQuery()
void SpatialIndex::TPRTree::TPRTree::internalNodesQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 323 of file TPRTree.cc.
intersectsWithQuery()
void SpatialIndex::TPRTree::TPRTree::intersectsWithQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 334 of file TPRTree.cc.
References SpatialIndex::IShape::getDimension(), and SpatialIndex::TPRTree::IntersectionQuery.
isIndexValid()
bool SpatialIndex::TPRTree::TPRTree::isIndexValid () override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 472 of file TPRTree.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::MovingRegion::m_pVHigh, SpatialIndex::MovingRegion::m_pVLow, and SpatialIndex::TimeRegion::m_startTime.
nearestNeighborQuery() [1/2]
void SpatialIndex::TPRTree::TPRTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v, INearestNeighborComparator &) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 347 of file TPRTree.cc.
Referenced by nearestNeighborQuery().
nearestNeighborQuery() [2/2]
void SpatialIndex::TPRTree::TPRTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 352 of file TPRTree.cc.
References SpatialIndex::IShape::getDimension(), and nearestNeighborQuery().
pointLocationQuery()
void SpatialIndex::TPRTree::TPRTree::pointLocationQuery (const Point & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 340 of file TPRTree.cc.
References SpatialIndex::TPRTree::IntersectionQuery, and SpatialIndex::Point::m_dimension.
queryStrategy()
void SpatialIndex::TPRTree::TPRTree::queryStrategy (IQueryStrategy & qs) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 364 of file TPRTree.cc.
References SpatialIndex::IQueryStrategy::getNextEntry().
selfJoinQuery()
void SpatialIndex::TPRTree::TPRTree::selfJoinQuery (const IShape & s, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 359 of file TPRTree.cc.
Friends And Related Function Documentation
Index
friend class Index friend
Definition at line 191 of file src/tprtree/TPRTree.h.
Referenced by flush().
Leaf
friend class Leaf friend
Definition at line 190 of file src/tprtree/TPRTree.h.
Referenced by flush().
Node
friend class Node friend
Definition at line 189 of file src/tprtree/TPRTree.h.
operator<<
std::ostream& operator<< (std::ostream & os, const TPRTree & t) friend
The documentation for this class was generated from the following files:
src/tprtree/TPRTree.h
TPRTree.cc