libspatialindex API Reference: SpatialIndex::RTree::BulkLoader Class Reference
SpatialIndex::RTree::BulkLoader Class Reference
#include <BulkLoader.h>
Public Member Functions
void bulkLoadUsingSTR (RTree *pTree, IDataStream &stream, uint32_t bindex, uint32_t bleaf, uint32_t pageSize, uint32_t numberOfPages)
Protected Member Functions
void createLevel (RTree *pTree, Tools::SmartPointer< ExternalSorter > es, uint32_t dimension, uint32_t indexSize, uint32_t leafSize, uint32_t level, Tools::SmartPointer< ExternalSorter > es2, uint32_t pageSize, uint32_t numberOfPages)
Node * createNode (RTree *pTree, std::vector< ExternalSorter::Record * > &e, uint32_t level)
Detailed Description
Definition at line 105 of file BulkLoader.h.
Member Function Documentation
void BulkLoader::bulkLoadUsingSTR (RTree * pTree, IDataStream & stream, uint32_t bindex, uint32_t bleaf, uint32_t pageSize, uint32_t numberOfPages)
Definition at line 322 of file BulkLoader.cc.
References createLevel(), Tools::PoolPointer< X >::get(), SpatialIndex::IDataStream::getNext(), SpatialIndex::RTree::ExternalSorter::getTotalEntries(), Tools::IObjectStream::hasNext(), SpatialIndex::RTree::ExternalSorter::insert(), SpatialIndex::RTree::Data::m_dataLength, SpatialIndex::RTree::Data::m_id, SpatialIndex::RTree::Data::m_pData, SpatialIndex::RTree::Data::m_region, and SpatialIndex::RTree::ExternalSorter::sort().
Referenced by SpatialIndex::RTree::createAndBulkLoadNewRTree().
void BulkLoader::createLevel (RTree * pTree, Tools::SmartPointer< ExternalSorter > es, uint32_t dimension, uint32_t indexSize, uint32_t leafSize, uint32_t level, Tools::SmartPointer< ExternalSorter > es2, uint32_t pageSize, uint32_t numberOfPages) protected
Definition at line 383 of file BulkLoader.cc.
References createNode(), SpatialIndex::RTree::ExternalSorter::getNextRecord(), SpatialIndex::RTree::ExternalSorter::getTotalEntries(), SpatialIndex::RTree::ExternalSorter::insert(), SpatialIndex::RTree::ExternalSorter::Record::m_s, and SpatialIndex::RTree::ExternalSorter::sort().
Referenced by bulkLoadUsingSTR().
Node * BulkLoader::createNode (RTree * pTree, std::vector< ExternalSorter::Record * > & e, uint32_t level) protected
Definition at line 451 of file BulkLoader.cc.
Referenced by createLevel().
The documentation for this class was generated from the following files:
BulkLoader.h
BulkLoader.cc