libspatialindex API Reference: SpatialIndex::MVRTree::MVRTree Class Reference
SpatialIndex::MVRTree::MVRTree Class Reference
#include <MVRTree.h>
Public Member Functions
MVRTree (IStorageManager &, Tools::PropertySet &)
~MVRTree () override
virtual void insertData (uint32_t len, const uint8_t *pData, const IShape &shape, id_type id) override
virtual bool deleteData (const IShape &shape, id_type id) override
virtual void internalNodesQuery (const IShape &query, IVisitor &v) override
virtual void containsWhatQuery (const IShape &query, IVisitor &v) override
virtual void intersectsWithQuery (const IShape &query, IVisitor &v) override
virtual void pointLocationQuery (const Point &query, IVisitor &v) override
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v, INearestNeighborComparator &) override
virtual void nearestNeighborQuery (uint32_t k, const IShape &query, IVisitor &v) override
virtual void selfJoinQuery (const IShape &s, IVisitor &v) override
virtual void queryStrategy (IQueryStrategy &qs) override
virtual void getIndexProperties (Tools::PropertySet &out) const override
virtual void addCommand (ICommand *pCommand, CommandType ct) override
virtual bool isIndexValid () override
virtual void getStatistics (IStatistics **out) const override
virtual void flush () override
Public Member Functions inherited from SpatialIndex::ISpatialIndex
virtual ~ISpatialIndex ()=default
Friends
class Node
class Leaf
class Index
std::ostream & operator<< (std::ostream &os, const MVRTree &t)
Detailed Description
Definition at line 42 of file src/mvrtree/MVRTree.h.
Constructor & Destructor Documentation
MVRTree()
SpatialIndex::MVRTree::MVRTree::MVRTree (IStorageManager & sm, Tools::PropertySet & ps)
Definition at line 200 of file MVRTree.cc.
References Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::VT_EMPTY, Tools::VT_LONG, and Tools::VT_LONGLONG.
~MVRTree()
SpatialIndex::MVRTree::MVRTree::~MVRTree () override
Definition at line 242 of file MVRTree.cc.
Member Function Documentation
addCommand()
void SpatialIndex::MVRTree::MVRTree::addCommand (ICommand * pCommand, CommandType ct) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 449 of file MVRTree.cc.
References SpatialIndex::CT_NODEDELETE, SpatialIndex::CT_NODEREAD, and SpatialIndex::CT_NODEWRITE.
containsWhatQuery()
void SpatialIndex::MVRTree::MVRTree::containsWhatQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 310 of file MVRTree.cc.
References SpatialIndex::MVRTree::ContainmentQuery, and SpatialIndex::IShape::getDimension().
deleteData()
bool SpatialIndex::MVRTree::MVRTree::deleteData (const IShape & shape, id_type id) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 282 of file MVRTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), Tools::IInterval::getLowerBound(), SpatialIndex::IShape::getMBR(), Tools::IInterval::getUpperBound(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::TimeRegion::makeDimension().
flush()
void SpatialIndex::MVRTree::MVRTree::flush () override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 560 of file MVRTree.cc.
References Tools::PointerPool< X >::acquire(), Tools::Variant::blVal, SpatialIndex::MVRTree::ContainmentQuery, SpatialIndex::IShape::containsShape(), Tools::Variant::dblVal, SpatialIndex::IStorageManager::deleteByteArray(), Tools::PoolPointer< X >::get(), SpatialIndex::Region::getDimension(), Tools::PropertySet::getProperty(), Index, SpatialIndex::TimeRegion::intersectsInterval(), Tools::IInterval::intersectsInterval(), SpatialIndex::IShape::intersectsShape(), Tools::IT_RIGHTOPEN, Leaf, SpatialIndex::IStorageManager::loadByteArray(), SpatialIndex::MVRTree::Node::loadFromByteArray(), Tools::Variant::lVal, SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::TimeRegion::m_startTime, Tools::Variant::m_val, Tools::Variant::m_varType, SpatialIndex::TimeRegion::makeInfinite(), SpatialIndex::StorageManager::NewPage, SpatialIndex::MVRTree::PersistentIndex, SpatialIndex::MVRTree::PersistentLeaf, Tools::PoolPointer< X >::relinquish(), SpatialIndex::MVRTree::RV_LINEAR, SpatialIndex::MVRTree::RV_QUADRATIC, SpatialIndex::MVRTree::RV_RSTAR, Tools::PointerPool< X >::setCapacity(), SpatialIndex::IStorageManager::storeByteArray(), SpatialIndex::MVRTree::Node::storeToByteArray(), Tools::Variant::ulVal, Tools::PoolPointer< X >::unique(), SpatialIndex::IVisitor::visitData(), SpatialIndex::IVisitor::visitNode(), Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_EMPTY, Tools::VT_LONG, Tools::VT_ULONG, and SpatialIndex::InvalidPageException::what().
getIndexProperties()
void SpatialIndex::MVRTree::MVRTree::getIndexProperties (Tools::PropertySet & out) const override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 360 of file MVRTree.cc.
References Tools::Variant::blVal, Tools::Variant::dblVal, Tools::PointerPool< X >::getCapacity(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_BOOL, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
getStatistics()
void SpatialIndex::MVRTree::MVRTree::getStatistics (IStatistics ** out) const override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 555 of file MVRTree.cc.
insertData()
void SpatialIndex::MVRTree::MVRTree::insertData (uint32_t len, const uint8_t * pData, const IShape & shape, id_type id) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 251 of file MVRTree.cc.
References Tools::PointerPool< X >::acquire(), SpatialIndex::IShape::getDimension(), Tools::IInterval::getLowerBound(), SpatialIndex::IShape::getMBR(), SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, SpatialIndex::TimeRegion::m_startTime, and SpatialIndex::TimeRegion::makeDimension().
internalNodesQuery()
void SpatialIndex::MVRTree::MVRTree::internalNodesQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 305 of file MVRTree.cc.
intersectsWithQuery()
void SpatialIndex::MVRTree::MVRTree::intersectsWithQuery (const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 316 of file MVRTree.cc.
References SpatialIndex::IShape::getDimension(), and SpatialIndex::MVRTree::IntersectionQuery.
isIndexValid()
bool SpatialIndex::MVRTree::MVRTree::isIndexValid () override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 465 of file MVRTree.cc.
References SpatialIndex::Region::m_dimension, SpatialIndex::TimeRegion::m_endTime, SpatialIndex::Region::m_pHigh, SpatialIndex::Region::m_pLow, and SpatialIndex::TimeRegion::m_startTime.
nearestNeighborQuery() [1/2]
void SpatialIndex::MVRTree::MVRTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v, INearestNeighborComparator &) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 331 of file MVRTree.cc.
Referenced by nearestNeighborQuery().
nearestNeighborQuery() [2/2]
void SpatialIndex::MVRTree::MVRTree::nearestNeighborQuery (uint32_t k, const IShape & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 336 of file MVRTree.cc.
References SpatialIndex::IShape::getDimension(), and nearestNeighborQuery().
pointLocationQuery()
void SpatialIndex::MVRTree::MVRTree::pointLocationQuery (const Point & query, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 322 of file MVRTree.cc.
References SpatialIndex::MVRTree::IntersectionQuery, and SpatialIndex::Point::m_dimension.
queryStrategy()
void SpatialIndex::MVRTree::MVRTree::queryStrategy (IQueryStrategy & qs) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 348 of file MVRTree.cc.
References SpatialIndex::IQueryStrategy::getNextEntry().
selfJoinQuery()
void SpatialIndex::MVRTree::MVRTree::selfJoinQuery (const IShape & s, IVisitor & v) override virtual
Implements SpatialIndex::ISpatialIndex.
Definition at line 343 of file MVRTree.cc.
Friends And Related Function Documentation
Index
friend class Index friend
Definition at line 216 of file src/mvrtree/MVRTree.h.
Referenced by flush().
Leaf
friend class Leaf friend
Definition at line 215 of file src/mvrtree/MVRTree.h.
Referenced by flush().
Node
friend class Node friend
Definition at line 214 of file src/mvrtree/MVRTree.h.
operator<<
std::ostream& operator<< (std::ostream & os, const MVRTree & t) friend
The documentation for this class was generated from the following files:
src/mvrtree/MVRTree.h
MVRTree.cc