libspatialindex API Reference: SpatialIndex::StorageManager::RandomEvictionsBuffer Class Reference
SpatialIndex::StorageManager::RandomEvictionsBuffer Class Reference
#include <RandomEvictionsBuffer.h>
Public Member Functions
RandomEvictionsBuffer (IStorageManager &, Tools::PropertySet &ps)
~RandomEvictionsBuffer () override
void addEntry (id_type page, Buffer::Entry *pEntry) override
void removeEntry () override
Public Member Functions inherited from SpatialIndex::StorageManager::Buffer
Buffer (IStorageManager &sm, Tools::PropertySet &ps)
~Buffer () override
void flush () override
void loadByteArray (const id_type page, uint32_t &len, uint8_t **data) override
void storeByteArray (id_type &page, const uint32_t len, const uint8_t *const data) override
void deleteByteArray (const id_type page) override
void clear () override
uint64_t getHits () override
Public Member Functions inherited from SpatialIndex::StorageManager::IBuffer
~IBuffer () override=default
Public Member Functions inherited from SpatialIndex::IStorageManager
virtual ~IStorageManager ()=default
Additional Inherited Members
Protected Attributes inherited from SpatialIndex::StorageManager::Buffer
uint32_t m_capacity
bool m_bWriteThrough
IStorageManager * m_pStorageManager
std::map< id_type, Entry * > m_buffer
uint64_t m_u64Hits
Detailed Description
Definition at line 36 of file RandomEvictionsBuffer.h.
Constructor & Destructor Documentation
RandomEvictionsBuffer()
RandomEvictionsBuffer::RandomEvictionsBuffer (IStorageManager & sm, Tools::PropertySet & ps)
Definition at line 63 of file RandomEvictionsBuffer.cc.
References srand48(), and ~RandomEvictionsBuffer().
~RandomEvictionsBuffer()
RandomEvictionsBuffer::~RandomEvictionsBuffer () override default
Referenced by RandomEvictionsBuffer().
Member Function Documentation
addEntry()
void RandomEvictionsBuffer::addEntry (id_type page, Buffer::Entry * pEntry) override virtual
Implements SpatialIndex::StorageManager::Buffer.
Definition at line 71 of file RandomEvictionsBuffer.cc.
References SpatialIndex::StorageManager::Buffer::m_buffer, SpatialIndex::StorageManager::Buffer::m_capacity, and removeEntry().
removeEntry()
void RandomEvictionsBuffer::removeEntry () override virtual
Implements SpatialIndex::StorageManager::Buffer.
Definition at line 80 of file RandomEvictionsBuffer.cc.
References drand48(), SpatialIndex::StorageManager::Buffer::m_buffer, SpatialIndex::StorageManager::Buffer::m_pStorageManager, and SpatialIndex::IStorageManager::storeByteArray().
Referenced by addEntry().
The documentation for this class was generated from the following files:
RandomEvictionsBuffer.h
RandomEvictionsBuffer.cc