libspatialindex API Reference: Tools::Exception Class Reference
Tools::Exception Class Reference abstract
#include <Tools.h>
Public Member Functions
virtual std::string what ()=0
virtual ~Exception ()=default
Detailed Description
Definition at line 118 of file Tools.h.
Constructor & Destructor Documentation
~Exception()
virtual Tools::Exception::~Exception () virtual default
Member Function Documentation
what()
virtual std::string Tools::Exception::what () pure virtual
Implemented in Tools::NotSupportedException, Tools::ResourceLockedException, Tools::EndOfStreamException, Tools::IllegalStateException, Tools::IllegalArgumentException, Tools::IndexOutOfBoundsException, and SpatialIndex::InvalidPageException.
Referenced by Index::Index(), Index_Contains_count(), Index_Contains_id(), Index_Contains_obj(), Index_Create(), Index_CreateWithStream(), Index_DeleteData(), Index_DeleteMVRData(), Index_DeleteTPData(), Index_GetBounds(), Index_GetLeaves(), Index_InsertData(), Index_InsertMVRData(), Index_InsertTPData(), Index_Intersects_count(), Index_Intersects_id(), Index_Intersects_internal(), Index_Intersects_obj(), Index_MVRIntersects_count(), Index_MVRIntersects_id(), Index_MVRIntersects_obj(), Index_MVRNearestNeighbors_id(), Index_MVRNearestNeighbors_obj(), Index_NearestNeighbors_id(), Index_NearestNeighbors_obj(), Index_SegmentIntersects_count(), Index_SegmentIntersects_id(), Index_SegmentIntersects_obj(), Index_TPIntersects_count(), Index_TPIntersects_id(), Index_TPIntersects_obj(), Index_TPNearestNeighbors_id(), Index_TPNearestNeighbors_obj(), IndexProperty_SetBufferingCapacity(), IndexProperty_SetCustomStorageCallbacks(), IndexProperty_SetCustomStorageCallbacksSize(), IndexProperty_SetDimension(), IndexProperty_SetEnsureTightMBRs(), IndexProperty_SetFileName(), IndexProperty_SetFileNameExtensionDat(), IndexProperty_SetFileNameExtensionIdx(), IndexProperty_SetFillFactor(), IndexProperty_SetIndexCapacity(), IndexProperty_SetIndexID(), IndexProperty_SetIndexPoolCapacity(), IndexProperty_SetIndexStorage(), IndexProperty_SetIndexType(), IndexProperty_SetIndexVariant(), IndexProperty_SetLeafCapacity(), IndexProperty_SetLeafPoolCapacity(), IndexProperty_SetNearMinimumOverlapFactor(), IndexProperty_SetOverwrite(), IndexProperty_SetPagesize(), IndexProperty_SetPointPoolCapacity(), IndexProperty_SetRegionPoolCapacity(), IndexProperty_SetReinsertFactor(), IndexProperty_SetResultSetLimit(), IndexProperty_SetSplitDistributionFactor(), IndexProperty_SetTPRHorizon(), and IndexProperty_SetWriteThrough().
The documentation for this class was generated from the following file:
Tools.h