libspatialindex API Reference: SpatialIndex::MVRTree Namespace Reference
SpatialIndex::MVRTree Namespace Reference
Classes
class Data
class Index
class Leaf
class MVRTree
class Node
class Statistics
Typedefs
typedef Tools::PoolPointer< Node > NodePtr
Enumerations
enum MVRTreeVariant { RV_LINEAR = 0x0, RV_QUADRATIC, RV_RSTAR }
enum PersistenObjectIdentifier { PersistentIndex = 0x1, PersistentLeaf = 0x2 }
enum RangeQueryType { ContainmentQuery = 0x1, IntersectionQuery = 0x2 }
Functions
SIDX_DLL ISpatialIndex * returnMVRTree (IStorageManager &ind, Tools::PropertySet &in)
SIDX_DLL ISpatialIndex * createNewMVRTree (IStorageManager &in, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, MVRTreeVariant rv, id_type &out_indexIdentifier)
SIDX_DLL ISpatialIndex * loadMVRTree (IStorageManager &in, id_type indexIdentifier)
std::ostream & operator<< (std::ostream &os, const MVRTree &t)
std::ostream & operator<< (std::ostream &os, const Statistics &s)
Typedef Documentation
NodePtr
typedef Tools::PoolPointer<Node> SpatialIndex::MVRTree::NodePtr
Definition at line 40 of file mvrtree/Node.h.
Enumeration Type Documentation
MVRTreeVariant
enum SpatialIndex::MVRTree::MVRTreeVariant
Enumerator
RV_LINEAR
RV_QUADRATIC
RV_RSTAR
Definition at line 34 of file include/spatialindex/MVRTree.h.
PersistenObjectIdentifier
enum SpatialIndex::MVRTree::PersistenObjectIdentifier
Enumerator
PersistentIndex
PersistentLeaf
Definition at line 41 of file include/spatialindex/MVRTree.h.
RangeQueryType
enum SpatialIndex::MVRTree::RangeQueryType
Enumerator
ContainmentQuery
IntersectionQuery
Definition at line 47 of file include/spatialindex/MVRTree.h.
Function Documentation
createNewMVRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::MVRTree::createNewMVRTree (SpatialIndex::IStorageManager & sm, double fillFactor, uint32_t indexCapacity, uint32_t leafCapacity, uint32_t dimension, MVRTreeVariant rv, id_type & out_indexIdentifier)
Definition at line 147 of file MVRTree.cc.
References Tools::Variant::dblVal, Tools::PropertySet::getProperty(), Tools::Variant::llVal, Tools::Variant::lVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnMVRTree(), Tools::PropertySet::setProperty(), Tools::Variant::ulVal, Tools::VT_DOUBLE, Tools::VT_LONG, Tools::VT_LONGLONG, and Tools::VT_ULONG.
loadMVRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::MVRTree::loadMVRTree (IStorageManager & in, id_type indexIdentifier)
Definition at line 188 of file MVRTree.cc.
References Tools::Variant::llVal, Tools::Variant::m_val, Tools::Variant::m_varType, returnMVRTree(), Tools::PropertySet::setProperty(), and Tools::VT_LONGLONG.
operator<<() [1/2]
std::ostream & SpatialIndex::MVRTree::operator<< (std::ostream & os, const Statistics & s)
Definition at line 170 of file mvrtree/Statistics.cc.
operator<<() [2/2]
std::ostream & SpatialIndex::MVRTree::operator<< (std::ostream & os, const MVRTree & t)
Definition at line 1316 of file MVRTree.cc.
References Tools::PointerPool< X >::m_hits, Tools::PointerPool< X >::m_misses, and RV_RSTAR.
returnMVRTree()
SpatialIndex::ISpatialIndex * SpatialIndex::MVRTree::returnMVRTree (SpatialIndex::IStorageManager & sm, Tools::PropertySet & in)
Definition at line 141 of file MVRTree.cc.
Referenced by createNewMVRTree(), and loadMVRTree().