var namespaceTools =
[
    [ "PointerPool", "classTools_1_1PointerPool.html", "classTools_1_1PointerPool" ],
    [ "PoolPointer", "classTools_1_1PoolPointer.html", "classTools_1_1PoolPointer" ],
    [ "SmartPointer", "classTools_1_1SmartPointer.html", "classTools_1_1SmartPointer" ],
    [ "Exception", "classTools_1_1Exception.html", "classTools_1_1Exception" ],
    [ "IndexOutOfBoundsException", "classTools_1_1IndexOutOfBoundsException.html", "classTools_1_1IndexOutOfBoundsException" ],
    [ "IllegalArgumentException", "classTools_1_1IllegalArgumentException.html", "classTools_1_1IllegalArgumentException" ],
    [ "IllegalStateException", "classTools_1_1IllegalStateException.html", "classTools_1_1IllegalStateException" ],
    [ "EndOfStreamException", "classTools_1_1EndOfStreamException.html", "classTools_1_1EndOfStreamException" ],
    [ "ResourceLockedException", "classTools_1_1ResourceLockedException.html", "classTools_1_1ResourceLockedException" ],
    [ "NotSupportedException", "classTools_1_1NotSupportedException.html", "classTools_1_1NotSupportedException" ],
    [ "IInterval", "classTools_1_1IInterval.html", "classTools_1_1IInterval" ],
    [ "IObject", "classTools_1_1IObject.html", "classTools_1_1IObject" ],
    [ "ISerializable", "classTools_1_1ISerializable.html", "classTools_1_1ISerializable" ],
    [ "IComparable", "classTools_1_1IComparable.html", "classTools_1_1IComparable" ],
    [ "IObjectComparator", "classTools_1_1IObjectComparator.html", "classTools_1_1IObjectComparator" ],
    [ "IObjectStream", "classTools_1_1IObjectStream.html", "classTools_1_1IObjectStream" ],
    [ "Variant", "classTools_1_1Variant.html", "classTools_1_1Variant" ],
    [ "PropertySet", "classTools_1_1PropertySet.html", "classTools_1_1PropertySet" ],
    [ "Interval", "classTools_1_1Interval.html", "classTools_1_1Interval" ],
    [ "Random", "classTools_1_1Random.html", "classTools_1_1Random" ],
    [ "BufferedFile", "classTools_1_1BufferedFile.html", "classTools_1_1BufferedFile" ],
    [ "BufferedFileReader", "classTools_1_1BufferedFileReader.html", "classTools_1_1BufferedFileReader" ],
    [ "BufferedFileWriter", "classTools_1_1BufferedFileWriter.html", "classTools_1_1BufferedFileWriter" ],
    [ "TemporaryFile", "classTools_1_1TemporaryFile.html", "classTools_1_1TemporaryFile" ],
    [ "PointerPool< SpatialIndex::MVRTree::Node >", "classTools_1_1PointerPool_3_01SpatialIndex_1_1MVRTree_1_1Node_01_4.html", "classTools_1_1PointerPool_3_01SpatialIndex_1_1MVRTree_1_1Node_01_4" ],
    [ "PointerPool< RTree::Node >", "classTools_1_1PointerPool_3_01RTree_1_1Node_01_4.html", "classTools_1_1PointerPool_3_01RTree_1_1Node_01_4" ],
    [ "PointerPool< SpatialIndex::TPRTree::Node >", "classTools_1_1PointerPool_3_01SpatialIndex_1_1TPRTree_1_1Node_01_4.html", "classTools_1_1PointerPool_3_01SpatialIndex_1_1TPRTree_1_1Node_01_4" ]
];