var namespaceSpatialIndex =
[
    [ "MVRTree", "namespaceSpatialIndex_1_1MVRTree.html", "namespaceSpatialIndex_1_1MVRTree" ],
    [ "RTree", "namespaceSpatialIndex_1_1RTree.html", "namespaceSpatialIndex_1_1RTree" ],
    [ "StorageManager", "namespaceSpatialIndex_1_1StorageManager.html", "namespaceSpatialIndex_1_1StorageManager" ],
    [ "TPRTree", "namespaceSpatialIndex_1_1TPRTree.html", "namespaceSpatialIndex_1_1TPRTree" ],
    [ "ICommand", "classSpatialIndex_1_1ICommand.html", "classSpatialIndex_1_1ICommand" ],
    [ "IData", "classSpatialIndex_1_1IData.html", "classSpatialIndex_1_1IData" ],
    [ "IDataStream", "classSpatialIndex_1_1IDataStream.html", "classSpatialIndex_1_1IDataStream" ],
    [ "IEntry", "classSpatialIndex_1_1IEntry.html", "classSpatialIndex_1_1IEntry" ],
    [ "IEvolvingShape", "classSpatialIndex_1_1IEvolvingShape.html", "classSpatialIndex_1_1IEvolvingShape" ],
    [ "INearestNeighborComparator", "classSpatialIndex_1_1INearestNeighborComparator.html", "classSpatialIndex_1_1INearestNeighborComparator" ],
    [ "INode", "classSpatialIndex_1_1INode.html", "classSpatialIndex_1_1INode" ],
    [ "InvalidPageException", "classSpatialIndex_1_1InvalidPageException.html", "classSpatialIndex_1_1InvalidPageException" ],
    [ "IQueryStrategy", "classSpatialIndex_1_1IQueryStrategy.html", "classSpatialIndex_1_1IQueryStrategy" ],
    [ "IShape", "classSpatialIndex_1_1IShape.html", "classSpatialIndex_1_1IShape" ],
    [ "ISpatialIndex", "classSpatialIndex_1_1ISpatialIndex.html", "classSpatialIndex_1_1ISpatialIndex" ],
    [ "IStatistics", "classSpatialIndex_1_1IStatistics.html", "classSpatialIndex_1_1IStatistics" ],
    [ "IStorageManager", "classSpatialIndex_1_1IStorageManager.html", "classSpatialIndex_1_1IStorageManager" ],
    [ "ITimeShape", "classSpatialIndex_1_1ITimeShape.html", "classSpatialIndex_1_1ITimeShape" ],
    [ "IVisitor", "classSpatialIndex_1_1IVisitor.html", "classSpatialIndex_1_1IVisitor" ],
    [ "LineSegment", "classSpatialIndex_1_1LineSegment.html", "classSpatialIndex_1_1LineSegment" ],
    [ "MovingPoint", "classSpatialIndex_1_1MovingPoint.html", "classSpatialIndex_1_1MovingPoint" ],
    [ "MovingRegion", "classSpatialIndex_1_1MovingRegion.html", "classSpatialIndex_1_1MovingRegion" ],
    [ "Point", "classSpatialIndex_1_1Point.html", "classSpatialIndex_1_1Point" ],
    [ "Region", "classSpatialIndex_1_1Region.html", "classSpatialIndex_1_1Region" ],
    [ "TimePoint", "classSpatialIndex_1_1TimePoint.html", "classSpatialIndex_1_1TimePoint" ],
    [ "TimeRegion", "classSpatialIndex_1_1TimeRegion.html", "classSpatialIndex_1_1TimeRegion" ]
];