libspatialindex API Reference: rand48.h File Reference
rand48.h File Reference
Macros
#define __THROW
#define __NTH(fct) fct
Functions
void srand48 (long int seed) __THROW
unsigned short * seed48 (unsigned short xseed[3]) __THROW
long nrand48 (unsigned short xseed[3]) __THROW
long mrand48 (void) __THROW
long lrand48 (void) __THROW
void lcong48 (unsigned short p[7]) __THROW
long jrand48 (unsigned short xseed[3]) __THROW
double erand48 (unsigned short xseed[3]) __THROW
double drand48 (void) __THROW
Macro Definition Documentation
__NTH
#define __NTH (fct) fct
Definition at line 65 of file rand48.h.
__THROW
#define __THROW
Definition at line 61 of file rand48.h.
Function Documentation
drand48()
double drand48 (void)
Definition at line 145 of file rand48.cc.
References __rand48_Seed, and erand48().
Referenced by SpatialIndex::StorageManager::RandomEvictionsBuffer::removeEntry().
erand48()
double erand48 (unsigned short xseed[3])
Definition at line 136 of file rand48.cc.
References _dorand48().
Referenced by drand48(), and Tools::Random::nextUniformDouble().
jrand48()
long jrand48 (unsigned short xseed[3])
Definition at line 129 of file rand48.cc.
References _dorand48().
Referenced by Tools::Random::nextUniformLong().
lcong48()
void lcong48 (unsigned short p[7])
Definition at line 118 of file rand48.cc.
References __rand48_Add, __rand48_Mult, and __rand48_Seed.
lrand48()
long lrand48 (void)
Definition at line 111 of file rand48.cc.
References __rand48_Seed, and _dorand48().
mrand48()
long mrand48 (void)
Definition at line 104 of file rand48.cc.
References __rand48_Seed, and _dorand48().
nrand48()
long nrand48 (unsigned short xseed[3])
Definition at line 98 of file rand48.cc.
References _dorand48().
seed48()
unsigned short* seed48 (unsigned short xseed[3])
Definition at line 80 of file rand48.cc.
References __rand48_Add, __rand48_Mult, __rand48_Seed, RAND48_ADD, RAND48_MULT_0, RAND48_MULT_1, and RAND48_MULT_2.
srand48()
void srand48 (long int seed)
Referenced by SpatialIndex::StorageManager::RandomEvictionsBuffer::RandomEvictionsBuffer(), and Tools::Random::~Random().